package com.DevSalud.DSB.Controller;

import java.time.format.DateTimeFormatter;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;

import com.DevSalud.DSB.Model.ExerciseLogModel;
import com.DevSalud.DSB.Model.UserModel;
import com.DevSalud.DSB.Service.ExerciseLogServices;
import com.DevSalud.DSB.Service.UserServices;

import jakarta.servlet.http.HttpSession;
import lombok.Data;

@Data
@Controller
@RequestMapping(path = "/Api/Users/Exercises")
public class ExercisesController {

    @Autowired
    private UserServices userService;

    @Autowired
    private ExerciseLogServices exerciseLogService;

    @ModelAttribute("allTipEjercicios")
    public List<String> tiposDeEjercicios() {
        return Arrays.asList("Aerobico", "Anaerobicos", "Fuerza", "Resistencia", "Pecho", "Pierna",
                "Hombro", "Espalda", "Biceps", "Triceps", "Abdominales", "Antebrazo", "Pantorrilla",
                "Equilibrio", "Fortalecimiento", "Flexibilidad");
    }

    @ModelAttribute("allIntecidadEjercicios")
    public List<String> intecidadDeEjercicios() {
        return Arrays.asList("Baja", "Media", "Alta");
    }

    @ModelAttribute("allNameEjercicios")
    public Map<String, List<String>> nombreDeLosEjercicios() {
        Map<String, List<String>> ejercicios = new HashMap<>();

        ejercicios.put("Aerobico", Arrays.asList(
                "Flexiones De Brazo (Push-ups)", "Flexiones De Diamante", "Flexiones Declinadas",
                "Flexiones Inclinadas",
                "Flexiones Con Palmada", "Flexiones De Pica (Pike push-ups)",
                "Flexiones De Brazos Abiertas",
                "Flexiones Con Pierna Elevada", "Flexiones Hindúes (Hindu push-ups)",
                "Fondos De Tríceps En Silla",
                "Sentadillas", "Sentadillas Con Salto", "Sentadillas Búlgaras", "Sentadillas De Sumo",
                "Sentadillas Con Una Pierna (Pistol squats)", "Estocadas", "Estocadas Laterales",
                "Estocadas Inversas",
                "Estocadas Con Salto", "Puentes De Glúteos", "Elevaciones De Talón",
                "Elevaciones De Pierna En Decúbito Supino",
                "Elevaciones De Pierna En Decúbito Lateral", "Elevaciones De Pierna En Decúbito Prono",
                "Elevaciones De Rodilla",
                "Elevaciones De Cadera", "Planchas", "Planchas Laterales",
                "Planchas Con Toque De Hombro",
                "Planchas Con Elevación De Pierna", "Burpees", "Alpinistas",
                "Abdominales Tradicionales",
                "Abdominales Tipo Bicicleta", "Abdominales Con Toque De Talones",
                "Abdominales Con Piernas Elevadas",
                "Abdominales Laterales", "Abdominales En V", "Levantamiento De Cadera",
                "Escaladores En El Suelo",
                "Escaladores Cruzados", "Tuck Jumps", "Rodillas Al Pecho",
                "Sentadillas Tipo Sumo Con Peso Corporal",
                "Patadas Laterales", "Patadas Frontales", "Elevaciones De Talones Sobre Un Escalón",
                "Fondos De Tríceps Con Una Silla",
                "Flexiones Con Las Rodillas En El Suelo", "Flexiones De Bíceps Con Bandas Elásticas",
                "Flexiones De Tríceps Con Bandas Elásticas",
                "Elevaciones Laterales Con Bandas Elásticas",
                "Elevaciones Frontales Con Bandas Elásticas",
                "Elevaciones De Cadera Con Bandas Elásticas",
                "Peso Muerto Con Bandas Elásticas", "Sentadillas Con Bandas Elásticas",
                "Prensa De Hombros Con Bandas Elásticas",
                "Desplantes Con Bandas Elásticas", "Remo Con Bandas Elásticas",
                "Desplantes Laterales Con Bandas Elásticas",
                "Tirones De Banda Elástica", "Flexiones De Bíceps Con Mancuernas",
                "Flexiones De Tríceps Con Mancuernas",
                "Prensa De Pecho Con Mancuernas", "Peso Muerto Con Mancuernas", "Remo Con Mancuernas",
                "Prensa De Hombros Con Mancuernas", "Elevaciones Laterales Con Mancuernas",
                "Elevaciones Frontales Con Mancuernas",
                "Sentadillas Con Mancuernas", "Desplantes Con Mancuernas", "Fondos Con Mancuernas",
                "Extensiones De Tríceps Con Mancuernas", "Elevaciones De Talón Con Mancuernas",
                "Peso Muerto A Una Pierna Con Mancuernas", "Remo Unilateral Con Mancuernas",
                "Flexiones De Bíceps Con Mancuernas De Martillo",
                "Flexiones De Bíceps Alternadas Con Mancuernas",
                "Flexiones Con Mancuernas Tipo Martillo", "Peso Muerto Rumano Con Mancuernas",
                "Curl De Bíceps En Martillo",
                "Prensa De Pecho Con Mancuernas En Banco", "Sentadillas Tipo Sumo Con Mancuernas",
                "Elevaciones De Talón Con Mancuernas En Banco",
                "Peso Muerto Rumano A Una Pierna Con Mancuernas",
                "Sentadillas De Sumo Con Bandas Elásticas", "Desplantes Inversos Con Bandas Elásticas",
                "Peso Muerto A Una Pierna Con Bandas Elásticas",
                "Fondos De Tríceps Con Bandas Elásticas",
                "Abdominales Tipo Bicicleta Con Bandas Elásticas",
                "Flexiones De Pecho Con Bandas Elásticas",
                "Remo Con Bandas Elásticas En Una Pierna", "Desplantes Laterales Con Bandas Elásticas",
                "Planchas Con Bandas Elásticas", "Flexiones Con Bandas Elásticas En Brazos",
                "Abdominales Laterales Con Bandas Elásticas",
                "Abdominales Tipo Bicicleta Con Bandas Elásticas",
                "Fondos De Tríceps En Silla Con Bandas Elásticas",
                "Prensa De Pecho Con Bandas Elásticas En Banco"));

        ejercicios.put("Anaerobicos", Arrays.asList(
                "Saltos De Tijera",
                "Burpees",
                "Escaladores De Montaña",
                "Saltos De Cuerda",
                "Correr En El Lugar",
                "Correr Con Elevación De Rodillas",
                "Correr Con Talones Hacia Atrás",
                "Tuck Jumps",
                "Pasos Laterales",
                "Saltos Laterales",
                "Saltos En Caja",
                "Saltos En Cuclillas",
                "Patadas Altas",
                "Patadas De Bicicleta En El Suelo",
                "Abdominales Tipo Bicicleta",
                "Escaladores Cruzados",
                "Rodillas Al Pecho",
                "Skipping",
                "Skaters",
                "Salto De Estrella",
                "Saltos De Cangrejo",
                "Saltos A Una Pierna",
                "Sentadillas Con Salto",
                "Sentadillas Con Toque De Tobillo",
                "Tabata De Burpees",
                "Tabata De Saltos De Tijera",
                "Tabata De Escaladores",
                "Sentadillas Con Desplazamiento Lateral",
                "Saltos En Zig-Zag",
                "Pasos Altos En El Sitio",
                "Saltos De Rana",
                "Lunge Con Salto",
                "Sentadillas Laterales Con Salto",
                "Salto Con Giro",
                "Saltos Con Codos A Las Rodillas",
                "Step-up Con Salto",
                "Salto Lateral De Tronco",
                "Saltos De Estrella Con Giros",
                "Salto Con Patada Frontal",
                "Salto Con Patada Lateral",
                "Saltos Con Patada Trasera",
                "Sentadillas Con Desplazamiento Circular",
                "Saltos En V",
                "Correr Subiendo Escaleras",
                "Jump Squat En Cruz",
                "Saltos Laterales Con Rodilla Arriba",
                "Sentadillas Pliométricas",
                "Salto En Cruz Alternando Manos Y Pies",
                "Saltos De Conejo",
                "Jumping Jacks Con Salto Frontal",
                "Jumping Jacks Con Salto Trasero",
                "Patadas Laterales En Desplazamiento",
                "Patadas Frontales En Desplazamiento",
                "Step-up Rápido",
                "Pasos Laterales Rápidos",
                "Correr Tocando El Suelo",
                "Escaladores De Montaña Lentos Y Rápidos",
                "Jump Squat Con Rodillas Altas",
                "Sentadillas Con Toque De Talón",
                "Escaladores Con Toque De Codo",
                "Sentadillas Con Salto Y Toque De Mano",
                "Jump Squat Con Toque De Suelo",
                "Correr En Círculos",
                "Patadas De Burro",
                "Plancha Con Toque De Pie",
                "Saltos De Tijera Con Variaciones",
                "Saltos Con Talones A Las Manos",
                "Correr Lateral",
                "Sentadillas En 360 Grados",
                "Saltos En Estrellas Laterales",
                "Pasos Cruzados Rápidos",
                "Step-up En Cruz",
                "Patadas Con Salto Y Giro",
                "Sentadillas Con Patadas Altas",
                "Escaladores Con Salto",
                "Lunge Con Salto Cruzado",
                "Planchas Con Salto Y Elevación",
                "Saltos De Tríceps",
                "Sentadilla Con Salto Y Elevacion",
                "Salto En Estrella En El Suelo",
                "Escaladores De Montaña Con Patada Lateral",
                "Jumping Jacks En Rotación",
                "Burpees Con Salto Y Toque",
                "Saltos Con Elevación De Brazos",
                "Saltos En Tijera Alternando Manos Y Pies",
                "Saltos En Cruz Con Elevación De Piernas",
                "Saltos En V Con Toque De Codo",
                "Patadas Laterales Con Salto Y Toque De Suelo",
                "Lunge Con Salto Y Elevación",
                "Saltos En Cruz Con Elevación De Brazos",
                "Sentadillas Con Salto Y Patada Lateral",
                "Jump Squat Con Toque De Codo",
                "Lunge Con Salto Y Toque De Suelo",
                "Step-up Con Toque De Pie",
                "Sentadillas Con Salto En Círculo",
                "Planchas Con Salto Y Patadas Laterales",
                "Jumping Jacks Con Elevación De Pierna",
                "Burpees Con Salto Y Giro",
                "Saltos Laterales Con Elevación De Rodilla"));

        ejercicios.put("Pecho", Arrays.asList(
                "Flexiones De Brazo", "Flexiones De Diamante", "Flexiones Inclinadas",
                "Flexiones Declinadas", "Flexiones Con Palmada", "Flexiones Hindúes",
                "Flexiones Con Pies Elevados", "Flexiones Con Una Mano",
                "Flexiones Con Toque De Hombro",
                "Flexiones Escalonadas", "Flexiones Con Dedos", "Flexiones Arqueras",
                "Flexiones En Anillo", "Flexiones Con Deslizamiento Lateral",
                "Flexiones Con Cuerpo Recto",
                "Flexiones Con Brazos Abiertos", "Flexiones En Forma De T",
                "Flexiones Con Rodillas Al Pecho",
                "Flexiones Con Toque De Pie", "Flexiones Con Elevación De Pierna",
                "Flexiones Con Una Pierna Elevada",
                "Flexiones De Cangrejo", "Flexiones Con Desplazamiento Lateral",
                "Flexiones Con Rotación",
                "Flexiones Con Rebote", "Flexiones Con Rebote En Balón Medicinal", "Flexiones Cruzadas",
                "Flexiones Con Toque De Codo", "Flexiones Estilo Spiderman", "Flexiones Con Giro",
                "Flexiones Con Pies En Superficie Inestable", "Flexiones Con Cuerpo Recto En Balón",
                "Flexiones Con Desplazamiento Circular", "Flexiones De Pecho En Anillos",
                "Flexiones Con Brazo Elevado",
                "Flexiones Con Toque De Hombro Alterno", "Flexiones En Puente", "Flexiones En V",
                "Flexiones Con Anillo Y Giro", "Flexiones De Pecho Con Salto",
                "Flexiones Con Banda Elástica",
                "Flexiones Tipo Superman", "Flexiones En X", "Flexiones En Y",
                "Flexiones Con Salto Y Giro",
                "Flexiones Con Caída", "Flexiones Con Elevación De Hombro", "Flexiones Alternadas",
                "Flexiones Con Elevación De Rodillas", "Prensa De Pecho Con Mancuernas",
                "Prensa De Pecho Con Bandas Elásticas",
                "Aperturas De Pecho Con Mancuernas", "Aperturas De Pecho Con Bandas Elásticas",
                "Pasos Laterales Rápidos",
                "Flexiones De Pecho Con Bandas Elásticas", "Prensa De Pecho En Banco Con Mancuernas",
                "Prensa De Pecho En Banco Declinado Con Mancuernas",
                "Prensa De Pecho En Banco Inclinado Con Mancuernas",
                "Prensa De Pecho En Banco Con Bandas Elásticas",
                "Prensa De Pecho Con Mancuernas En El Suelo",
                "Prensa De Pecho Con Bandas Elásticas En El Suelo",
                "Aperturas De Pecho Con Bandas Elásticas En Banco",
                "Prensa De Pecho Alternando Mancuernas",
                "Flexiones Con Mancuernas Con Rotación", "Prensa De Pecho Con Bandas Elásticas Y Giros",
                "Prensa De Pecho Con Mancuernas Y Elevación De Piernas",
                "Prensa De Pecho Con Bandas Elásticas Y Elevación De Piernas",
                "Flexiones De Pecho Con Mancuernas Y Elevación De Pies",
                "Prensa De Pecho Con Mancuernas Alternando Brazos",
                "Aperturas De Pecho Con Mancuernas Con Rotación",
                "Prensa De Pecho Con Bandas Elásticas En Banco Declinado",
                "Prensa De Pecho Con Bandas Elásticas En Banco Inclinado",
                "Flexiones Con Bandas Elásticas Y Elevación De Pies",
                "Aperturas De Pecho Con Bandas Elásticas Y Elevación De Pies",
                "Prensa De Pecho Con Bandas Elásticas Alternando Brazos",
                "Prensa De Pecho Con Bandas Elásticas Y Elevación De Piernas",
                "Prensa De Pecho Con Mancuernas Y Elevación De Pies",
                "Flexiones De Pecho Con Bandas Elásticas Y Elevación De Pies",
                "Flexiones De Pecho Con Mancuernas Y Rotación",
                "Flexiones Con Bandas Elásticas Y Giro De Torso",
                "Flexiones Con Bandas Elásticas Y Elevación De Pierna",
                "Prensa De Pecho En Banco Plano Con Mancuernas",
                "Flexiones Con Mancuernas Y Elevación De Pies",
                "Prensa De Pecho Con Bandas Elásticas Y Giro",
                "Flexiones De Pecho Con Mancuernas Y Elevación De Pies",
                "Flexiones De Pecho En Banco Plano Con Mancuernas",
                "Flexiones Con Bandas Elásticas Y Giro De Torso",
                "Prensa De Pecho Con Bandas Elásticas Y Elevación De Piernas",
                "Flexiones De Pecho Con Bandas Elásticas Y Elevación De Pies",
                "Aperturas De Pecho Con Mancuernas Con Rotación",
                "Prensa De Pecho En Banco Plano Con Mancuernas",
                "Flexiones Con Bandas Elásticas Y Giro De Torso",
                "Prensa De Pecho Con Bandas Elásticas En Banco Declinado",
                "Flexiones Con Bandas Elásticas Y Elevación De Piernas",
                "Flexiones De Pecho En Banco Plano Con Mancuernas",
                "Prensa De Pecho Con Bandas Elásticas Y Elevación De Pies",
                "Flexiones Pe Pecho Con Mancuernas Y Rotación",
                "Aperturas De Pecho Con Bandas Elásticas Y Elevación De Piernas",
                "Flexiones De Pecho En Banco Plano Con Bandas Elásticas",
                "Flexiones Con Bandas Elásticas Y Elevación De Pies"));

        ejercicios.put("Pierna", Arrays.asList(
                "Sentadillas",
                "Sentadillas Con Salto",
                "Sentadillas De Sumo",
                "Sentadillas Búlgaras",
                "Sentadillas De Pistola",
                "Sentadillas Con Una Pierna En Banco",
                "Sentadillas Pliométricas",
                "Sentadillas Con Pies Juntos",
                "Sentadillas Con Pies Separados",
                "Sentadillas Con Paso Lateral",
                "Sentadillas Con Elevación De Talones",
                "Sentadillas Con Elevación De Brazos",
                "Sentadillas Con Elevación De Rodillas",
                "Sentadillas Con Salto Y Rotación",
                "Sentadillas Tipo Box",
                "Sentadillas Con Toque De Tobillo",
                "Sentadillas Con Puente De Glúteos",
                "Sentadillas Con Elevación De Cadera",
                "Sentadillas Con Giro De Torso",
                "Sentadillas Con Desplazamiento Lateral",
                "Desplantes",
                "Desplantes Con Salto",
                "Desplantes Laterales",
                "Desplantes Cruzados",
                "Desplantes Inversos",
                "Desplantes Con Rotación De Torso",
                "Desplantes En Cruz",
                "Desplantes Con Elevación De Rodillas",
                "Desplantes Con Elevación De Talones",
                "Desplantes Con Giro De Torso",
                "Desplantes Con Elevación De Brazos",
                "Desplantes Con Elevación De Pierna",
                "Desplantes Con Desplazamiento Lateral",
                "Desplantes Con Pies Juntos",
                "Desplantes Con Giro De Cadera",
                "Elevaciones De Talones",
                "Elevaciones De Talones Con Una Pierna",
                "Elevaciones De Talones En Escalón",
                "Elevaciones De Talones Con Desplazamiento Lateral",
                "Elevaciones De Talones Con Peso Corporal",
                "Elevaciones De Talones Con Flexión De Rodilla",
                "Elevaciones De Talones Con Salto",
                "Elevaciones De Talones Alternadas",
                "Elevaciones De Talones Con Giro De Pie",
                "Elevaciones De Talones Con Elevación De Cadera",
                "Elevaciones De Talones Con Elevación De Rodillas",
                "Puentes De Glúteos",
                "Puentes De Glúteos Con Elevación De Pierna",
                "Puentes De Glúteos Con Elevación De Talones",
                "Puentes De Glúteos Con Salto",
                "Sentadillas Con Mancuernas",
                "Sentadillas Con Barra",
                "Sentadillas Con Bandas Elásticas",
                " Sentadillas Con Peso En Banco",
                "Sentadillas Con Mancuernas En Banco",
                "Sentadillas Con Mancuernas En Suelo",
                "Sentadillas Con Mancuernas Y Elevación De Talones",
                "Sentadillas Con Mancuernas Y Elevación De Rodillas",
                "Sentadillas Con Mancuernas Y Desplazamiento Lateral",
                "Sentadillas Con Bandas Elásticas Y Elevación De Talones",
                "Sentadillas Con Bandas Elásticas Y Desplazamiento Lateral",
                "Sentadillas Con Mancuernas Y Elevación De Cadera",
                "Sentadillas Con Mancuernas Y Salto",
                "Desplantes Con Mancuernas",
                "Desplantes Laterales Con Mancuernas",
                "Desplantes Inversos Con Mancuernas",
                "Desplantes Con Bandas Elásticas",
                "Desplantes Laterales Con Bandas Elásticas",
                "Desplantes Inversos Con Bandas Elásticas",
                "Desplantes Cruzados Con Mancuernas",
                "Desplantes Cruzados Con Bandas Elásticas",
                "Desplantes Con Mancuernas Y Elevación De Rodillas",
                "Desplantes Con Bandas Elásticas Y Elevación De Rodillas",
                "Desplantes Con Mancuernas Y Elevación De Talones",
                "Desplantes Con Bandas Elásticas Y Elevación De Talones",
                "Elevaciones De Talones Con Mancuernas",
                "Elevaciones De Talones Con Barra",
                "Elevaciones De Talones Con Bandas Elásticas",
                "Elevaciones De Talones Con Mancuernas En Banco",
                "Elevaciones De Talones Con Mancuernas Y Salto",
                "Puentes De Glúteos Con Mancuernas",
                "Puentes De Glúteos Con Bandas Elásticas",
                "Puentes De Glúteos Con Mancuernas Y Elevación De Pierna",
                "Puentes De Glúteos Con Bandas Elásticas Y Elevación De Pierna",
                "Puentes De Glúteos Con Mancuernas Y Elevación De Talones",
                "Puentes De Glúteos Con Bandas Elásticas Y Elevación De Talones",
                "Elevaciones De Cadera Con Mancuernas",
                "Elevaciones De Cadera Con Bandas Elásticas",
                "Elevaciones De Cadera Con Mancuernas Y Salto",
                "Peso Muerto Con Mancuernas",
                "Peso Muerto Con Bandas Elásticas",
                "Peso Muerto Rumano Con Mancuernas",
                "Peso Muerto Rumano Con Bandas Elásticas",
                "Peso Muerto A Una Pierna Con Mancuernas",
                "Peso Muerto A Una Pierna Con Bandas Elásticas",
                "Peso Muerto Con Mancuernas Y Salto",
                "Sentadillas Con Bandas Elásticas Y Salto",
                "Desplantes Con Bandas Elásticas Y Salto",
                "Puentes De Glúteos Con Bandas Elásticas Y Salto",
                "Elevaciones De Cadera Con Mancuernas Y Salto"));

        ejercicios.put("Hombro", Arrays.asList(
                "Flexiones De Pica", "Flexiones Hindúes", "Flexiones Declinadas",
                "Flexiones De Brazo Inclinadas",
                "Flexiones En Plancha",
                "Flexiones En T", "Flexiones Arqueras", "Flexiones Con Rotación",
                "Flexiones Con Toque De Hombro",
                "Flexiones De Tríceps",
                "Flexiones Con Desplazamiento Lateral", "Flexiones Con Rotación Del Tronco",
                "Flexiones Declinadas Con Pica",
                "Flexiones Con Cuerpo Recto", "Flexiones De Hombro En Pica",
                "Flexiones Con Desplazamiento Circular",
                "Flexiones Con Salto",
                "Flexiones Con Salto Y Giro", "Flexiones En Anillos", "Flexiones Con Dedos",
                "Fondos En Silla",
                "Fondos De Tríceps En Silla",
                "Fondos Entre Dos Sillas", "Flexiones Con Palmas Hacia Adentro",
                "Flexiones Con Banda Elástica",
                "Elevaciones Laterales De Brazo",
                "Elevaciones Laterales De Hombro", "Elevaciones Frontales De Hombro",
                "Elevaciones Laterales Con Giro",
                "Elevaciones Frontales Con Giro",
                "Flexiones De Tríceps En Banco", "Planchas Laterales",
                "Planchas Con Elevación De Brazo",
                "Planchas Con Toque De Hombro",
                "Flexiones De Diamante", "Flexiones De Hombro A Una Mano", "Flexiones Tipo Crucifixión",
                "Flexiones Con Pica Y Desplazamiento",
                "Flexiones De Puente", "Flexiones Con Peso En Espalda",
                "Planchas Laterales Con Toque De Hombro",
                "Planchas Con Giro",
                "Flexiones En Plancha", "Planchas Con Elevación De Cadera",
                "Planchas Con Elevación De Pierna",
                "Flexiones En V",
                "Flexiones Con Despliegue", "Flexiones Con Desplazamiento Lateral", "Flexiones En X",
                "Flexiones En Y",
                "Elevaciones Laterales Con Bandas Elásticas",
                "Elevaciones Frontales Con Bandas Elásticas",
                "Prensa De Hombro Con Bandas Elásticas",
                "Prensa De Hombro Con Bandas Elásticas Alternando Brazos",
                "Elevaciones Laterales Con Bandas Elásticas Cruzadas",
                "Elevaciones Frontales Con Bandas Elásticas Y Giro",
                "Prensa De Hombro Con Bandas Elásticas Y Elevación De Pie",
                "Prensa De Hombro Con Bandas Elásticas Con Elevación De Talones",
                "Elevaciones Laterales En Cruz Con Bandas Elásticas",
                "Elevaciones Frontales Con Bandas Elásticas Y Giro De Torso",
                "Prensa De Hombro Con Bandas Elásticas Y Elevación De Cadera",
                "Elevaciones Laterales Con Bandas Elásticas Y Elevación De Brazo",
                "Elevaciones Laterales Con Bandas Elásticas Y Giro De Torso",
                "Prensa De Hombro Con Bandas Elásticas En Banco",
                "Elevaciones Frontales Con Bandas Elásticas Con Giro De Pie",
                "Prensa De Hombro Con Bandas Elásticas Y Elevación De Pierna",
                "Prensa De Hombro Con Bandas Elásticas Y Salto",
                "Elevaciones Laterales Con Bandas Elásticas Y Elevación De Brazo",
                "Elevaciones Frontales Con Bandas Elásticas Y Elevación De Pie",
                "Prensa De Hombro Con Bandas Elásticas Con Elevación De Pie",
                "Elevaciones Laterales En Cruz Con Bandas Elásticas",
                "Elevaciones Laterales Con Bandas Elásticas En Banco",
                "Elevaciones Frontales Con Bandas Elásticas Y Elevación De Brazo",
                "Prensa De Hombro Con Bandas Elásticas Y Elevación De Pie",
                "Elevaciones Laterales Con Bandas Elásticas Con Rotación De Torso",
                "Elevaciones Laterales Con Mancuernas", "Elevaciones Frontales Con Mancuernas",
                "Prensa De Hombro Con Mancuernas",
                "Prensa De Hombro Con Mancuernas En Banco",
                "Prensa De Hombro Con Mancuernas Alternando Brazos",
                "Prensa De Hombro Con Mancuernas Y Giro De Torso",
                "Elevaciones Laterales En Cruz Con Mancuernas",
                "Elevaciones Frontales Con Mancuernas Y Giro De Torso",
                "Elevaciones Laterales Con Mancuernas En Banco",
                "Elevaciones Laterales Con Mancuernas Con Rotación De Torso",
                "Elevaciones Frontales Con Mancuernas Y Elevación De Brazo",
                "Prensa De Hombro Con Mancuernas En Banco",
                "Elevaciones Laterales Con Mancuernas Con Elevación De Pie",
                "Prensa De Hombro Con Mancuernas Con Elevación De Pie",
                "Elevaciones Laterales En Cruz Con Mancuernas En Banco",
                "Elevaciones Laterales Con Mancuernas Y Elevación De Cadera",
                "Elevaciones Laterales Con Mancuernas Y Elevación De Pie",
                "Elevaciones Frontales Con Mancuernas Con Giro De Torso",
                "Prensa De Hombro Con Mancuernas En Banco",
                "Elevaciones Laterales Con Mancuernas Y Elevación De Pie",
                "Elevaciones Laterales Con Mancuernas Con Rotación De Torso",
                "Prensa De Hombro Con Mancuernas Y Elevación De Pie",
                "Prensa De Hombro Con Mancuernas Y Giro De Torso",
                "Elevaciones Laterales Con Mancuernas Y Elevación De Pie",
                "Prensa De Hombro Con Mancuernas Y Elevación De Cadera"));

        ejercicios.put("Triceps", Arrays.asList(
                "Fondos En Silla",
                "Fondos Entre Dos Sillas",
                "Fondos En El Suelo",
                "Flexiones De Diamante",
                "Flexiones Declinadas Con Agarre Cerrado",
                "Flexiones Declinadas Con Diamante",
                "Flexiones Inclinadas Con Agarre Cerrado",
                "Flexiones Inclinadas Con Diamante",
                "Flexiones De Tríceps Con El Torso Recto",
                "Flexiones De Pica Con Agarre Cerrado",
                "Flexiones Con Toque De Hombro",
                "Flexiones Con Agarre Estrecho",
                "Flexiones Escalonadas",
                "Flexiones Con Rotación",
                "Fondos De Tríceps En Banco",
                "Fondos Con Salto",
                "Fondos De Tríceps Con Elevación De Pierna",
                "Fondos De Tríceps Con Elevación De Cadera",
                "Flexiones Con Elevación De Pierna",
                "Flexiones Con Codos Hacia Atrás",
                "Flexiones En Forma De V",
                "Fondos De Tríceps Con Toque De Codo",
                "Flexiones De Diamante Con Elevación De Pierna",
                "Flexiones De Diamante En Pica",
                "Flexiones De Tríceps En Banco",
                "Fondos De Tríceps Con Rotación",
                "Fondos Con Cuerpo Recto",
                "Fondos Entre Dos Mesas",
                "Fondos Con Elevación De Pierna Alternada",
                "Flexiones De Codos Cerrados",
                "Flexiones Tipo Arqueras",
                "Fondos De Tríceps Con Elevación De Cadera",
                "Fondos De Tríceps Con Giro De Torso",
                "Fondos De Tríceps En Banco Declinado",
                "Fondos De Tríceps En Banco Inclinado",
                "Fondos En Caja",
                "Fondos En Plataforma",
                "Fondos De Tríceps Con Elevación De Brazos",
                "Flexiones Con Pica Y Desplazamiento",
                "Flexiones Con Peso En Espalda",
                "Flexiones De Tríceps En V",
                "Flexiones Con Pica Y Rotación",
                "Flexiones De Cangrejo",
                "Fondos De Tríceps Con Rebote",
                "Fondos Con Elevación De Talones",
                "Fondos Con Rotación",
                "Fondos Con Desplazamiento Lateral",
                "Fondos Entre Dos Bancos",
                " Flexiones De Tríceps Con Elevación De Talones",
                "Fondos Con Rotación De Torso",
                "Extensión De Tríceps Con Bandas Elásticas",
                "Extensión De Tríceps Sobre La Cabeza Con Bandas Elásticas",
                "Extensión De Tríceps En Banco Con Bandas Elásticas",
                "Prensa De Tríceps Con Bandas Elásticas",
                "Extensión De Tríceps En Posición De Flexión",
                "Extensión De Tríceps Con Bandas Elásticas Desde Banco",
                "Extensión De Tríceps Desde Cadera Con Bandas Elásticas",
                "Extensión De Tríceps Cruzada Con Bandas Elásticas",
                "Extensión De Tríceps Con Giro De Torso",
                "Extensión De Tríceps Con Banda Elástica Y Elevación De Cadera",
                "Extensión De Tríceps Con Bandas Elásticas Desde El Suelo",
                "Extensión De Tríceps Con Bandas Elásticas Desde Arriba",
                "Extensión De Tríceps En Banco Inclinado Con Bandas Elásticas",
                "Extensión De Tríceps Con Bandas Elásticas Y Elevación De Pie",
                "Extensión De Tríceps Con Bandas Elásticas Y Giro De Torso",
                "Extensión De Tríceps Cruzada Con Bandas Elásticas Desde El Suelo",
                "Extensión De Tríceps En Banco Con Bandas Elásticas Con Elevación De Cadera",
                "Extensión De Tríceps En Banco Con Bandas Elásticas Con Giro De Torso",
                "Extensión De Tríceps Con Bandas Elásticas Desde Banco Declinado",
                "Extensión De Tríceps Con Bandas Elásticas Y Elevación De Talones",
                "Extensión De Tríceps Con Bandas Elásticas Y Elevación De Cadera",
                "Extensión De Tríceps Cruzada Con Bandas Elásticas Desde Banco",
                "Extensión De Tríceps En Banco Con Bandas Elásticas Con Giro De Cadera",
                "Extensión De Tríceps En Banco Declinado Con Bandas Elásticas Y Elevación De Cadera",
                "Extensión De Tríceps En Banco Inclinado Con Bandas Elásticas Y Elevación De Cadera",
                "Extensión De Tríceps Sobre La Cabeza",
                "Extensión De Tríceps Con Mancuernas",
                "Extensión De Tríceps En Banco Inclinado",
                "Extensión De Tríceps En Banco Declinado",
                "Extensión De Tríceps En Banco Plano",
                "Prensa De Tríceps En Banco Plano",
                "Prensa De Tríceps En Banco Declinado",
                "Prensa De Tríceps En Banco Inclinado",
                "Prensa De Tríceps Con Mancuernas Y Giro De Torso",
                "Extensión De Tríceps Sobre La Cabeza Con Mancuernas",
                "Prensa De Tríceps Con Mancuernas En Banco",
                "Extensión De Tríceps Cruzada Con Mancuernas",
                "Extensión De Tríceps Con Mancuernas Y Elevación De Talones",
                "Extensión De Tríceps En Banco Declinado Con Mancuernas Y Elevación De Cadera",
                "Extensión De Tríceps En Banco Plano Con Mancuernas Y Elevación De Cadera",
                "Extensión De Tríceps Cruzada Con Mancuernas Desde Banco",
                "Extensión De Tríceps Sobre La Cabeza Con Mancuernas Desde Banco",
                "Prensa De Tríceps Con Mancuernas Con Elevación De Cadera",
                "Extensión De Tríceps Sobre La Cabeza Con Mancuernas Con Elevación De Talones",
                "Extensión De Tríceps En Banco Declinado Con Mancuernas Y Elevación De Talones",
                "Extensión De Tríceps En Banco Inclinado Con Mancuernas Y Elevación De Cadera",
                "Prensa De Tríceps En Banco Plano Con Mancuernas Y Giro De Torso",
                "Prensa De Tríceps En Banco Inclinado Con Mancuernas Con Elevación De Talones",
                "Prensa De Tríceps En Banco Declinado Con Mancuernas Y Elevación De Cadera",
                "Extensión De Tríceps Cruzada Con Mancuernas En Banco Inclinado"));

        ejercicios.put("Biceps", Arrays.asList(
                "Flexiones Con Agarre Estrecho", "Flexiones De Diamante", "Flexiones Escalonadas",
                "Flexiones Arqueras", "Flexiones Con Rotación Del Torso",
                "Flexiones Con Rotación De Brazos",
                "Flexiones De Cuerpo Recto", "Flexiones De Manos Invertidas",
                "Flexiones Con Palma Hacia Arriba",
                "Flexiones Con Toque De Hombro", "Flexiones Con Peso En Espalda",
                "Flexiones Con Elevación De Pies",
                "Flexiones De Diamante Con Toque De Codo", "Flexiones Inclinadas Con Agarre Estrecho",
                "Flexiones Declinadas Con Agarre Estrecho", "Flexiones Escalonadas Con Rotación",
                "Flexiones De Cangrejo",
                "Flexiones De Diamante En Pica", "Flexiones De Diamante Con Elevación De Pierna",
                "Flexiones Con Manos Invertidas Y Toque De Hombro", "Flexiones Con Palma Hacia Abajo",
                "Flexiones De Diamante Declinadas", "Flexiones Con Toque De Hombro Y Palma Invertida",
                "Flexiones De Diamante Con Elevación De Cadera", "Flexiones Con Elevación De Talones",
                "Flexiones De Diamante Con Elevación De Pie", "Flexiones Con Codos Hacia Afuera",
                "Flexiones De Diamante Con Elevación De Cadera", "Flexiones Con Rotación De Codo",
                "Flexiones Escalonadas Con Elevación De Pierna",
                "Flexiones En Pica Con Agarre Estrecho",
                "Flexiones De Diamante Con Rotación", "Flexiones Con Agarre Estrecho Con Giro",
                "Flexiones De Diamante Con Rotación De Torso",
                "Flexiones De Diamante Con Elevación De Talones",
                "Flexiones Escalonadas Con Rotación De Codo",
                "Flexiones Inclinadas Con Rotación De Codo",
                "Flexiones Escalonadas Con Elevación De Cadera", "Flexiones Con Toque De Codo",
                "Flexiones De Diamante Con Salto", "Flexiones De Diamante Con Palma Hacia Abajo",
                "Flexiones De Diamante Con Elevación De Pierna Alternada",
                "Flexiones Con Agarre Estrecho Con Rotación",
                "Flexiones Con Elevación De Cadera", "Flexiones Con Rotación De Torso",
                "Flexiones Con Elevación De Talones",
                "Flexiones Con Giro De Torso", "Flexiones De Diamante Con Salto",
                "Flexiones De Diamante Con Rotación De Cuerpo",
                "Flexiones De Bíceps Con Bandas Elásticas", "Curl De Bíceps Con Bandas Elásticas",
                "Curl De Bíceps Con Bandas Elásticas Alternado",
                "Curl De Bíceps Con Bandas Elásticas Cruzadas",
                "Curl De Bíceps Con Bandas Elásticas Y Elevación De Cadera",
                "Curl De Bíceps Con Bandas Elásticas Con Giro De Torso",
                "Flexión De Bíceps Con Bandas Elásticas Y Elevación De Talones",
                "Flexión De Bíceps Con Bandas Elásticas Con Giro De Codo",
                "Flexión De Bíceps Con Bandas Elásticas Desde Banco",
                "Flexión De Bíceps Con Bandas Elásticas Desde El Suelo",
                "Flexión De Bíceps Con Bandas Elásticas Y Elevación De Pies",
                "Flexión De Bíceps Con Bandas Elásticas Con Elevación De Cadera",
                "Flexión De Bíceps Con Bandas Elásticas Desde Banco Inclinado",
                "Flexión De Bíceps Con Bandas Elásticas Desde Banco Declinado",
                "Flexión De Bíceps Cruzada Con Bandas Elásticas Desde Banco",
                "Flexión De Bíceps Con Bandas Elásticas Con Elevación De Cadera",
                "Flexión De Bíceps Con Bandas Elásticas Y Rotación De Torso",
                "Flexión De Bíceps Con Bandas Elásticas Desde Banco",
                "Flexión De Bíceps Con Bandas Elásticas Desde El Suelo Y Elevación De Talones",
                "Flexión De Bíceps Con Bandas Elásticas Cruzada Desde Banco Inclinado",
                "Flexión De Bíceps Con Bandas Elásticas Desde Banco Inclinado Con Elevación De Talones",
                "Flexión De Bíceps Con Bandas Elásticas Con Elevación De Talones",
                "Flexión De Bíceps Con Bandas Elásticas Desde Banco Declinado Con Elevación De Cadera",
                "Flexión De Bíceps Con Bandas Elásticas Desde Banco Inclinado Con Elevación De Cadera",
                "Flexión De Bíceps Con Bandas Elásticas Desde Banco Inclinado Con Giro De Torso",
                "Curl De Bíceps Con Mancuernas",
                "Curl De Bíceps Con Mancuernas Alternando Brazos",
                "Curl De Bíceps Con Mancuernas En Banco",
                "Curl De Bíceps Con Mancuernas Con Elevación De Talones",
                "Curl De Bíceps Con Mancuernas En Banco Inclinado",
                "Curl De Bíceps Con Mancuernas Con Elevación De Cadera",
                "Curl De Bíceps Cruzado Con Mancuernas",
                "Curl De Bíceps Con Mancuernas Y Rotación",
                "Curl De Bíceps Con Mancuernas Y Elevación De Cadera",
                "Curl De Bíceps Cruzado Con Mancuernas En Banco Inclinado",
                "Curl De Bíceps Con Mancuernas Con Elevación De Pie",
                "Curl De Bíceps Con Mancuernas Con Giro De Torso",
                "Curl De Bíceps Con Mancuernas Y Elevación De Cadera",
                "Curl De Bíceps Cruzado Con Mancuernas Y Elevación De Pie",
                "Curl De Bíceps Cruzado Con Mancuernas Desde Banco Declinado",
                "Curl De Bíceps Con Mancuernas Y Rotación De Torso",
                "Curl De Bíceps Con Mancuernas Desde Banco Inclinado Y Elevación De Cadera",
                "Curl De Bíceps Cruzado Con Mancuernas Desde Banco Declinado",
                "Curl De Bíceps Cruzado Con Mancuernas Desde Banco Inclinado",
                "Curl De Bíceps Cruzado Con Mancuernas Con Elevación De Pie",
                "Curl De Bíceps Cruzado Con Mancuernas Con Elevación De Cadera",
                "Curl De Bíceps Con Mancuernas Con Rotación De Torso",
                "Curl De Bíceps cruzado Con Mancuernas Con Elevación De Cadera",
                "Curl De Bíceps Cruzado Con Mancuernas Desde Banco Inclinado"));

        ejercicios.put("Espalda", Arrays.asList(
                "Flexiones Hindúes",
                "Flexiones Con Pica",
                "Flexiones Arqueras",
                "Flexiones Con Giro De Torso",
                "Flexiones En T",
                "Flexiones Con Toque De Hombro",
                "Flexiones Con Rotación",
                "Flexiones Con Codo Cruzado",
                "Flexiones Tipo Spiderman",
                "Flexiones Con Pica Y Desplazamiento Lateral",
                "Flexiones Estilo Cangrejo",
                "Puente De Glúteos",
                "Puente De Cadera Con Elevación De Pierna",
                "Elevación De Pelvis",
                "Plancha Con Giro De Torso",
                "Plancha Lateral Con Elevación De Brazo",
                "Plancha Con Elevación De Pierna",
                "Planchas Laterales",
                "Flexiones Declinadas",
                "Flexiones Inclinadas",
                "Escaladores De Montaña",
                "Pull-ups Dn Barra Casera",
                "Chin-ups En Barra Casera",
                "Flexiones De Tríceps",
                "Flexiones De Puente",
                "Plancha En Posición De Superman",
                "Flexiones Con Cuerpo Recto",
                "Flexiones Tipo Diamante",
                "Fondos De Tríceps En Silla",
                "Elevación De Cadera Con Una Pierna",
                "Flexiones Con Salto",
                "Flexiones Con Salto Y Giro",
                "Flexiones En Forma De Y",
                "Flexiones Con Pica Y Rotación",
                "Elevaciones De Tronco",
                "Flexiones Declinadas Con Pica",
                "Flexiones Con Desplazamiento Lateral",
                "Flexiones Con Rotación De Codo",
                "Flexiones Cruzadas",
                "Flexiones Escalonadas",
                "Flexiones De Pica Con Palma Hacia Abajo",
                "Flexiones Con Toque De Codo",
                "Elevación De Cadera En Banco",
                "Planchas Laterales Con Elevación De Pierna",
                "Flexiones En Puente Con Elevación De Pierna",
                "Flexiones En Puente Con Elevación De Pierna Alternada",
                "Flexiones Con Cuerpo Recto Y Giro",
                "Flexiones En Cruz",
                "Flexiones De Pica Con Desplazamiento",
                "Flexiones Con Peso En Espalda",
                "Remo Con Bandas Elásticas",
                "Remo Con Bandas Elásticas Alternando Brazos",
                "Remo Unilateral Con Bandas Elásticas",
                "Remo Con Bandas Elásticas Y Giro De Torso",
                "Remo Con Bandas Elásticas Con Elevación De Talones",
                "Remo Con Bandas Elásticas Y Elevación De Cadera",
                "Remo Con Bandas Elásticas Y Elevación De Brazo",
                "Pull-aparts Con Bandas Elásticas",
                "Pull-aparts Con Bandas Elásticas Con Giro De Torso",
                "Pull-aparts Con Bandas Elásticas En Banco",
                "Remo Con Bandas Elásticas En Banco",
                "Remo Con Bandas Elásticas Desde Banco Inclinado",
                "Remo Con Bandas Elásticas Desde Banco Declinado",
                "Remo Con Bandas Elásticas Cruzado",
                "Remo Con Bandas Elásticas Desde El Suelo",
                "Remo Con Bandas Elásticas Desde Banco Inclinado",
                "Remo Con Bandas Elásticas Con Elevación De Pie",
                "Remo Con Bandas Elásticas En Banco Con Elevación De Cadera",
                "Pull-aparts Con Bandas Elásticas Y Elevación De Pie",
                "Remo Con Bandas Elásticas Desde Banco Plano",
                "Remo Con Bandas Elásticas Y Elevación De Talones",
                "Remo Con Bandas Elásticas Con Giro De Torso Desde Banco",
                "Remo Con Bandas Elásticas Desde Banco Declinado Con Elevación De Cadera",
                "Remo Con Bandas Elásticas Desde Banco Inclinado Con Elevación De Cadera",
                "Pull-aparts Con Bandas Elásticas En Banco Con Elevación De Cadera",
                "Remo Con Mancuernas",
                "Remo Unilateral Con Mancuernas",
                "Remo Con Mancuernas Alternando Brazos",
                "Remo Con Mancuernas Con Elevación De Talones",
                "Remo Con Mancuernas En Banco",
                "Remo Con Mancuernas En Banco Plano",
                "Remo Con Mancuernas En Banco Inclinado",
                "Remo Con Mancuernas En Banco Declinado",
                "Remo Cruzado Con Mancuernas",
                "Remo Con Mancuernas Con Giro De Torso",
                "Remo Con Mancuernas Desde Banco Inclinado",
                "Remo Con Mancuernas En Banco Plano Con Elevación De Cadera",
                "Remo Cruzado Con Mancuernas En Banco Declinado",
                "Remo Cruzado Con Mancuernas Desde Banco Plano",
                "Remo Con Mancuernas Desde Banco Inclinado Y Elevación De Cadera",
                "Remo Cruzado Con Mancuernas Desde Banco Declinado",
                "Remo Con Mancuernas Con Elevación De Pie",
                "Remo Con Mancuernas Con Giro De Torso",
                "Remo Cruzado Con Mancuernas Con Elevación De Cadera",
                "Remo Con Mancuernas Con Elevación De Pie",
                "Remo Con Mancuernas En Banco Plano Con Giro De Torso",
                "Remo Con Mancuernas En Banco Inclinado Con Elevación De Cadera",
                "Remo Con Mancuernas En Banco Plano Con Elevación De Cadera",
                "Remo Cruzado Con Mancuernas En Banco Inclinado"));

        ejercicios.put("Abdominales", Arrays.asList(
                "Abdominales Tradicionales",
                "Abdominales Tipo Bicicleta",
                "Abdominales Con Piernas Elevadas",
                "Abdominales Oblicuos",
                "Abdominales En V",
                "Plancha Tradicional",
                "Plancha Lateral",
                "Plancha Lateral Con Elevación De Pierna",
                "Plancha Con Elevación De Brazo",
                "Plancha Con Toque De Hombro",
                "Plancha Con Elevación De Pierna",
                "Plancha Con Desplazamiento Lateral",
                "Plancha Con Elevación De Cadera",
                "Plancha Con Toque De Codo",
                "Abdominales Invertidos",
                "Abdominales Con Rodillas Al Pecho",
                "Abdominales Con Torsión De Cadera",
                "Abdominales Tipo Rana",
                "Abdominales De Doble Pierna",
                "Abdominales Con Toque De Tobillo",
                "Abdominales Tipo Puente",
                "Abdominales Con Toque De Codo",
                "Plancha Con Giro De Torso",
                "Plancha Con Giro De Cadera",
                "Plancha Con Elevación De Pie",
                "Plancha Con Desplazamiento Circular",
                "Escaladores De Montaña",
                "Abdominales Con Elevación De Pierna Y Giro De Torso",
                "Abdominales Con Toque De Pie",
                "Abdominales Con Elevación De Cadera",
                "Abdominales Con Toque De Talón",
                "Abdominales Laterales",
                "Abdominales Con Elevación De Pierna Y Toque De Codo",
                "Abdominales Con Giro De Torso",
                "Abdominales Con Elevación De Pie",
                "Abdominales Con Desplazamiento Lateral",
                "Abdominales Tipo Estrella",
                "Abdominales Con Desplazamiento Lateral Y Giro De Torso",
                "Abdominales Con Toque De Talón Y Elevación De Pierna",
                "Abdominales Con Elevación De Rodilla",
                "Abdominales Con Elevación De Cadera Y Giro De Torso",
                "Abdominales Con Elevación De Pierna Y Giro De Cadera",
                "Abdominales Con Elevación De Rodilla Y Toque De Codo",
                "Abdominales Tipo Puente Con Elevación De Cadera",
                "Plancha Con Rotación",
                "Plancha Con Toque De Codo Y Elevación De Pierna",
                "Abdominales Con Toque De Codo Y Elevación De Pierna",
                "Abdominales Con Elevación De Pie Y Toque De Codo",
                "Abdominales Con Elevación De Cadera Y Giro De Torso",
                "Abdominales Con Desplazamiento Lateral Y Giro De Torso",
                "Abdominales Con Bandas Elásticas",
                "Plancha Con Bandas Elásticas",
                "Plancha Lateral Con Bandas Elásticas",
                "Abdominales Con Bandas Elásticas Y Giro De Torso",
                "Abdominales Con Bandas Elásticas Y Elevación De Pie",
                "Abdominales Con Bandas Elásticas Y Elevación De Cadera",
                "Abdominales Con Bandas Elásticas Con Giro De Torso",
                "Plancha Con Bandas Elásticas Y Elevación De Cadera",
                "Plancha Con Bandas Elásticas Y Toque De Codo",
                "Abdominales Con Bandas Elásticas Y Elevación De Cadera",
                "Abdominales Con Bandas Elásticas Y Elevación De Pie",
                "Plancha Con Bandas Elásticas Y Giro De Torso",
                "Abdominales Con Bandas Elásticas Desde Banco",
                "Plancha Con Bandas Elásticas Desde Banco",
                "Plancha Lateral Con Bandas Elásticas Con Elevación De Pierna",
                "Abdominales Con Bandas Elásticas Y Elevación De Talones",
                "Abdominales Con Bandas Elásticas Desde Banco Inclinado",
                "Plancha Con Bandas Elásticas Y Elevación De Pie",
                "Plancha Con Bandas Elásticas Y Giro De Torso",
                "Abdominales Con Bandas Elásticas Desde Banco Declinado",
                "Abdominales Con Bandas Elásticas Con Elevación De Cadera",
                "Plancha Con Bandas Elásticas Y Elevación De Cadera",
                "Abdominales Con Bandas Elásticas Desde Banco Inclinado",
                "Abdominales Con Bandas Elásticas Con Elevación De Talones",
                "Abdominales Con Bandas Elásticas Desde Banco Plano",
                "Abdominales Con Mancuernas",
                "Abdominales Con Mancuernas Y Giro De Torso",
                "Abdominales Con Mancuernas Con Elevación De Pierna",
                "Plancha Con Mancuernas",
                "Plancha Lateral Con Mancuernas",
                "Plancha Con Mancuernas Y Elevación De Cadera",
                "Plancha Con Mancuernas Y Toque De Hombro",
                "Abdominales Laterales Con Mancuernas",
                "Abdominales Con Mancuernas Y Elevación De Pie",
                "Plancha Con Mancuernas Y Elevación De Cadera",
                "Abdominales Con Mancuernas Con Giro De Torso",
                "Plancha Lateral Con Mancuernas Y Elevación De Pierna",
                "Plancha Con Mancuernas Con Giro De Torso",
                "Plancha Con Mancuernas Y Elevación De Cadera",
                "Abdominales Laterales Con Mancuernas Y Elevación De Pierna",
                "Abdominales Con Mancuernas Desde Banco",
                "Abdominales Con Mancuernas Y Elevación De Cadera",
                "Abdominales Con Mancuernas Y Giro De Torso",
                "Abdominales Con Mancuernas Desde Banco Inclinado",
                "Abdominales Con Mancuernas Desde Banco Declinado",
                "Abdominales Con Mancuernas Con Elevación De Pie",
                "Abdominales Laterales Con Mancuernas En Banco Inclinado",
                "Abdominales Con Mancuernas Con Giro De Torso",
                "Plancha Con Mancuernas Desde Banco",
                "Abdominales Con Mancuernas Y Elevación De Pie Desde Banco Inclinado"));

        ejercicios.put("Pantorrilla", Arrays.asList(
                "Elevaciones De Talón",
                "Elevaciones De Talón Con Una Pierna",
                "Elevaciones De Talón En Escalón",
                "Elevaciones De Talón Con Pies Juntos",
                "Elevaciones De Talón Con Pies Separados",
                "Elevaciones De Talón Con Pies Hacia Afuera",
                "Elevaciones De Talón Con Pies Hacia Adentro",
                "Elevaciones De Talón Con Rebote",
                "Elevaciones De Talón Con Salto",
                "Elevaciones De Talón Con Toque De Cadera",
                "Elevaciones De Talón Con Elevación De Cadera",
                "Elevaciones De Talón Con Flexión De Rodilla",
                "Elevaciones De Talón En Banco",
                "Elevaciones De Talón Con Rotación",
                "Elevaciones De Talón Alternadas",
                "Elevaciones De Talón En Forma De Estrella",
                "Elevaciones De Talón En Cruz",
                " Elevaciones De Talón En Forma De T",
                "Elevaciones De Talón Con Una Pierna Y Rotación",
                "Elevaciones De Talón Con Una Pierna Y Salto",
                "Elevaciones De Talón Con Una Pierna En Escalón",
                "Elevaciones De Talón Con Una Pierna Y Elevación De Cadera",
                "Elevaciones De Talón En Banco Con Salto",
                "Elevaciones De Talón En Banco Con Toque De Cadera",
                "Elevaciones De Talón En Banco Con Elevación De Cadera",
                "Elevaciones De Talón En Banco Con Rebote",
                "Elevaciones De Talón Con Una Pierna Y Giro De Torso",
                "Elevaciones De Talón En Banco Con Rotación",
                "Elevaciones De Talón Con Una Pierna En Forma De Estrella",
                "Elevaciones De Talón En Escalón Con Toque De Cadera",
                "Elevaciones De Talón Con Rebote Y Salto",
                "Elevaciones De Talón Con Toque De Cadera Y Giro De Torso",
                "Elevaciones De Talón En Banco Con Toque De Cadera Y Salto",
                "Elevaciones De Talón Con Una Pierna En Escalón Y Rebote",
                "Elevaciones De Talón En Escalón Con Rebote Y Salto",
                "Elevaciones De Talón En Escalón Con Rotación",
                "Elevaciones De Talón Con Pies Juntos Y Salto",
                "Elevaciones De Talón En Escalón Con Una Pierna Y Giro De Torso",
                "Elevaciones De Talón Con Una Pierna Y Toque De Cadera",
                "Elevaciones De Talón Con Pies Hacia Afuera Y Rotación",
                "Elevaciones De Talón En Escalón Con Pies Separados",
                "Elevaciones De Talón En Banco Con Una Pierna Y Salto",
                "Elevaciones De Talón En Banco Con Una Pierna Y Rebote",
                "Elevaciones De Talón Con Pies Hacia Adentro Y Salto",
                "Elevaciones De Talón En Escalón Con Una Pierna Y Toque De Cadera",
                "Elevaciones De Talón En Banco Con Una Pierna Y Rotación",
                "Elevaciones De Talón En Escalón Con Pies Juntos Y Salto",
                "Elevaciones De Talón En Escalón Con Pies Hacia Adentro Y Rebote",
                "Elevaciones De Talón Con Flexión De Rodilla Y Toque De Cadera",
                "Elevaciones De Talón En Escalón Con Una Pierna Y Rotación",
                "Elevaciones De Talón Con Bandas Elásticas Y Rotación",
                "Elevaciones De Talón Con Bandas Elásticas Con Una Pierna",
                "Elevaciones De Talón Con Bandas Elásticas En Banco",
                "Elevaciones De Talón Con Bandas Elásticas En Banco Y Rebote",
                "Elevaciones De Talón Con Bandas Elásticas En Escalón",
                "Elevaciones De Talón Con Bandas Elásticas En Banco Con Salto",
                "Elevaciones De Talón Con Bandas Elásticas Con Pies Juntos",
                "Elevaciones De Talón Con Bandas Elásticas En Banco Y Rotación",
                "Elevaciones De Talón Con Bandas Elásticas Con Toque De Cadera",
                "Elevaciones De Talón Con Bandas Elásticas Con Flexión De Rodilla",
                "Elevaciones De Talón Con Bandas Elásticas En Escalón Con Rebote",
                "Elevaciones De Talón Con Bandas Elásticas En Banco Con Una Pierna",
                "Elevaciones De Talón Con Bandas Elásticas Con Una Pierna Y Salto",
                "Elevaciones De Talón Con Bandas Elásticas En Escalón Con Una Pierna",
                "Elevaciones De Talón Con Bandas Elásticas Con Pies Juntos Y Salto",
                "Elevaciones De Talón Con Bandas Elásticas Con Toque De Cadera Y Rotación",
                "Elevaciones De Talón Con Bandas Elásticas En Banco Con Toque De Cadera",
                "Elevaciones De Talón Con Bandas Elásticas En Escalón Con Rotación",
                "Elevaciones De Talón Con Bandas Elásticas En Escalón Y Rebote",
                "Elevaciones De Talón Con Bandas Elásticas En Banco Con Rotación",
                "Elevaciones De Talón Con Bandas Elásticas En Banco Con Flexión De Rodilla",
                "Elevaciones De Talón Con Bandas Elásticas En Banco Con Toque De Cadera",
                "Elevaciones De Talón Con Bandas Elásticas En Escalón Con Toque De Cadera",
                "Elevaciones De Talón Con Bandas Elásticas Con Flexión De Rodilla Y Toque De Cadera",
                "Elevaciones De Talón Con Mancuernas",
                "Elevaciones De Talón Con Mancuernas Y Rotación",
                "Elevaciones De Talón Con Mancuernas En Banco",
                "Elevaciones De Talón Con Mancuernas En Escalón",
                "Elevaciones De Talón Con Mancuernas Con Una Pierna",
                "Elevaciones De Talón Con Mancuernas Con Pies Juntos",
                "Elevaciones De Talón Con Mancuernas En Banco Con Rebote",
                "Elevaciones De Talón Con Mancuernas Y Flexión De Rodilla",
                "Elevaciones De Talón Con Mancuernas En Banco Con Una Pierna",
                "Elevaciones De Talón Con Mancuernas Con Toque De Cadera",
                "Elevaciones De Talón Con Mancuernas En Banco Con Salto",
                "Elevaciones De Talón Con Mancuernas Y Rebote",
                "Elevaciones De Talón Con Mancuernas En Banco Con Rotación",
                "Elevaciones De Talón Con Mancuernas En Banco Con Flexión De Rodilla",
                "Elevaciones De Talón Con Mancuernas En Escalón Con Rebote",
                "Elevaciones De Talón Con Mancuernas En Banco Con Una Pierna Y Rotación",
                "Elevaciones De Talón Con Mancuernas En Banco Con Salto",
                "Elevaciones De Talón Con Mancuernas En Escalón Con Toque De Cadera",
                "Elevaciones De Talón Con Mancuernas En Banco Con Flexión De Rodilla",
                "Elevaciones De Talón Con Mancuernas Con Una Pierna En Banco",
                "Elevaciones De Talón Con Mancuernas En Banco Con Rotación",
                "Elevaciones De Talón Con Mancuernas Con Pies Juntos Y Rebote",
                "Elevaciones De Talón Con Mancuernas En Banco Con Salto",
                "Elevaciones De Talón Con Mancuernas Con Flexión De Rodilla Y Rotación",
                "Elevaciones De Talón Con Mancuernas En Escalón Con Rotación"));

        ejercicios.put("Antebrazo", Arrays.asList(
                "Flexiones Con Manos Invertidas",
                "Flexiones Con Agarre Estrecho",
                "Flexiones De Diamante",
                "Flexiones Con Dedos",
                "Flexiones Con Pica",
                "Flexiones Con Toque De Hombro",
                "Flexiones Arqueras (Archer Push-Ups)",
                "Flexiones Con Rotación",
                "Flexiones Con Cuerpo Recto (Planche Push-Ups)",
                "Flexiones Escalonadas (Staggered Push-Ups)",
                "Flexiones Tipo Spiderman",
                "Flexiones De Pica Con Palma Hacia Arriba",
                "Flexiones De Pica Con Palma Hacia Abajo",
                "Flexiones Con Toque De Hombro Y Rotación",
                "Flexiones Con Dedos Y Desplazamiento Lateral",
                "Flexiones Con Peso En Espalda",
                "Flexiones Con Toque De Codo",
                "Flexiones De Diamante Con Salto",
                "Flexiones Con Toque De Codo Y Rotación",
                "Flexiones Con Dedos Y Salto",
                "Flexiones Con Cuerpo Recto Y Giro De Torso",
                "Flexiones Inclinadas Con Manos Invertidas",
                "Flexiones Declinadas Con Manos Invertidas",
                "Flexiones Con Toque De Hombro Y Elevación De Cadera",
                "Flexiones Con Dedos Y Toque De Codo",
                "Flexiones Con Agarre Estrecho Y Rotación",
                "Flexiones Con Desplazamiento Lateral",
                "Flexiones Con Toque De Codo Y Rotación De Torso",
                "Flexiones Con Dedos En Forma De T",
                "Flexiones Con Cuerpo Recto Con Elevación De Cadera",
                "Flexiones Con Dedos Y Salto Hacia Adelante",
                "Flexiones De Diamante Con Toque De Codo",
                "Flexiones Con Cuerpo Recto Y Salto",
                "Flexiones Con Dedos Y Rotación",
                "Flexiones Con Dedos Y Elevación De Cadera",
                "Flexiones Con Dedos Y Giro De Torso",
                "Flexiones Con Cuerpo Recto Y Toque De Codo",
                "Flexiones Con Cuerpo Recto Y Rotación De Torso",
                "Flexiones Con Dedos Y Elevación De Cadera",
                "Flexiones Con Dedos Y Toque De Hombro",
                "Flexiones Con Dedos Y Elevación De Pies",
                "Flexiones Con Dedos Y Desplazamiento Lateral",
                "Flexiones Con Dedos Y Rotación De Torso",
                "Flexiones Con Dedos Y Elevación De Cadera",
                "Flexiones De Diamante Con Dedos",
                "Flexiones Con Dedos Y Toque De Hombro",
                "Flexiones Con Dedos Y Rotación De Torso",
                "Flexiones Con Dedos Y Toque De Codo",
                "Flexiones Con Dedos Y Elevación De Cadera",
                "Flexiones Con Dedos Y Desplazamiento Lateral",
                "Curl De Muñeca Con Bandas Elásticas",
                "Flexión De Muñeca Con Bandas Elásticas",
                "Extensión De Muñeca Con Bandas Elásticas",
                "Flexión De Muñeca Con Bandas Elásticas Y Rotación",
                "Extensión De Muñeca Con Bandas Elásticas Y Giro De Torso",
                "Flexión De Muñeca Con Bandas Elásticas Con Rotación",
                "Curl De Muñeca Con Bandas Elásticas Y Giro De Codo",
                "Flexión De Muñeca Con Bandas Elásticas Y Elevación De Cadera",
                "Flexión De Muñeca Con Bandas El ásticas Desde Banco",
                "Extensión De Muñeca Con Bandas Elásticas Desde Banco",
                "Flexión De Muñeca Con Bandas Elásticas Y Elevación De Pie",
                "Extensión De Muñeca Con Bandas Elásticas Con Giro De Torso",
                "Flexión De Muñeca Con Bandas Elásticas Desde Banco Inclinado",
                "Extensión De Muñeca Con Bandas Elásticas Desde Banco Plano",
                "Flexión De Muñeca Con Bandas Elásticas Con Elevación De Cadera",
                "Flexión De Muñeca Con Bandas Elásticas Y Rotación De Torso",
                "Extensión De Muñeca Con Bandas Elásticas Y Rotación",
                "Flexión De Muñeca Con Bandas Elásticas Desde Banco Declinado",
                "Extensión De Muñeca Con Bandas Elásticas Desde Banco Inclinado",
                "Flexión De Muñeca Con Bandas Elásticas Desde Banco Plano",
                "Flexión De Muñeca Con Bandas Elásticas Y Giro De Codo",
                "Extensión De Muñeca Con Bandas Elásticas Y Elevación De Cadera",
                "Flexión De Muñeca Con Bandas Elásticas Desde Banco Inclinado Con Rotación",
                "Flexión De Muñeca Con Bandas Elásticas Desde Banco Inclinado Con Elevación De Cadera",
                "Extensión De Muñeca Con Bandas Elásticas Desde Banco Inclinado Y Elevación De Cadera",
                "Curl De Muñeca Con Mancuernas",
                "Flexión De Muñeca Con Mancuernas",
                "Extensión De Muñeca Con Mancuernas",
                "Curl De Muñeca Con Mancuernas En Banco",
                "Flexión De Muñeca Con Mancuernas En Banco",
                "Extensión De Muñeca Con Mancuernas En Banco Plano",
                "Flexión De Muñeca Con Mancuernas Y Rotación",
                "Extensión De Muñeca Con Mancuernas Con Rotación",
                "Flexión De Muñeca Con Mancuernas Y Giro De Torso",
                "Flexión De Muñeca Con Mancuernas Con Elevación De Cadera",
                "Extensión De Muñeca Con Mancuernas Desde Banco Inclinado",
                "Flexión De Muñeca Con Mancuernas Desde Banco Declinado",
                "Extensión De Muñeca Con Mancuernas Con Giro De Torso",
                "Curl De Muñeca Con Mancuernas Y Elevación De Cadera",
                "Flexión De Muñeca Con Mancuernas Desde Banco Inclinado Y Elevación De Cadera",
                "Flexión De Muñeca Con Mancuernas Y Elevación De Pie",
                "Flexión De Muñeca Con Mancuernas Con Giro De Torso",
                "Flexión De Muñeca Con Mancuernas En Banco Plano Con Rotación",
                "Extensión De Muñeca Con Mancuernas Desde Banco Inclinado Y Elevación De Cadera"));

        ejercicios.put("Flexibilidad", Arrays.asList(
                "Estiramiento De Cuádriceps",
                "Estiramiento De Isquiotibiales",
                "Estiramiento De Pantorrillas",
                "Estiramiento De La Parte Baja De La Espalda",
                "Estiramiento De Glúteos",
                "Estiramiento De Cadera",
                "Estiramiento De Flexores De Cadera",
                "Estiramiento De Los Músculos De La Ingle",
                "Estiramiento De Aductores",
                "Estiramiento De Abductores",
                "Estiramiento De Tríceps",
                "Estiramiento De Bíceps",
                "Estiramiento De Deltoides",
                "Estiramiento De Trapecio",
                "Estiramiento De Cuello",
                "Estiramiento De Antebrazos",
                "Estiramiento De Pecho",
                "Estiramiento De Hombros",
                "Estiramiento De La Parte Alta De La Espalda",
                "Estiramiento De Muñeca",
                "Estiramiento De Tobillos",
                "Estiramiento De Dedos",
                "Estiramiento De Planta Del Pie",
                "Estiramiento De Gemelos",
                "Estiramiento De Los Músculos Rotadores Del Hombro",
                "Estiramiento De Los Músculos Laterales Del Tronco",
                "Estiramiento De Los Músculos Oblicuos",
                "Estiramiento De Pectorales",
                "Estiramiento De Los Músculos Intercostales",
                "Estiramiento De Lumbares",
                "Postura Del Perro Mirando Hacia Abajo (Downward-Facing Dog)",
                "Postura Del Perro Mirando Hacia Arriba (Upward-Facing Dog)",
                "Postura Del Gato (Cat Pose)",
                "Postura De La Vaca (Cow Pose)",
                "Postura De La Cobra (Cobra Pose)",
                "Postura Del Niño (Child's Pose)",
                "Postura Del Guerrero I (Warrior I)",
                "Postura Del Guerrero II (Warrior II)",
                "Postura Del Guerrero III (Warrior III)",
                "Postura Del Árbol (Tree Pose)",
                "Postura De La Paloma (Pigeon Pose)",
                "Postura Del Triángulo (Triangle Pose)",
                "Postura Del Triángulo Invertido (Reverse Triangle Pose)",
                "Postura Del Águila (Eagle Pose)",
                "Postura De La Silla (Chair Pose)",
                "Postura Del Cuervo (Crow Pose)",
                "Postura De La Mariposa (Butterfly Pose)",
                "Postura Del Camello (Camel Pose)",
                "Postura Del Puente (Bridge Pose)",
                "Postura De La Rueda (Wheel Pose)"));

        ejercicios.put("Equilibrio", Arrays.asList(
                "Equilibrio A Una Pierna",
                "Equilibrio A Una Pierna Con Ojo Cerrado",
                "Equilibrio En Puntillas",
                "Equilibrio En Talones",
                "Estocadas Con Equilibrio",
                "Equilibrio Con Pierna Cruzada",
                "Equilibrio Con Movimiento De Brazos",
                "Equilibrio Con Elevación Lateral De Pierna",
                "Equilibrio Con Elevación Frontal De Pierna",
                "Flexión A Una Pierna",
                "Sentadillas A Una Pierna",
                "Equilibrio Con Elevación De Cadera",
                "Equilibrio Con Elevación De Rodilla",
                "Estocada Inversa Con Equilibrio",
                "Sentadilla De Pistola",
                "Salto Y Equilibrio A Una Pierna",
                "Saltos Laterales Con Equilibrio",
                "Equilibrio En Silla",
                "Planchas Laterales",
                "Equilibrio En T",
                "Plancha Con Elevación De Pierna",
                "Equilibrio Con Elevación De Brazos",
                "Equilibrio Sobre Una Superficie Inestable",
                "Equilibrio Con Extensión De Brazos Y Piernas",
                "Equilibrio En Posición De Yoga (Árbol)",
                "Estocada Con Banda Elástica",
                "Sentadilla A Una Pierna Con Pesas",
                "Equilibrio Con Banda Elástica",
                "Equilibrio Con Pesas En Una Pierna",
                "Elevación De Piernas Con Banda Elástica",
                "Estocada Inversa Con Pesas",
                "Sentadillas Con Pesas Y Elevación De Pierna",
                "Equilibrio Con Banda Elástica Y Elevación De Pierna",
                "Sentadilla De Pistola Con Pesas",
                "Equilibrio Sobre Una Pierna Con Bandas Elásticas",
                "Elevación De Pierna Con Mancuernas",
                "Estocadas Laterales Con Pesas",
                "Equilibrio En T Con Mancuernas",
                "Plancha Con Elevación De Pesas",
                "Equilibrio En Banco Con Pesas",
                "Elevación De Cadera Con Mancuernas",
                "Flexión A Una Pierna Con Pesas",
                "Elevación De Piernas En Plancha Con Pesas",
                "Elevación De Rodilla Con Pesas",
                "Plancha Lateral Con Bandas Elásticas",
                "Sentadillas Con Salto Y Pesas",
                "Equilibrio Con Bandas Y Elevación De Piernas",
                "Sentadilla De Pistola Con Bandas Elásticas",
                "Equilibrio Con Bandas Elásticas Y Rotación",
                "Plancha Con Elevación De Pesas Y Rotación"));

        ejercicios.put("Fortalecimiento", Arrays.asList(
                "Flexiones De Brazo (Push-Ups)",
                "Flexiones De Diamante",
                "Flexiones Arqueras (Archer Push-Ups)",
                "Flexiones Hindúes (Hindu Push-Ups)",
                "Flexiones Escalonadas (Staggered Push-Ups)",
                "Fondos De Tríceps En Silla",
                "Sentadillas (Squats)",
                "Sentadillas Con Salto",
                "Sentadillas De Sumo",
                "Sentadillas Con Elevación De Talón",
                "Estocadas (Lunges)",
                "Estocadas Con Salto",
                "Desplantes Laterales",
                "Sentadillas Búlgaras",
                "Sentadillas Con Una Pierna (Pistol Squats)",
                "Plancha Tradicional",
                "Plancha Lateral",
                "Plancha Con Elevación De Pierna",
                "Plancha Con Toque De Hombro",
                "Plancha Con Giro De Torso",
                "Puentes De Glúteos",
                "Puentes De Glúteos Con Elevación De Pierna",
                "Puentes De Glúteos Con Elevación De Cadera",
                "Abdominales Tradicionales (Crunches)",
                "Abdominales Tipo Bicicleta",
                "Abdominales En V",
                "Abdominales Laterales (Russian Twists)",
                "Abdominales Oblicuos",
                "Abdominales Invertidos",
                "Abdominales Tipo Rana",
                "Escaladores De Montaña (Mountain Climbers)",
                "Burpees",
                "Saltos De Tijera (Jumping Jacks)",
                "Tuck Jumps",
                "Saltos Laterales (Lateral Jumps)",
                "Equilibrio A Una Pierna",
                "Flexión A Una Pierna",
                "Elevación De Talones",
                "Elevación De Talones Con Una Pierna",
                "Sentadillas Con Desplazamiento Lateral",
                "Fondos De Tríceps Con Salto",
                "Flexiones Con Codo Cruzado",
                "Plancha Con Elevación De Cadera",
                "Flexiones Con Salto Y Giro",
                "Flexiones De Cuerpo Recto (Planche Push-Ups)",
                "Sentadilla Tipo Pistola",
                "Equilibrio En T",
                "Burpees Con Salto",
                "Planchas Con Elevación De Cadera",
                "Flexiones Con Rotación"));

        ejercicios.put("Fuerza", Arrays.asList(
                "Flexiones De Brazo (Push-Ups)",
                "Flexiones De Diamante",
                "Flexiones Inclinadas",
                "Flexiones Declinadas",
                "Flexiones Con Aplauso",
                "Fondos De Tríceps En Silla",
                "Sentadillas (Squats)",
                "Sentadillas Con Salto",
                "Sentadillas De Sumo",
                "Sentadillas Con Elevación De Talón",
                "Estocadas (Lunges)",
                "Desplantes Laterales",
                "Estocadas Con Salto",
                "Sentadillas Búlgaras",
                "Puentes De Glúteos",
                "Puentes De Glúteos Con Elevación De Pierna",
                "Plancha Tradicional",
                "Plancha Lateral",
                "Plancha Con Elevación De Pierna",
                "Abdominales Tipo Bicicleta",
                "Abdominales Tradicionales (Crunches)",
                "Abdominales Laterales (Russian Twists)",
                "Escaladores De Montaña (Mountain Climbers)",
                "Burpees",
                "Burpees Con Flexiones",
                "Sentadillas Con Bandas Elásticas",
                "Estocadas Con Bandas Elásticas",
                "Flexiones De Pecho Con Bandas Elásticas",
                "Prensa De Hombros Con Bandas Elásticas",
                "Remo Con Bandas Elásticas",
                "Prensa De Tríceps Con Bandas Elásticas",
                "Extensión De Tríceps Con Bandas Elásticas",
                "Curl De Bíceps Con Bandas Elásticas",
                "Elevaciones Laterales Con Bandas Elásticas",
                "Elevaciones Frontales Con Bandas Elásticas",
                "Prensa De Pecho Con Mancuernas",
                "Prensa De Hombros Con Mancuernas",
                "Sentadillas Con Mancuernas",
                "Desplantes Con Mancuernas",
                "Peso Muerto Con Mancuernas",
                "Curl De Bíceps Con Mancuernas",
                "Extensión De Tríceps Con Mancuernas",
                "Plancha Con Mancuernas",
                "Plancha Lateral Con Mancuernas",
                "Fondos Con Mancuernas",
                "Sentadillas Con Mochila Cargada",
                "Flexiones Con Mochila Cargada",
                "Estocadas Con Mochila Cargada",
                "Peso Muerto Con Mochila Cargada",
                "Prensa De Pecho Con Mochila Cargada"));

        ejercicios.put("Resistencia", Arrays.asList(
                "Saltos De Tijera (Jumping Jacks)",
                "Burpees",
                "Escaladores De Montaña (Mountain Climbers)",
                "Flexiones De Brazo (Push-Ups)",
                "Fondos De Tríceps En Silla",
                "Sentadillas (Squats)",
                "Sentadillas Con Salto",
                "Estocadas (Lunges)",
                "Desplantes Laterales",
                "Sentadillas De Pistola",
                "Puentes De Glúteos",
                "Plancha Tradicional",
                "Plancha Lateral",
                "Abdominales Tipo Bicicleta",
                "Abdominales Tradicionales (Crunches)",
                "Tuck Jumps",
                "Saltos Laterales (Lateral Jumps)",
                "Sentadillas Con Paso Lateral",
                "Plancha Con Toque De Hombro",
                "Flexiones Declinadas",
                "Flexiones Con Pica",
                "Flexiones Con Salto Y Palmada",
                "Flexiones Con Toque De Codo",
                "Flexiones En Plancha",
                "Flexiones Escalonadas",
                "Flexiones De Diamante",
                "Sentadillas De Sumo",
                "Burpees Con Salto",
                "Sentadillas Con Elevación De Talón",
                "Abdominales Laterales (Russian Twists)",
                "Planchas Con Elevación De Pierna",
                "Sentadillas Búlgaras",
                "Sentadillas Con Peso Muerto (Deadlift Squats)",
                "Plancha Con Giro De Torso",
                "Flexiones Con Salto Y Elevación De Rodillas",
                "Sentadillas Tipo Pistol Con Elevación De Pie",
                "Fondos De Tríceps Con Salto",
                "Flexiones En Pica Con Toque De Codo",
                "Flexiones De Cuerpo Recto (Planche Push-Ups)",
                "Burpees Con Salto Y Elevación De Rodillas",
                "Flexiones Con Toque De Hombro Y Codo",
                "Estocadas Con Salto",
                "Saltos Con Elevación De Pierna",
                "Sentadillas Con Salto Lateral",
                "Escaladores De Montaña Cruzados",
                "Escaladores De Montaña Con Giro",
                "Burpees Con Flexiones",
                "Flexiones De Puente",
                "Flexiones Con Codos Cerrados",
                "Sentadillas Con Elevación De Cadera"));

        return ejercicios;
    }

    @ModelAttribute("allTiposEjercicio")
    public List<String> tiposDeEjercicio() {
        return Arrays.asList(
                "Aerobico", "Anaerobicos", "Fuerza", "Resistencia",
                "Pierna", "Hombro", "Espalda", "Biceps",
                "Triceps", "Abdominales", "Antebrazo",
                "Pantorrilla", "Equilibrio", "Fortalecimiento",
                "Flexibilidad");
    }

    @ModelAttribute("allNombresEjercicio")
    public List<String> nombresDeEjercicio() {
        return Arrays.asList(
                "Flexiones De Brazo", "Flexiones Diamante", "Flexiones Declinadas",
                "Flexiones Inclinadas", "Flexiones Con Palma");
    }

    @GetMapping("/RegistroEjercicio")
    public String showExerciseForm(Model model) {
        model.addAttribute("exerciseLog", new ExerciseLogModel());
        return "Exercises/FormularioRegistroEjercicio";
    }

    @PostMapping("/RegistroEjercicio")
    public String registerExercise(@ModelAttribute("exerciseLog") ExerciseLogModel exerciseLog, Model model,
            HttpSession session) {
        Long userId = (Long) session.getAttribute("UsuarioId");
        if (userId != null) {
            UserModel user = userService.getUserById(userId);
            exerciseLog.setUser(user);
            exerciseLogService.saveExerciseLog(exerciseLog);
            model.addAttribute("message", "Registro exitoso");
            System.out.println("Fecha de inicio: " + exerciseLog.getStrartDate());
            System.out.println("Fecha final: " + exerciseLog.getFinalDate());
            return "redirect:/Api/Users/Exercises/TablaEjercicio";
        } else {
            model.addAttribute("error", "Usuario no encontrado.");
            return "redirect:/DSBConection";
        }
    }

    @GetMapping("/TablaEjercicio")
    public String TablaRegistroEjercicio(Model model, HttpSession session) {
        Long userId = (Long) session.getAttribute("UsuarioId");
        if (userId != null) {
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yy hh:mm a");
            List<ExerciseLogModel> exerciseLogs = exerciseLogService.getAllExerciseLogs()
                    .stream()
                    .filter(exerciseLog -> exerciseLog.getUser().getId().equals(userId))
                    .collect(Collectors.toList());
            // Formatear las fechas antes de añadirlas al modelo
            exerciseLogs.forEach(log -> {
                log.setFormattedStartDate(log.getStrartDate().format(formatter));
                log.setFormattedFinalDate(log.getFinalDate().format(formatter));
            });
            model.addAttribute("exerciseLogs", exerciseLogs);
            return "Exercises/TablaRegistroEjercicio";
        } else {
            model.addAttribute("error", "Usuario no encontrado.");
            return "redirect:/DSBConection";
        }
    }

    @GetMapping("/EditarEjercicio/{id}")
    public String showEditEjercicio(@PathVariable Long id, Model model) {
        // Obtener el ejercicio específico a editar
        ExerciseLogModel exerciseLog = exerciseLogService.getExerciseLogById(id);
        // Agregar atributos al modelo
        model.addAttribute("exerciseLog", exerciseLog);
        return "Exercises/FormularioEditarEjercicio";
    }

    @PostMapping("/EditarEjercicio")
    public String editarEjercicio(@ModelAttribute ExerciseLogModel exerciseLog) {
        exerciseLogService.UpdateExerciseLog(exerciseLog);
        return "redirect:/Api/Users/Exercises/TablaEjercicio"; // Redirige después de la edición
    }

    @GetMapping("/EliminarEjercicio/{id}")
    public String deleteExercise(@PathVariable Long id) {
        exerciseLogService.DeleteExerciseLog(id);
        return "redirect:/Api/Users/Exercises/TablaEjercicio";
    }

    @GetMapping("/Home")
    public String homeRegistroEjercicio() {
        return "/Exercises/HomeRegistroEjercicio";
    }

}
