package com.DevSalud.DSB.Controller;

import java.util.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.*;
import com.DevSalud.DSB.Model.*;
import com.DevSalud.DSB.Service.UserServices;
import jakarta.servlet.http.HttpSession;

@Controller
@RequestMapping("/Api/Users/Exercises")
public class PlanExerciseController {

    @Autowired
    private UserServices userService;

    @ModelAttribute("allNamePlanes")
    public Map<String, List<List<String>>> PlanesMap() {
        Map<String, List<List<String>>> planMap = new HashMap<>();

        // Planes para hipertensos con IMC bajo de peso
        planMap.put("HipertensosBajoDePeso", Arrays.asList(
                Arrays.asList("Lunes", "Aerobicos", "Saltos De Cuerda", "Moderada", "Hipertensos", "Bajo Peso"),
                Arrays.asList("Lunes", "Aerobicos", "Saltos De Tijera", "Moderada", "Hipertensos", "Bajo Peso"),
                Arrays.asList("Lunes", "Aeróbicos", "Caminata Rápida", "Baja", "Hipertensos", "Bajo Peso"),
                Arrays.asList("Lunes", "Aeróbicos", "bicicleta Estática", "Alta", "Hipertensos", "Bajo Peso"),
                Arrays.asList("Lunes", "Pierna", "Sentadillas Sin Peso O Con Una Silla", "Moderada", "Hipertensos",
                        "Bajo Peso"),
                Arrays.asList("Lunes", "Pierna", "Sentadillas Con Salto", "Baja", "Hipertensos", "Bajo Peso"),
                Arrays.asList("Lunes", "Pierna", "Elevaciones De Talones Con Elevación De Cadera", "Moderada",
                        "Hipertensos", "Bajo Peso"),
                Arrays.asList("Lunes", "Hombro", "Elevaciones Laterales Con Bandas Elásticas", "Moderada",
                        "Hipertensos", "Bajo Peso"),
                Arrays.asList("Lunes", "Hombro", "Elevaciones Frontales Con Bandas Elásticas Y Giro", "Alta",
                        "Hipertensos", "Bajo Peso"),
                Arrays.asList("Lunes", "Hombro", "Elevaciones Frontales Con Bandas Elásticas Con Giro De Pie", "Baja",
                        "Hipertensos", "Bajo Peso"),
                Arrays.asList("Martes", "Espalda", "Flexiones Inclinadas", "Baja", "Hipertensos", "Bajo Peso"),
                Arrays.asList("Martes", "Espalda", "Escaladores De Montaña", "Moderada", "Hipertensos", "Bajo Peso"),
                Arrays.asList("Martes", "Espalda", "Remo Con Bandas Elásticas", "Alta", "Hipertensos", "Bajo Peso"),
                Arrays.asList("Martes", "Triceps", "Fondos En Silla", "Moderada", "Hipertensos", "Bajo Peso"),
                Arrays.asList("Martes", "Triceps", "Fondos En El Suelo", "Baja", "Hipertensos", "Bajo Peso"),
                Arrays.asList("Martes", "Triceps", "Fondos De Tríceps Con Elevación De Pierna", "Moderada",
                        "Hipertensos", "Bajo Peso"),
                Arrays.asList("Martes", "Equilibrio", "Levantamiento de una pierna", "Alta", "Hipertensos",
                        "Bajo Peso"),
                Arrays.asList("Martes", "Equilibrio", "Equilibrio En T", "Alta", "Hipertensos", "Bajo Peso"),
                Arrays.asList("Martes", "Equilibrio", "Equilibrio En Talones", "Alta", "Hipertensos", "Bajo Peso"),
                Arrays.asList("Miercoles", "Pecho", "Flexiones De Brazo", "Baja", "Hipertensos", "Bajo Peso"),
                Arrays.asList("Miercoles", "Pecho", "Flexiones Con Brazos Abiertos", "Baja", "Hipertensos",
                        "Bajo Peso"),
                Arrays.asList("Miercoles", "Pecho", "Flexiones Inclinadas", "Alta", "Hipertensos", "Bajo Peso"),
                Arrays.asList("Miercoles", "Biceps", "Curl De Bíceps Con Bandas Elásticas", "Moderada", "Hipertensos",
                        "Bajo Peso"),
                Arrays.asList("Miercoles", "Biceps", "Curl De Bíceps Con Bandas Elásticas Alternado", "Moderada",
                        "Hipertensos", "Bajo Peso"),
                Arrays.asList("Miercoles", "Biceps", "Curl De Bí ceps Con Bandas Elásticas Cruzadas", "Moderada",
                        "Hipertensos", "Bajo Peso"),
                Arrays.asList("Miercoles", "Antebrazo", "Curl De Muñeca Con Bandas Elásticas", "Moderada",
                        "Hipertensos", "Bajo Peso"),
                Arrays.asList("Miercoles", "Antebrazo", "Extensión De Muñeca Con Bandas Elásticas", "Moderada",
                        "Hipertensos", "Bajo Peso"),
                Arrays.asList("Miercoles", "Antebrazo", "Extensión De Muñeca Con Bandas Elásticas Y Giro De Torso",
                        "Moderada", "Hipertensos", "Bajo Peso"),
                Arrays.asList("Jueves", "Abdominales", "Abdominales Tradicionales", "Moderada", "Hipertensos",
                        "Bajo Peso"),
                Arrays.asList("Jueves", "Abdominales", "Abdominales Tipo Bicicleta", "Moderada", "Hipertensos",
                        "Bajo Peso"),
                Arrays.asList("Jueves", "Abdominales", "Abdominales Con Piernas Elevadas", "Moderada", "Hipertensos",
                        "Bajo Peso"),
                Arrays.asList("Jueves", "Pantorrilla", "Elevaciones De Talón", "Moderada", "Hipertensos", "Bajo Peso"),
                Arrays.asList("Jueves", "Pantorrilla", "Elevaciones De Talón Con Una Pierna", "Baja", "Hipertensos",
                        "Bajo Peso"),
                Arrays.asList("Jueves", "Pantorrilla", "Elevaciones De Talón En Escalón", "Moderada", "Hipertensos",
                        "Bajo Peso"),
                Arrays.asList("Jueves", "Flexibilidad", "Estiramiento De Cuádriceps", "Alta", "Hipertensos",
                        "Bajo Peso"),
                Arrays.asList("Jueves", "Flexibilidad", "Estiramiento De Pantorrillas", "Alta", "Hipertensos",
                        "Bajo Peso"),
                Arrays.asList("Jueves", "Flexibilidad", "Estiramiento De Cadera", "Alta", "Hipertensos", "Bajo Peso"),
                Arrays.asList("Viernes", "Fuerza", "Flexiones De Brazo (Push-Ups)", "Baja", "Hipertensos", "Bajo Peso"),
                Arrays.asList("Viernes", "Fuerza", "Flexiones Inclinadas", "Baja", "Hipertensos", "Bajo Peso"),
                Arrays.asList("Viernes", "Fuerza", "Fondos De Tríceps En Silla", "Baja", "Hipertensos", "Bajo Peso"),
                Arrays.asList("Viernes", "Resistencia", "Saltos De Tijera", "Moderada", "Hipertensos", "Bajo Peso"),
                Arrays.asList("Viernes", "Resistencia", "Sentadillas Con Salto", "Baja", "Hipertensos", "Bajo Peso"),
                Arrays.asList("Viernes", "Resistencia", "Flexiones Declinadas", "Baja", "Hipertensos", "Bajo Peso"),
                Arrays.asList("Viernes", "Aerobico", "Rodillas Al Pecho", "Alta", "Hipertensos", "Bajo Peso"),
                Arrays.asList("Viernes", "Aerobico", "Skipping", "Alta", "Hipertensos", "Bajo Peso"),
                Arrays.asList("Viernes", "Aerobico", "Salto De Estrella", "Alta", "Hipertensos", "Bajo Peso"),
                Arrays.asList("Sabado", "Fortalecimiento", "Estocadas Con Salto", "Moderada", "Hipertensos",
                        "Bajo Peso"),
                Arrays.asList("Sabado", "Fortalecimiento", "Desplantes Laterales", "Moderada", "Hipertensos",
                        "Bajo Peso"),
                Arrays.asList("Sabado", "Fortalecimiento", "Abdominales Laterales", "Alta", "Hipertensos", "Bajo Peso"),
                Arrays.asList("Sabado", "Anaerobicos", "Elevaciones De Cadera", "Baja", "Hipertensos", "Bajo Peso"),
                Arrays.asList("Sabado", "Anaerobicos", "Abdominales En V", "Baja", "Hipertensos", "Bajo Peso"),
                Arrays.asList("Sabado", "Anaerobicos", "Escaladores Cruzados", "Baja", "Hipertensos", "Bajo Peso"),
                Arrays.asList("Sabado", "Aerobico", "Correr Con Elevación De Rodillas", "Alta", "Hipertensos",
                        "Bajo Peso"),
                Arrays.asList("Sabado", "Aerobico", "Saltos En Zig-Zag", "Moderada", "Hipertensos", "Bajo Peso"),
                Arrays.asList("Sabado", "Aerobico", "Saltos De Rana", "Alta", "Hipertensos", "Bajo Peso"),
                Arrays.asList("Domingo", "Flexibilidad", "Estiramiento De Flexores De Cadera", "Alta", "Hipertensos",
                        "Bajo Peso"),
                Arrays.asList("Domingo", "Flexibilidad", "Estiramiento De Antebrazos", "Alta", "Hipertensos",
                        "Bajo Peso"),
                Arrays.asList("Domingo", "Flexibilidad", "Estiramiento De Abductores", "Alta", "Hipertensos",
                        "Bajo Peso"),
                Arrays.asList("Domingo", "Flexibilidad", "Estiramiento De Hombros", "Alta", "Hipertensos", "Bajo Peso"),
                Arrays.asList("Domingo", "Flexibilidad", "Estiramiento De Isquiotibiales", "Alta", "Hipertensos",
                        "Bajo Peso")));

        // Planes para hipertensos con IMC sobrepeso
        planMap.put("hipertensosSobrePeso", Arrays.asList(
                Arrays.asList("Lunes", "Aerobicos", "Trote Moderado", "Moderada", "Hipertensos", "Sobre Peso"),
                Arrays.asList("Lunes", "Aerobicos", "Saltos Laterales", "Alta", "Hipertensos", "Sobre Peso"),
                Arrays.asList("Lunes", "Aerobicos", "Abdominales Tipo Bicicleta", "Moderada", "Hipertensos",
                        "Sobre Peso"),
                Arrays.asList("Lunes", "Pierna", "sentadillas", "Moderada", "Hipertensos", "SobrePeso"),
                Arrays.asList("Lunes", "Pierna", "Sentadillas De Sumo", "Moderada", "Hipertensos", "Sobre Peso"),
                Arrays.asList("Lunes", "Pierna", "Sentadillas Con Elevación De Brazos", "Moderada", "Hipertensos",
                        "Sobre Peso"),
                Arrays.asList("Lunes", "Hombro", "Elevaciones Laterales Con Bandas Elásticas Cruzadas", "Moderada",
                        "Hipertensos", "Sobre Peso"),
                Arrays.asList("Lunes", "Hombro", "Elevaciones Laterales Con Bandas Elásticas Y Elevación De Brazo",
                        "Moderada", "Hipertensos", "Sobre Peso"),
                Arrays.asList("Martes", "Espalda", "remo con bandas elásticas", "Alta", "Hipertensos", "Sobre Peso"),
                Arrays.asList("Martes", "Espalda", "Pull-ups De Barra Casera", "Moderada", "Hipertensos", "Sobre Peso"),
                Arrays.asList("Martes", "Espalda", "Remo Con Bandas Elásticas Alternando Brazos", "Alta", "Hipertensos",
                        "Sobre Peso"),
                Arrays.asList("Martes", "Triceps", "Fondos Con Elevación De Talones", "Baja", "Hipertensos",
                        "Sobre Peso"),
                Arrays.asList("Martes", "Triceps", "Fondos Con Rotación De Torso", "Baja", "Hipertensos", "Sobre Peso"),
                Arrays.asList("Martes", "Triceps", "Extensión De Tríceps Con Bandas Elásticas Desde Banco", "Baja",
                        "Hipertensos", "Sobre Peso"),
                Arrays.asList("Martes", "Equilibrio", "Flexiones Con Elevación De Pierna", "Alta", "Hipertensos",
                        "Sobre Peso"),
                Arrays.asList("Martes", "Equilibrio", "Equilibrio En T", "Alta", "Hipertensos", "Sobre Peso"),
                Arrays.asList("Martes", "Equilibrio", "Equilibrio En Talones", "Alta", "Hipertensos", "Sobre Peso"),
                Arrays.asList("Miercoles", "Pecho", "Flexiones Con Bandas Elásticas Y Elevación De Piernas", "Moderada",
                        "Hipertensos", "Sobre Peso"),
                Arrays.asList("Miercoles", "Pecho", "Aperturas De Pecho Con Bandas Elásticas Y Elevación De Piernas",
                        "Moderada", "Hipertensos", "Sobre Peso"),
                Arrays.asList("Miercoles", "Pecho", "Flexiones De Brazo", "Moderada", "Hipertensos", "Sobre Peso"),
                Arrays.asList("Miercoles", "Biceps", "Flexiones Con Agarre Estrecho", "Moderada", "Hipertensos",
                        "Sobre Peso"),
                Arrays.asList("Miercoles", "Biceps",
                        "Flexión De Bíceps Con Bandas Elásticas Cruzada Desde Banco Inclinado", "Moderada",
                        "Hipertensos", "Sobre Peso"),
                Arrays.asList("Miercoles", "Antebrazo", "Flexión De Muñeca Con Bandas Elásticas", "Moderada",
                        "Hipertensos", "Sobre Peso"),
                Arrays.asList("Miercoles", "Antebrazo", "Extensión De Muñeca Con Bandas Elásticas Y Giro De Torso",
                        "Moderada", "Hipertensos", "Sobre Peso"),
                Arrays.asList("Jueves", "Abdominales", "Abdominales Tradicionales", "Moderada", "Hipertensos",
                        "Sobre Peso"),
                Arrays.asList("Jueves", "Abdominales", "Abdominales Tipo Bicicleta", "Moderada", "Hipertensos",
                        "Sobre Peso"),
                Arrays.asList("Jueves", "Pantorrilla", "Elevaciones De Talón", "Moderada", "Hipertensos", "SobrePeso"),
                Arrays.asList("Jueves", "Pantorrilla", "Elevaciones De Talón Con Una Pierna", "Baja", "Hipertensos",
                        "Sobre Peso"),
                Arrays.asList("Jueves", "Pantorrilla", "Elevaciones De Talón En Escalón", "Moderada", "Hipertensos",
                        "Sobre Peso"),
                Arrays.asList("Jueves", "Flexibilidad", "Estiramiento De Cuádriceps", "Alta", "Hipertensos",
                        "Sobre Peso"),
                Arrays.asList("Jueves", "Flexibilidad", "Estiramiento De Pantorrillas", "Alta", "Hipertensos",
                        "Sobre Peso"),
                Arrays.asList("Jueves", "Flexibilidad", "Estiramiento De Cadera", "Alta", "Hipertensos", "Sobre Peso"),
                Arrays.asList("Viernes", "Fuerza", "Flexiones De Brazo (Push-Ups)", "Baja", "Hipertensos", "Sobre Peso"),
                Arrays.asList("Viernes", "Fuerza", "Flexiones Inclinadas", "Baja", "Hipertensos", "SobrePeso"),
                Arrays.asList("Viernes", "Fuerza", "Fondos De Tríceps En Silla", "Baja", "Hipertensos", "Sobre Peso"),
                Arrays.asList("Viernes", "Resistencia", "Saltos De Tijera", "Moderada", "Hipertensos", "Sobre Peso"),
                Arrays.asList("Viernes", "Resistencia", "Sentadillas Con Salto", "Baja", "Hipertensos", "Sobre Peso"),
                Arrays.asList("Viernes", "Resistencia", "Flexiones Declinadas", "Baja", "Hipertensos", "Sobre Peso"),
                Arrays.asList("Viernes", "Aerobico", "Rodillas Al Pecho", "Alta", "Hipertensos", "Sobre Peso"),
                Arrays.asList("Viernes", "Aerobico", "Skipping", "Alta", "Hipertensos", "SobrePeso"),
                Arrays.asList("Viernes", "Aerobico", "Salto De Estrella", "Alta", "Hipertensos", "Sobre Peso"),
                Arrays.asList("Sabado", "Fortalecimiento", "Estocadas Con Salto", "Moderada", "Hipertensos",
                        "Sobre Peso"),
                Arrays.asList("Sabado", "Fortalecimiento", "Desplantes Laterales", "Moderada", "Hipertensos",
                        "Sobre Peso"),
                Arrays.asList("Sabado", "Fortalecimiento", "Abdominales Laterales", "Alta", "Hipertensos", "Sobre Peso"),
                Arrays.asList("Sabado", "Anaerobicos", "Elevaciones De Cadera", "Baja", "Hipertensos", "Sobre Peso"),
                Arrays.asList("Sabado", "Anaerobicos", "Abdominales En V", "Baja", "Hipertensos", "Sobre Peso"),
                Arrays.asList("Sabado", "Anaerobicos", "Escaladores Cruzados", "Baja", "Hipertensos", "Sobre Peso"),
                Arrays.asList("Sabado", "Aerobico", "Correr Con Elevación De Rodillas", "Alta", "Hipertensos",
                        "Sobre Peso"),
                Arrays.asList("Sabado", "Aerobico", "Saltos En Zig-Zag", "Moderada", "Hipertensos", "Sobre Peso"),
                Arrays.asList("Sabado", "Aerobico", "Saltos De Rana", "Alta", "Hipertensos", "Sobre Peso"),
                Arrays.asList("Domingo", "Flexibilidad", "Estiramiento De Flexores De Cadera", "Alta", "Hipertensos",
                        "Sobre Peso"),
                Arrays.asList("Domingo", "Flexibilidad", "Estiramiento De Antebrazos", "Alta", "Hipertensos",
                        "Sobre Peso"),
                Arrays.asList("Domingo", "Flexibilidad", "Estiramiento De Abductores", "Alta", "Hipertensos",
                        "Sobre Peso"),
                Arrays.asList("Domingo", "Flexibilidad", "Estiramiento De Hombros", "Alta", "Hipertensos", "Sobre Peso"),
                Arrays.asList("Domingo", "Flexibilidad", "Estiramiento De Isquiotibiales", "Alta", "Hipertensos",
                        "Sobre Peso")));

        // Planes para diabetes tipo 1 con IMC bajo de peso
        planMap.put("diabetesTipo1BajoPeso", Arrays.asList(
                Arrays.asList("Lunes", "Aerobicos", "Saltos En Cuclillas", "Alta", "Diabetico Tipo I", "Bajo Peso"),
                Arrays.asList("Lunes", "Aerobicos", "Saltos Con Patada Trasera", "Alta", "Diabetico Tipo I",
                        "Bajo Peso"),
                Arrays.asList("Lunes", "Aerobicos", "Sentadilla Con Salto Y Elevacion", "Moderada", "Diabetico Tipo I",
                        "Bajo Peso"),
                Arrays.asList("Lunes", "Pierna", "Sentadillas Con Mancuernas Y Salto", "Baja", "Diabetico Tipo I",
                        "Bajo Peso"),
                Arrays.asList("Lunes", "Pierna", "Puentes De Glúteos Con Mancuernas", "Baja", "Diabetico Tipo I",
                        "Bajo Peso"),
                Arrays.asList("Lunes", "Pierna", "Elevaciones De Cadera Con Mancuernas", "Baja", "Diabetico Tipo I",
                        "Bajo Peso"),
                Arrays.asList("Lunes", "Hombro", "Elevaciones Laterales", "Moderada", "diabetico tipo 1", "Bajo Peso"),
                Arrays.asList("Lunes", "Hombro", "Press De Hombros Con Mancuernas", "Moderada", "diabetico tipo 1",
                        "Bajo Peso"),
                Arrays.asList("Lunes", "Hombro", "Prensa De Hombro Con Bandas Elásticas Y Salto", "Moderada",
                        "diabetico tipo 1", "Bajo Peso"),
                Arrays.asList("Martes", "Espalda", "Planchas Laterales Con Elevación De Pierna", "Baja",
                        "diabetico tipo 1", "Bajo Peso"),
                Arrays.asList("Martes", "Espalda", "Remo Con Bandas Elásticas Y Elevación De Cadera", "Moderada",
                        "diabetico tipo 1", "Bajo Peso"),
                Arrays.asList("Martes", "Espalda", "Pull-aparts Con Bandas Elásticas En Banco", "Moderada",
                        "diabetico tipo 1", "Bajo Peso"),
                Arrays.asList("Martes", "Triceps", "Flexiones Con Peso En Espalda", "Baja", "diabetico tipo 1",
                        "Bajo Peso"),
                Arrays.asList("Martes", "Triceps", "Fondos Con Rotación", "Baja", "diabetico tipo 1", "Bajo Peso"),
                Arrays.asList("Martes", "Triceps", "Extensión De Tríceps En Posición De Flexión", "Baja",
                        "diabetico tipo 1", "Bajo Peso"),
                Arrays.asList("Martes", "Anaerobicos", "Remo Unilateral Con Mancuernas", "Baja", "diabetico tipo 1",
                        "Bajo Peso"),
                Arrays.asList("Martes", "Anaerobicos", "Flexiones De Bíceps Alternadas Con Mancuernas", "Moderada",
                        "diabetico tipo 1", "Bajo Peso"),
                Arrays.asList("Martes", "Anaerobicos", "Abdominales Tipo Bicicleta Con Bandas Elásticas", "Baja",
                        "diabetico tipo 1", "Bajo Peso"),
                Arrays.asList("Miercoles", "Pecho", "Aperturas De Pecho Con Mancuernas", "Baja", "diabetico tipo 1",
                        "Bajo Peso"),
                Arrays.asList("Miercoles", "Pecho", "Flexiones De Pecho Con Bandas Elásticas", "Baja",
                        "diabetico tipo 1", "Bajo Peso"),
                Arrays.asList("Miercoles", "Pecho", "Prensa De Pecho En Banco Inclinado Con Mancuernas", "Baja",
                        "diabetico tipo 1", "Bajo Peso"),
                Arrays.asList("Miercoles", "Biceps", "Extensión De Tríceps Sobre La Cabeza Con Bandas Elásticas",
                        "Moderada", "diabetico tipo 1", "Bajo Peso"),
                Arrays.asList("Miercoles", "Biceps", "Extensión De Tríceps Con Bandas Elásticas Y Giro De Torso",
                        "Baja", "diabetico tipo 1", "Bajo Peso"),
                Arrays.asList("Miercoles", "Biceps", "Extensión De Tríceps Con Mancuernas", "Baja", "diabetico tipo 1",
                        "BajoDePeso"),
                Arrays.asList("Miercoles", "Antebrazo", "Curl De Muñeca Con Mancuernas", "Baja", "diabetico tipo 1",
                        "Bajo Peso"),
                Arrays.asList("Miercoles", "Antebrazo",
                        "Flexión De Muñeca Con Bandas Elásticas Con Elevación De Cadera", "Moderada",
                        "diabetico tipo 1", "Bajo Peso"),
                Arrays.asList("Miercoles", "Antebrazo", "Flexiones Con Toque De Codo", "Moderada", "diabetico tipo 1",
                        "Bajo Peso"),
                Arrays.asList("Jueves", "Abdominales", "Abdominales Tipo Puente", "Baja", "diabetico tipo 1",
                        "Bajo Peso"),
                Arrays.asList("Jueves", "Abdominales", "Escaladores De Montaña", "Moderada", "diabetico tipo 1",
                        "BajoDePeso"),
                Arrays.asList("Jueves", "Abdominales", "Abdominales Laterales", "Moderada", "diabetico tipo 1",
                        "Bajo Peso"),
                Arrays.asList("Jueves", "Pantorrilla", "Elevaciones De Talón En Banco Con Toque De Cadera Y Salto",
                        "Alta", "diabetico tipo 1", "Bajo Peso"),
                Arrays.asList("Jueves", "Pantorrilla", "Elevaciones De Talón En Banco Con Una Pierna Y Rebote", "Alta",
                        "diabetico tipo 1", "Bajo Peso"),
                Arrays.asList("Jueves", "Flexibilidad", "Postura Del Árbol", "Alta", "diabetico tipo 1", "Bajo Peso"),
                Arrays.asList("Jueves", "Flexibilidad", "Estiramiento De Cuádriceps", "Alta", "diabetico tipo 1",
                        "Bajo Peso"),
                Arrays.asList("Jueves", "Equilibrio", "Equilibrio En T", "Alta", "diabetico tipo 1", "Bajo Peso"),
                Arrays.asList("Jueves", "Equilibrio", "Equilibrio Con Extensión De Brazos Y Piernas", "Alta",
                        "diabetico tipo 1", "Bajo Peso"),
                Arrays.asList("Viernes", "Fuerza", "Estocadas Con Salto", "Baja", "diabetico tipo 1", "Bajo Peso"),
                Arrays.asList("Viernes", "Fuerza", "Estocadas Con Mochila Cargada", "Baja", "diabetico tipo 1",
                        "Bajo Peso"),
                Arrays.asList("Viernes", "Resistencia", "Flexiones Declinadas", "Baja", "diabetico tipo 1",
                        "Bajo Peso"),
                Arrays.asList("Viernes", "Resistencia", "Escaladores De Montaña Con Giro", "Baja", "diabetico tipo 1",
                        "Bajo Peso"),
                Arrays.asList("Viernes", "Fortalecimiento", "Saltos Laterales", "Moderada", "diabetico tipo 1",
                        "Bajo Peso"),
                Arrays.asList("Viernes", "Fortalecimiento", "Plancha Con Elevación De Pierna", "Moderada",
                        "diabetico tipo 1", "Bajo Peso"),
                Arrays.asList("Viernes", "Fortalecimiento", "Plancha Con Elevación De Cadera", "Moderada",
                        "diabetico tipo 1", "Bajo Peso"),
                Arrays.asList("Viernes", "Anaerobicos", "Abdominales Laterales Con Bandas Elásticas", "Alta",
                        "diabetico tipo 1", "Bajo Peso"),
                Arrays.asList("Viernes", "Anaerobicos", "Abdominales Tipo Bicicleta Con Bandas Elásticas", "Alta",
                        "diabetico tipo 1", "Bajo Peso"),
                Arrays.asList("Sabado", "Equilibrio", "Equilibrio A Una Pierna", "Alta", "diabetico tipo 1",
                        "Bajo Peso"),
                Arrays.asList("Sabado", "Equilibrio", "Equilibrio Con Pierna Cruzada", "Alta", "diabetico tipo 1",
                        "Bajo Peso"),
                Arrays.asList("Sabado", "Flexibilidad", "Estiramiento De Hombros", "Alta", "diabetico tipo 1",
                        "Bajo Peso"),
                Arrays.asList("Sabado", "Flexibilidad", "Estiramiento De Antebrazos", "Alta", "diabetico tipo 1",
                        "Bajo Peso"),
                Arrays.asList("Domingo", "Flexibilidad", "Postura Del Perro Mirando Hacia Abajo", "Alta",
                        "diabetico tipo 1", "Bajo Peso"),
                Arrays.asList("Domingo", "Flexibilidad", "Postura Del Niño", "Alta", "diabetico tipo 1", "Bajo Peso"),
                Arrays.asList("Domingo", "Equilibrio", "Equilibrio Con Bandas Y Elevación De Piernas", "Alta",
                        "diabetico tipo 1", "Bajo Peso"),
                Arrays.asList("Domingo", "Equilibrio", "Salto Y Equilibrio A Una Pierna", "Alta", "diabetico tipo 1",
                        "Bajo Peso"),
                Arrays.asList("Domingo", "Equilibrio", "Equilibrio Con Banda Elástica", "Alta", "diabetico tipo 1",
                        "Bajo Peso")));

        // Planes para diabetes tipo 1 con IMC sobrepeso
        planMap.put("diabetesTipo1SobrePeso", Arrays.asList(
                Arrays.asList("Lunes", "Pierna", "Sentadillas Con Peso Corporal", "Moderada", "diabetico tipo 1",
                        "SobrePeso"),
                Arrays.asList("Lunes", "Pierna", "Estocadas", "Alta", "diabetico tipo 1", "SobrePeso"),
                Arrays.asList("Lunes", "Pierna", "Peso Muerto Con Piernas Rectas", "Baja", "diabetico tipo 1",
                        "SobrePeso"),
                Arrays.asList("Lunes", "Hombro", "Prensa De Hombro Con Bandas Elásticas Con Elevación De Pie", "Baja",
                        "diabetico tipo 1", "SobrePeso"),
                Arrays.asList("Lunes", "Hombro", "Prensa De Hombro Con Bandas Elásticas Y Elevación De Pie", "Baja",
                        "diabetico tipo 1", "SobrePeso"),
                Arrays.asList("Lunes", "Aerobico", "Jumping Jacks En Rotación", "Moderada", "diabetico tipo 1",
                        "SobrePeso"),
                Arrays.asList("Lunes", "Aerobico", "Lunge Con Salto Y Toque De Suelo", "Moderada", "diabetico tipo 1",
                        "SobrePeso"),
                Arrays.asList("Lunes", "Aerobico", "Planchas Con Salto Y Patadas Laterales", "Moderada",
                        "diabetico tipo 1", "SobrePeso"),
                Arrays.asList("Martes", "Espalda", "Remo Con Mancuernas", "Moderada", "diabetico tipo 1", "SobrePeso"),
                Arrays.asList("Martes", "Espalda", "Pull-downs con banda de resistencia", "Moderada",
                        "diabetico tipo 1", "SobrePeso"),
                Arrays.asList("Martes", "Espalda", "Chin-ups En Barra Casera", "Moderada", "diabetico tipo 1",
                        "SobrePeso"),
                Arrays.asList("Martes", "Triceps", "Fondos en banco", "Alta", "diabetico tipo 1", "SobrePeso"),
                Arrays.asList("Martes", "Triceps", "Extensiones de tríceps", "Moderada", "diabetico tipo 1",
                        "SobrePeso"),
                Arrays.asList("Martes", "Triceps", "Extensión De Tríceps En Banco Inclinado", "Baja",
                        "diabetico tipo 1", "SobrePeso"),
                Arrays.asList("Martes", "Anaerobicos", "Planchas Con Bandas Elásticas", "Moderada", "diabetico tipo 1",
                        "SobrePeso"),
                Arrays.asList("Martes", "Anaerobicos", "Elevaciones De Talón Con Mancuernas En Banco", "Moderada",
                        "diabetico tipo 1", "SobrePeso"),
                Arrays.asList("Miercoles", "Pecho", "Flexiones De Pecho", "Moderada", "diabetico tipo 1", "SobrePeso"),
                Arrays.asList("Miercoles", "Pecho", "Press De Pecho Con Mancuernas", "Moderada", "diabetico tipo 1",
                        "SobrePeso"),
                Arrays.asList("Miercoles", "Pecho", "Flexiones Con Brazos Abiertos", "Moderada", "diabetico tipo 1",
                        "SobrePeso"),
                Arrays.asList("Miercoles", "Biceps", "Curl De bíceps Con Mancuernas", "Baja", "diabetico tipo 1",
                        "SobrePeso"),
                Arrays.asList("Miercoles", "Biceps", "Curl De Martillo", "Baja", "diabetico tipo 1", "SobrePeso"),
                Arrays.asList("Miercoles", "Biceps", "Curl De Bíceps Con Bandas Elásticas Cruzadas", "Baja",
                        "diabetico tipo 1", "SobrePeso"),
                Arrays.asList("Miercoles", "Antebrazo", "Flexiones De Muñeca", "Alta", "diabetico tipo 1", "SobrePeso"),
                Arrays.asList("Miercoles", "Antebrazo", "Extensiones De Muñeca", "Alta", "diabetico tipo 1",
                        "SobrePeso"),
                Arrays.asList("Jueves", "Abdominales", "Crunches", "Moderada", "diabetico tipo 1", "SobrePeso"),
                Arrays.asList("Jueves", "Abdominales", "Abdominales Tipo Bicicleta", "Moderada", "diabetico tipo 1",
                        "SobrePeso"),
                Arrays.asList("Jueves", "Abdominales", "Plancha", "Moderada", "diabetico tipo 1", "SobrePeso"),
                Arrays.asList("Jueves", "Pantorrilla", "Elevaciones De Talón", "Alta", "diabetico tipo 1", "SobrePeso"),
                Arrays.asList("Jueves", "Pantorrilla", "Elevaciones De Talón En Banco Con Salto", "Alta",
                        "diabetico tipo 1", "SobrePeso"),
                Arrays.asList("Jueves", "Abdominales", "Flexiones De Puente", "Resistencia", "diabetico tipo 1",
                        "SobrePeso"),
                Arrays.asList("Jueves", "Abdominales", "Flexiones Con Codos Cerrados", "Resistencia",
                        "diabetico tipo 1", "SobrePeso"),
                Arrays.asList("Jueves", "Flexibilidad", "Estiramientos De Cuerpo Completo", "Alta", "diabetico tipo 1",
                        "SobrePeso"),
                Arrays.asList("Viernes", "Pierna", "Sentadillas De Sumo", "Baja", "diabetico tipo 1", "SobrePeso"),
                Arrays.asList("Viernes", "Fuerza", "Flexiones De Pecho Con Bandas Elásticas", "Baja",
                        "diabetico tipo 1", "SobrePeso"),
                Arrays.asList("Viernes", "Fuerza", "Prensa De Hombros Con Bandas Elásticas", "Baja", "diabetico tipo 1",
                        "SobrePeso"),
                Arrays.asList("Viernes", "Fortalecimiento", "Plancha", "Moderada", "diabetico tipo 1", "SobrePeso"),
                Arrays.asList("Viernes", "Fortalecimiento", "Bird-Dog", "Moderada", "diabetico tipo 1", "SobrePeso"),
                Arrays.asList("Viernes", "Anaerobicos", "Estocadas Con Salto", "Baja", "diabetico tipo 1", "SobrePeso"),
                Arrays.asList("Viernes", "Anaerobicos", "Patadas Frontales", "Baja", "diabetico tipo 1", "SobrePeso"),
                Arrays.asList("Viernes", "Anaerobicos", "Elevaciones Laterales Con Bandas Elásticas", "Baja",
                        "diabetico tipo 1", "SobrePeso"),
                Arrays.asList("Sabado", "Equilibrio", "Postura Del Arbol", "Alta", "diabetico tipo 1", "SobrePeso"),
                Arrays.asList("Sabado", "Equilibrio", "Elevación De Una Pierna", "Alta", "diabetico tipo 1",
                        "SobrePeso"),
                Arrays.asList("Sabado", "Flexibilidad", "Estiramientos De Espalda", "Alta", "diabetico tipo 1",
                        "SobrePeso"),
                Arrays.asList("Sabado", "Flexibilidad", "Estiramientos De Hombros Y Cuello", "Alta", "diabetico tipo 1",
                        "SobrePeso"),
                Arrays.asList("Domingo", "Flexibilidad", "Estiramientos De Cuádriceps", "Alta", "diabetico tipo 1",
                        "SobrePeso"),
                Arrays.asList("Domingo", "Flexibilidad", "Estiramientos De Isquiotibiales", "Alta", "diabetico tipo 1",
                        "SobrePeso"),
                Arrays.asList("Domingo", "Flexibilidad", "Estiramientos De Pantorrillas", "Alta", "diabetico tipo 1",
                        "SobrePeso"),
                Arrays.asList("Domingo", "Flexibilidad", "Sesión de yoga suave", "Alta", "diabetico tipo 1",
                        "SobrePeso")));

        // Planes para diabetes tipo 1 con IMC Obesidad Tipo I y II
        planMap.put("diabetesTipo1ObesidadTipoIYII", Arrays.asList(
                Arrays.asList("Lunes", "Pierna", "Sentadillas", "Moderada", "diabetico tipo 1", "Obesidad Tipo I y II"),
                Arrays.asList("Lunes", "Pierna", "Puente De Glúteos", "Moderada", "diabetico tipo 1",
                        "Obesidad Tipo I y II"),
                Arrays.asList("Lunes", "Pierna", "Zancadas", "Moderada", "diabetico tipo 1", "Obesidad Tipo I y II"),
                Arrays.asList("Lunes", "Hombro", "Elevaciones Laterales", "Alta", "diabetico tipo 1",
                        "Obesidad Tipo I y II"),
                Arrays.asList("Lunes", "Hombro", "Press De Hombros Con Mancuernas", "Moderada", "diabetico tipo 1",
                        "Obesidad Tipo I y II"),
                Arrays.asList("Lunes", "Aerobico", "Trote Suave", "Moderada", "diabetico tipo 1",
                        "Obesidad Tipo I y II"),
                Arrays.asList("Martes", "Espalda", "Remo Con Mancuernas", "Moderada", "diabetico tipo 1",
                        "Obesidad Tipo I y II"),
                Arrays.asList("Martes", "Espalda", "Superman", "Alta", "diabetico tipo 1", "Obesidad Tipo I y II"),
                Arrays.asList("Martes", "Triceps", "Fondos De Tríceps En Banco", "Moderada", "diabetico tipo 1",
                        "Obesidad Tipo I y II"),
                Arrays.asList("Martes", "Triceps", "Extensión De Tríceps Con Mancuernas", "Baja", "diabetico tipo 1",
                        "Obesidad Tipo I y II"),
                Arrays.asList("Martes", "Anaerobicos", "Elevaciones Laterales Con Bandas Elásticas", "Moderada",
                        "diabetico tipo 1", "Obesidad Tipo I y II"),
                Arrays.asList("Martes", "Anaerobicos", "Escaladores En El Suelo", "Baja", "diabetico tipo 1",
                        "Obesidad Tipo I y II"),
                Arrays.asList("Miercoles", "Pecho", "Flexiones De Brazo", "Moderada", "diabetico tipo 1",
                        " Obesidad Tipo I y II"),
                Arrays.asList("Miercoles", "Pecho", "Press De Banca Con Mancuernas", "Baja", "diabetico tipo 1",
                        "Obesidad Tipo I y II"),
                Arrays.asList("Miercoles", "Biceps", "Flexión De Bíceps Con Bandas Elásticas Y Rotación De Torso",
                        "Baja", "diabetico tipo 1", "Obesidad Tipo I y II"),
                Arrays.asList("Miercoles", "Biceps",
                        "Flexión De Bíceps Con Bandas Elásticas Desde Banco Inclinado Con Giro De Torso", "Moderada",
                        "diabetico tipo 1", "Obesidad Tipo I y II"),
                Arrays.asList("Miercoles", "Antebrazo", "Flexiones De Muñeca", "Baja", "diabetico tipo 1",
                        "Obesidad Tipo I y II"),
                Arrays.asList("Miercoles", "Antebrazo", "Flexiones Con Cuerpo Recto Con Elevación De Cadera", "Baja",
                        "diabetico tipo 1", "Obesidad Tipo I y II"),
                Arrays.asList("Jueves", "Abdominales", "Bicicletas", "Alta", "diabetico tipo 1",
                        "Obesidad Tipo I y II"),
                Arrays.asList("Jueves", "Abdominales", "Russian Twists", "Moderada", "diabetico tipo 1",
                        "Obesidad Tipo I y II"),
                Arrays.asList("Jueves", "Pantorrilla", "Elevaciones De Pantorrillas", "Moderada", "diabetico tipo 1",
                        "Obesidad Tipo I y II"),
                Arrays.asList("Jueves", "Pantorrilla", "Elevaciones De Pantorrillas Con Rebote Y Salto", "Moderada",
                        "diabetico tipo 1", "Obesidad Tipo I y II"),
                Arrays.asList("Jueves", "Resistencia", "Burpees Con Salto Y Elevación De Rodillas", "Moderada",
                        "diabetico tipo 1", "Obesidad Tipo I y II"),
                Arrays.asList("Jueves", "Resistencia", "Escaladores De Montaña Cruzados", "Baja", "diabetico tipo 1",
                        "Obesidad Tipo I y II"),
                Arrays.asList("Viernes", "Fuerza", "Curl De Bíceps Con Mancuernas", "Baja", "diabetico tipo 1",
                        "Obesidad Tipo I y II"),
                Arrays.asList("Viernes", "Fuerza", "Peso Muerto Con Mochila", "Baja", "diabetico tipo 1",
                        "Obesidad Tipo I y II"),
                Arrays.asList("Viernes", "Fortalecimiento", "Plancha Con Toque De Hombro", "Moderada",
                        "diabetico tipo 1", "Obesidad Tipo I y II"),
                Arrays.asList("Viernes", "Fortalecimiento", "Abdominales Tipo Rana", "Moderada", "diabetico tipo 1",
                        "Obesidad Tipo I y II"),
                Arrays.asList("Viernes", "Anaerobico", "Elevaciones Frontales Con Mancuernas", "Baja",
                        "diabetico tipo 1", "Obesidad Tipo I y II"),
                Arrays.asList("Viernes", "Anaerobico", "Abdominales Laterales Con Bandas Elásticas", "Baja",
                        "diabetico tipo 1", "Obesidad Tipo I y II"),
                Arrays.asList("Sabado", "Equilibrio", "Saltos De Tijera", "Aerobico", "Alta", "diabetico tipo 1",
                        "Obesidad Tipo I y II"),
                Arrays.asList("Sabado", "Aerobico", "Mountain Climbers", "Alta", "diabetico tipo 1",
                        "Obesidad Tipo I y II"),
                Arrays.asList("Sabado", "Equilibrio", "Elevación De Piernas En Plancha Con Pesas", "Alta",
                        "diabetico tipo 1", "Obesidad Tipo I y II"),
                Arrays.asList("Sabado", "Equilibrio", "Equilibrio En T Con Mancuernas", "Alta", "diabetico tipo 1",
                        "Obesidad Tipo I y II"),
                Arrays.asList("Sabado", "Flexibilidad", "Yoga o Pilates", "Alta", "diabetico tipo 1",
                        "Obesidad Tipo I y II"),
                Arrays.asList("Sabado", "Flexibilidad", "Postura Del Puente", "Alta", "diabetico tipo 1",
                        "Obesidad Tipo I y II"),
                Arrays.asList("Domingo", "Flexibilidad", "Postura De La Silla", "Alta", "diabetico tipo 1",
                        "Obesidad Tipo I y II"),
                Arrays.asList("Domingo", "Flexibilidad", "Postura Del Guerrero", "Alta", "diabetico tipo 1",
                        "Obesidad Tipo I y II"),
                Arrays.asList("Domingo", "Flexibilidad", "Estiramiento De Aductores", "Alta", "diabetico tipo 1",
                        "Obesidad Tipo I y II"),
                Arrays.asList("Domingo", "Flexibilidad", "Estiramiento De Cuádriceps", "Alta", "diabetico tipo 1",
                        "Obesidad Tipo I y II"),
                Arrays.asList("Domingo", "Flexibilidad", "Estiramiento De Antebrazos", "Alta", "diabetico tipo 1",
                        "Obesidad Tipo I y II"),
                Arrays.asList("Domingo", "Flexibilidad", "Estiramiento De Los Músculos Laterales Del Tronco", "Alta",
                        "diabetico tipo 1", "Obesidad Tipo I y II")));

        // Planes para diabetes tipo 1 con IMC Obesidad Tipo III y IV
        planMap.put("diabetesTipo1ObesidadTipoIIIYIV", Arrays.asList(
                Arrays.asList("Lunes", "Pierna", "Sentadillas", "Moderada", "diabetico tipo 1",
                        "Obesidad Tipo III y IV"),
                Arrays.asList("Lunes", "Pierna", "Puente De Glúteos", "Moderada", "diabetico tipo 1",
                        "Obesidad Tipo III y IV"),
                Arrays.asList("Lunes", "Pierna", "Zancadas", "Moderada", "diabetico tipo 1", "Obesidad Tipo III y IV"),
                Arrays.asList("Lunes", "Hombro", "Elevaciones Laterales", "Alta", "diabetico tipo 1",
                        "Obesidad Tipo III y IV"),
                Arrays.asList("Lunes", "Hombro", "Press De Hombros Con Mancuernas", "Moderada", "diabetico tipo 1",
                        "Obesidad Tipo III y IV"),
                Arrays.asList("Lunes", "Aerobico", "Trote Suave", "Moderada", "diabetico tipo 1",
                        "Obesidad Tipo III y IV"),
                Arrays.asList("Martes", "Espalda", "Remo Con Mancuernas", "Moderada", "diabetico tipo 1",
                        "Obesidad Tipo III y IV"),
                Arrays.asList("Martes", "Espalda", "Superman", "Alta", "diabetico tipo 1", "Obesidad Tipo III y IV"),
                Arrays.asList("Martes", "Triceps", "Fondos De Tríceps En Banco", "Moderada", "diabetico tipo 1",
                        "Obesidad Tipo III y IV"),
                Arrays.asList("Martes", "Triceps", "Extensión De Tríceps Con Mancuernas", "Baja", "diabetico tipo 1",
                        "Obesidad Tipo III y IV"),
                Arrays.asList("Martes", "Anaerobicos", "Elevaciones Laterales Con Bandas Elásticas", "Moderada",
                        "diabetico tipo 1", "Obesidad Tipo III y IV"),
                Arrays.asList("Martes", "Anaerobicos", "Escaladores En El Suelo", "Baja", "diabetico tipo 1",
                        "Obesidad Tipo III y IV"),
                Arrays.asList("Miercoles", "Pecho", "Flexiones De Brazo", "Moderada", "diabetico tipo 1",
                        "Obesidad Tipo III y IV"),
                Arrays.asList("Miercoles", "Pecho", "Press De Banca Con Mancuernas", "Baja", "diabetico tipo 1",
                        "Obesidad Tipo III y IV"),
                Arrays.asList("Miercoles", "Biceps", "Flexión De Bíceps Con Bandas Elásticas Y Rotación De Torso",
                        "Baja", "diabetico tipo 1", "Obesidad Tipo III y IV"),
                Arrays.asList("Miercoles", "Biceps",
                        "Flexión De Bíceps Con Bandas Elásticas Desde Banco Inclinado Con Giro De Torso", "Moderada",
                        "diabetico tipo 1", "Obesidad Tipo III y IV"),
                Arrays.asList("Miercoles", "Antebrazo", "Flexiones De Muñeca", "Baja", "diabetico tipo 1",
                        "Obesidad Tipo III y IV"),
                Arrays.asList("Miercoles", "Antebrazo", "Flexiones Con Cuerpo Recto Con Elevación De Cadera", "Baja",
                        "diabetico tipo 1", "Obesidad Tipo III y IV"),
                Arrays.asList("Jueves", "Abdominales", "Bicicletas", "Alta", "diabetico tipo 1",
                        "Obesidad Tipo III y IV"),
                Arrays.asList("Jueves", "Abdominales", "Russian Twists", "Moderada", "diabetico tipo 1",
                        "Obesidad Tipo III y IV"),
                Arrays.asList("Jueves", "Pantorrilla", "Elevaciones De Pantorrillas", "Moderada", "diabetico tipo 1",
                        "Obesidad Tipo III y IV"),
                Arrays.asList("Jueves", "Pantorrilla", "Elevaciones De Pantorrillas Con Rebote Y Salto", "Moderada",
                        "diabetico tipo 1", "Obesidad Tipo III y IV"),
                Arrays.asList("Jueves", "Resistencia", "Burpees Con Salto Y Elevación De Rodillas", "Moderada",
                        "diabetico tipo 1", "Obesidad Tipo III y IV"),
                Arrays.asList("Jueves", "Resistencia", "Escaladores De Montaña Cruzados", "Baja", "diabetico tipo 1",
                        "Obesidad Tipo III y IV"),
                Arrays.asList("Viernes", "Fuerza", "Curl De Bíceps Con Mancuernas", "Baja", "diabetico tipo 1",
                        "Obesidad Tipo III y IV"),
                Arrays.asList("Viernes", "Fuerza", "Peso Muerto Con Mochila", "Baja", "diabetico tipo 1",
                        "Obesidad Tipo III y IV"),
                Arrays.asList("Viernes", "Fortalecimiento", "Plancha Con Toque De Hombro", "Moderada",
                        "diabetico tipo 1", "Obesidad Tipo III y IV"),
                Arrays.asList("Viernes", "Fortalecimiento", "Abdominales Tipo Rana", "Moderada", "diabetico tipo 1",
                        "Obesidad Tipo III y IV"),
                Arrays.asList("Viernes", "Anaerobico", "Elevaciones Frontales Con Mancuernas", "Baja",
                        "diabetico tipo 1", "Obesidad Tipo III y IV"),
                Arrays.asList("Viernes", "Anaerobico", "Abdominales Laterales Con Bandas Elásticas", "Baja",
                        "diabetico tipo 1", "Obesidad Tipo III y IV"),
                Arrays.asList("Sabado", "Equilibrio", "Saltos De Tijera", "Aerobico", "Alta", "diabetico tipo 1",
                        "Obesidad Tipo III y IV"),
                Arrays.asList("Sabado", "Aerobico", "Mountain Climbers", "Alta", "diabetico tipo 1",
                        "Obesidad Tipo III y IV"),
                Arrays.asList("Sabado", "Equilibrio", "Elevación De Piernas En Plancha Con Pesas", "Alta",
                        "diabetico tipo 1", "Obesidad Tipo III y IV"),
                Arrays.asList("Sabado", "Equilibrio", "Equilibrio En T Con Mancuernas", "Alta", "diabetico tipo 1",
                        "Obesidad Tipo III y IV"),
                Arrays.asList("Sabado", "Flexibilidad", "Yoga o Pilates", "Alta", "diabetico tipo 1",
                        "Obesidad Tipo III y IV"),
                Arrays.asList("Sabado", "Flexibilidad", "Postura Del Puente", "Alta", "diabetico tipo 1",
                        "Obesidad Tipo III y IV"),
                Arrays.asList("Domingo", "Flexibilidad", "Postura De La Silla", "Alta", "diabetico tipo 1",
                        "Obesidad Tipo III y IV"),
                Arrays.asList("Domingo", "Flexibilidad", "Postura Del Guerrero", "Alta", "diabetico tipo 1",
                        "Obesidad Tipo III y IV"),
                Arrays.asList("Domingo", "Flexibilidad", "Estiramiento De Aductores", "Alta", "diabetico tipo 1",
                        "Obesidad Tipo III y IV"),
                Arrays.asList("Domingo", "Flexibilidad", "Estiramiento De Cuádriceps", "Alta", "diabetico tipo 1",
                        "Obesidad Tipo III y IV"),
                Arrays.asList("Domingo", "Flexibilidad", "Estiramiento De Antebrazos", "Alta", "diabetico tipo 1",
                        "Obesidad Tipo III y IV"),
                Arrays.asList("Domingo", "Flexibilidad", "Estiramiento De Los Músculos Laterales Del Tronco", "Alta",
                        "diabetico tipo 1", "Obesidad Tipo III y IV")));

        // Planes para diabetes tipo 2 con IMC bajo de peso
        planMap.put("diabetesTipo2BajoPeso", Arrays.asList(
                Arrays.asList("Lunes", "Piernas", "Sentadillas", "Moderada", "diabetico tipo 2", "BajoDePeso"),
                Arrays.asList("Lunes", "Piernas", "Puente De Glúteos", "Moderada", "diabetico tipo 2", "BajoDePeso"),
                Arrays.asList("Lunes", "Piernas", "Zancadas", "Moderada", "diabetico tipo 2", "BajoDePeso"),
                Arrays.asList("Lunes", "Hombro", "Elevaciones Laterales", "Alta", "diabetico tipo 2", "BajoDePeso"),
                Arrays.asList("Lunes", "Hombro", "Press De Hombros Con Mancuernas", "Moderada", "diabetico tipo 2",
                        "BajoDePeso"),
                Arrays.asList("Lunes", "Aerobico", "Trote Suave", "Moderada", "diabetico tipo 2", "BajoDePeso"),
                Arrays.asList("Lunes", "Flexibilidad", "Estiramiento De Cuádriceps", "Alta", "diabetico tipo 2",
                        "BajoDePeso"),
                Arrays.asList("Lunes", "Flexibilidad", "Estiramiento De Antebrazos", "Alta", "diabetico tipo 2",
                        "BajoDePeso"),
                Arrays.asList("Martes", "Aerobico", "Saltos De Tijera", "Alta", "diabetico tipo 2", "BajoDePeso"),
                Arrays.asList("Martes", "Aerobico", "Mountain Climbers", "Alta", "diabetico tipo 2", "BajoDePeso"),
                Arrays.asList("Martes", "Equilibrio", "Elevación De Piernas En Plancha Con Pesas", "Moderada",
                        "diabetico tipo 2", "BajoDePeso"),
                Arrays.asList("Martes", "Equilibrio", "Equilibrio En T Con Mancuernas", "Moderada", "diabetico tipo 2",
                        "BajoDePeso"),
                Arrays.asList("Martes", "Flexibilidad", "Estiramiento De Antebrazos", "Moderada", "diabetico tipo 2",
                        "BajoDePeso"),
                Arrays.asList("Martes", "Flexibilidad", "Estiramiento De Los Músculos Laterales Del Tronco", "Moderada",
                        "diabetico tipo 2", "BajoDePeso"),
                Arrays.asList("Martes", "Flexibilidad", "Estiramiento De Aductores", "Moderada", "diabetico tipo 2",
                        "BajoDePeso"),
                Arrays.asList("Miercoles", "Pecho", "Flexiones De Brazo", "Moderada", "diabetico tipo 2", "BajoDePeso"),
                Arrays.asList("Miercoles", "Pecho", "Press De Banca Con Mancuernas", "Moderada", "diabetico tipo 2",
                        "BajoDePeso"),
                Arrays.asList("Miercoles", "Biceps", "Flexión De Bíceps Con Bandas Elásticas Y Rotación De Torso",
                        "Moderada", "diabetico tipo 2", "BajoDePeso"),
                Arrays.asList("Miercoles", "Biceps",
                        "Flexión De Bíceps Con Bandas Elásticas Desde Banco Inclinado Con Giro De Torso", "Moderada",
                        "diabetico tipo 2", "BajoDePeso"),
                Arrays.asList("Miercoles", "Antebrazo", "Flexiones De Muñeca", "Moderada", "diabetico tipo 2",
                        "BajoDePeso"),
                Arrays.asList("Miercoles", "Antebrazo", "Flexiones Con Cuerpo Recto Con Elevación De Cadera",
                        "Moderada", "diabetico tipo 2", "BajoDePeso"),
                Arrays.asList("Jueves", "Abdominales", "Crunches", "Moderada", "diabetico tipo 2", "BajoDePeso"),
                Arrays.asList("Jueves", "Abdominales", "Abdominales Tipo Bicicleta", "Moderada", "diabetico tipo 2",
                        "BajoDePeso"),
                Arrays.asList("Jueves", "Abdominales", "Plancha", "Moderada", "diabetico tipo 2", "BajoDePeso"),
                Arrays.asList("Jueves", "Pantorrilla", "Elevaciones De Talón", "Alta", "diabetico tipo 2",
                        "BajoDePeso"),
                Arrays.asList("Jueves", "Pantorrilla", "Elevaciones De Talón En Banco Con Salto", "Alta",
                        "diabetico tipo 2", "BajoDePeso"),
                Arrays.asList("Jueves", "Abdominales", "Flexiones De Puente", "Resistencia", "diabetico tipo 2",
                        "BajoDePeso"),
                Arrays.asList("Jueves", "Abdominales", "Flexiones Con Codos Cerrados", "Resistencia",
                        "diabetico tipo 2", "BajoDePeso"),
                Arrays.asList("Jueves", "Flexibilidad", "Estiramientos De Cuerpo Completo", "Alta", "diabetico tipo 2",
                        "BajoDePeso"),
                Arrays.asList("Viernes", "Pierna", "Sentadillas De Sumo", "Baja", "diabetico tipo 2", "BajoDePeso"),
                Arrays.asList("Viernes", "Fuerza", "Flexiones De Pecho Con Bandas Elásticas", "Baja",
                        "diabetico tipo 2", "BajoDePeso"),
                Arrays.asList("Viernes", "Fuerza", "Prensa De Hombros Con Bandas Elásticas", "Baja", "diabetico tipo 2",
                        "BajoDePeso"),
                Arrays.asList("Viernes", "Fortalecimiento", "Plancha", "Moderada", "diabetico tipo 2", "BajoDePeso"),
                Arrays.asList("Viernes", "Fortalecimiento", "Bird-Dog", "Moderada", "diabetico tipo 2", "BajoDePeso"),
                Arrays.asList("Viernes", "Anaerobicos", "Estocadas Con Salto", "Baja", "diabetico tipo 2",
                        "BajoDePeso"),
                Arrays.asList("Viernes", "Anaerobicos", "Patadas Frontales", "Baja", "diabetico tipo 2", "BajoDePeso"),
                Arrays.asList("Viernes", "Anaerobicos", "Elevaciones Laterales Con Bandas Elásticas", "Baja",
                        "diabetico tipo 2", "BajoDePeso"),
                Arrays.asList("Sabado", "Equilibrio", "Postura Del Árbol", "Alta", "diabetico tipo 2", "BajoDePeso"),
                Arrays.asList("Sabado", "Equilibrio", "Elevación De Una Pierna", "Alta", "diabetico tipo 2",
                        "BajoDePeso"),
                Arrays.asList("Sabado", "Flexibilidad", "Estiramientos De Espalda", "Alta", "diabetico tipo 2",
                        "BajoDePeso"),
                Arrays.asList("Sabado", "Flexibilidad", "Estiramientos De Hombros Y Cuello", "Alta", "diabetico tipo 2",
                        "BajoDePeso"),
                Arrays.asList("Domingo", "Flexibilidad", "Estiramientos De Cuádriceps", "Alta", "diabetico tipo 2",
                        "BajoDePeso"),
                Arrays.asList("Domingo", "Flexibilidad", "Estiramientos De Isquiotibiales", "Alta", "diabetico tipo 2",
                        "BajoDePeso"),
                Arrays.asList("Domingo", "Flexibilidad", "Estiramientos De Pantorrillas", "Alta", "diabetico tipo 2",
                        "BajoDePeso"),
                Arrays.asList("Domingo", "Flexibilidad", "Sesión de yoga suave", "Alta", "diabetico tipo 2",
                        "BajoDePeso")));

        // Planes para diabetes tipo 2 con IMC sobrepeso
        planMap.put("diabetesTipo2SobrePeso", Arrays.asList(
                Arrays.asList("Lunes", "Piernas", "Sentadillas", "Moderada", "diabetico tipo 2", "SobrePeso"),
                Arrays.asList("Lunes", "Piernas", "Puente De Glúteos", "Moderada", "diabetico tipo 2", "SobrePeso"),
                Arrays.asList("Lunes", "Piernas", "Estiramiento De Cuádriceps", "Moderada", "diabetico tipo 2",
                        "SobrePeso"),
                Arrays.asList("Lunes", "Flexibilidad", "Postura Del Árbol", "Moderada", "diabetico tipo 2",
                        "SobrePeso"),
                Arrays.asList("Lunes", "Equilibrio", "Equilibrio Con Extensión De Brazos Y Piernas", "Moderada",
                        "diabetico tipo 2", "SobrePeso"),
                Arrays.asList("Lunes", "Equilibrio", "Equilibrio En T", "Moderada", "diabetico tipo 2", "SobrePeso"),
                Arrays.asList("Martes", "Pecho", "Flexiones De Brazo", "Alta", "diabetico tipo 2", "SobrePeso"),
                Arrays.asList("Martes", "Pecho", "Press De Banca Con Mancuernas", "Alta", "diabetico tipo 2",
                        "SobrePeso"),
                Arrays.asList("Martes", "Hombro", "Elevaciones Laterales", "Moderada", "diabetico tipo 2", "SobrePeso"),
                Arrays.asList("Martes", "Hombro", "Press De Hombros Con Mancuernas", "Moderada", "diabetico tipo 2",
                        "SobrePeso"),
                Arrays.asList("Martes", "Antebrazo", "Flexiones De Muñeca", "Moderada", "diabetico tipo 2",
                        "SobrePeso"),
                Arrays.asList("Martes", "Antebrazo", "Extensiones De Muñeca", "Moderada", "diabetico tipo 2",
                        "SobrePeso"),
                Arrays.asList("Miercoles", "Espalda", "Superman", "Moderada", "diabetico tipo 2", "SobrePeso"),
                Arrays.asList("Miercoles", "Espalda", "Remo Con Mancuernas", "Moderada", "diabetico tipo 2",
                        "SobrePeso"),
                Arrays.asList("Miercoles", "Antebrazo", "Flexión De Muñeca Con Mancuernas", "Moderada",
                        "diabetico tipo 2", "SobrePeso"),
                Arrays.asList("Miercoles", "Antebrazo", "Flexiones Con Cuerpo Recto Con Elevación De Cadera",
                        "Moderada", "diabetico tipo 2", "SobrePeso"),
                Arrays.asList("Miercoles", "Fuerza", "Remo con barra", "Moderada", "diabetico tipo 2", "SobrePeso"),
                Arrays.asList("Miercoles", "Fuerza", "Elevaciones de pantorrillas", "Moderada", "diabetico tipo 2",
                        "SobrePeso"),
                Arrays.asList("Jueves", "Flexibilidad", "Postura Del Árbol", "Moderada", "diabetico tipo 2",
                        "SobrePeso"),
                Arrays.asList("Jueves", "Flexibilidad", "Estiramiento De Cuádriceps", "Moderada", "diabetico tipo 2",
                        "SobrePeso"),
                Arrays.asList("Jueves", "Flexibilidad", "Estiramiento de los isquiotibiales", "Moderada",
                        "diabetico tipo 2", "SobrePeso"),
                Arrays.asList("Jueves", "Flexibilidad", "Estiramiento De Cuádriceps", "Moderada", "diabetico tipo 2",
                        "SobrePeso"),
                Arrays.asList("Jueves", "Aeróbico", "Caminar a paso ligero", "Moderada", "diabetico tipo 2",
                        "SobrePeso"),
                Arrays.asList("Jueves", "Aeróbico", "Trotar En El Mismo Lugar", "Moderada", "diabetico tipo 2",
                        "SobrePeso"),
                Arrays.asList("Viernes", "Fortalecimiento", "Estocadas Con Salto", "Moderada", "diabetico tipo 2",
                        "SobrePeso"),
                Arrays.asList("Viernes", "Fortalecimiento", "Sentadillas Búlgaras", "Moderada", "diabetico tipo 2",
                        "SobrePeso"),
                Arrays.asList("Viernes", "Fuerza", "Fondos De TrícepsEn Silla", "Baja", "diabetico tipo 2",
                        "SobrePeso"),
                Arrays.asList("Viernes", "Fuerza", "Plancha Lateral", "Moderada", "diabetico tipo 2", "SobrePeso"),
                Arrays.asList("Viernes", "Flexibilidad", "Estiramiento Cuerpo Completo", "Alta", "diabetico tipo 2",
                        "SobrePeso"),
                Arrays.asList("Sabado", "Aeróbico", "Caminar a paso ligero", "Moderada", "diabetico tipo 2",
                        "SobrePeso"),
                Arrays.asList("Sabado", "Aeróbico", "Trote Suave", "Moderada", "diabetico tipo 2", "SobrePeso"),
                Arrays.asList("Domingo", "Flexibilidad", "Estiramiento De Antebrazos", "Alta", "diabetico tipo 2",
                        "SobrePeso"),
                Arrays.asList("Domingo", "Flexibilidad", "Estiramiento De Muñeca", "Alta", "diabetico tipo 2",
                        "SobrePeso"),
                Arrays.asList("Domingo", "Flexibilidad", "Estiramiento De Gemelos", "Alta", "diabetico tipo 2",
                        "SobrePeso"),
                Arrays.asList("Domingo", "Equilibrio", "Equilibrio En Talones", "Alta", "diabetico tipo 2",
                        "SobrePeso"),
                Arrays.asList("Domingo", "Equilibrio", "Equilibrio Con Banda Elástica", "Alta", "diabetico tipo 2",
                        "SobrePeso")));

        return planMap;
    }

    @GetMapping("/PlanEjercicio")
    public String listExercises(Model model, HttpSession session) {
        Long userId = (Long) session.getAttribute("UsuarioId");
        if (userId != null) {
            UserModel user = userService.getUserById(userId);
            if (user != null) {
                String disease = user.getDisease();
                String healthClassification = user.getHealthClassification();
                // Filtra los planes según la enfermedad y la clasificación de salud
                Map<String, List<List<String>>> exercisePlans = filterPlans(disease, healthClassification);
                model.addAttribute("exercisePlans", exercisePlans);
                return "/Health_Plans/Exercises/PlanesEjercicio"; // Vista donde se mostrarán los ejercicios
            }
        }
        model.addAttribute("error", "Usuario no encontrado.");
        return "redirect:/Api/Users/Login"; // Redirige a login si el usuario no se encuentra
    }

    private Map<String, List<List<String>>> filterPlans(String disease, String healthClassification) {
        Map<String, List<List<String>>> filteredPlans = new HashMap<>();
        // Filtrar planes para hipertensos
        if ("hipertensos".equals(disease)) {
            if ("Bajo Peso".equals(healthClassification)) {
                filteredPlans.put("hipertensosBajoDePeso", PlanesMap().get("hipertensosBajoDePeso"));
            } else if ("SobrePeso".equals(healthClassification)) {
                filteredPlans.put("hipertensosSobrePeso", PlanesMap().get("hipertensosSobrePeso"));
            }
        }
        // Filtrar planes para diabetes tipo 1
        if ("diabetico tipo 1".equals(disease)) {
            if ("BajoDePeso".equals(healthClassification)) {
                filteredPlans.put("diabetesTipo1BajoPeso", PlanesMap().get("diabetesTipo1BajoPeso"));
            } else if ("SobrePeso".equals(healthClassification)) {
                filteredPlans.put("diabetesTipo1SobrePeso", PlanesMap().get("diabetesTipo1SobrePeso"));
            } else if ("Obesidad Tipo I y II".equals(healthClassification)) {
                filteredPlans.put("diabetesTipo1ObesidadTipoIYII", PlanesMap().get("diabetesTipo1ObesidadTipoIYII"));
            } else if ("Obesidad Tipo III y IV".equals(healthClassification)) {
                filteredPlans.put("diabetesTipo1ObesidadTipoIIIYIV", PlanesMap().get("diabetesTipo1ObesidadTipoIIIYIV"));
            }
        }
        // Filtrar planes para diabetes tipo 2
        if ("diabetico tipo 2".equals(disease)) {
            if ("BajoDePeso".equals(healthClassification)) {
                filteredPlans.put("diabetesTipo2BajoPeso", PlanesMap().get("diabetesTipo2BajoPeso"));
            } else if ("SobrePeso".equals(healthClassification)) {
                filteredPlans.put("diabetesTipo2SobrePeso", PlanesMap().get("diabetesTipo2SobrePeso"));
            }
        }
        return filteredPlans;
    }

}