-- Planes de Ejercicio --
CREATE TABLE IF NOT EXISTS plans_exercises (
    Id BIGINT AUTO_INCREMENT PRIMARY KEY,
    Day VARCHAR(255) NOT NULL,
    ExerciseName VARCHAR(255),
    ExerciseType VARCHAR(255),
    ExerciseIntensity VARCHAR(255),
    Disease VARCHAR(255),
    HealthClassification VARCHAR(255)
);

-- Insertar plan de ejercicios para hipertensos con IMC bajo de peso
INSERT INTO plans_exercises (Day, ExerciseName, ExerciseType, ExerciseIntensity, Disease, HealthClassification) VALUES
('Lunes', 'Saltos De Cuerda', 'Aerobicos', 'Moderada', 'hipertensos', 'Bajo Peso'),
('Lunes', 'Saltos De Tijera', 'Aerobicos', 'Moderada', 'hipertensos', 'Bajo Peso'),
('Lunes', 'Caminata Rápida', 'Aeróbicos', 'Baja', 'hipertensos', 'Bajo Peso'),
('Lunes', 'bicicleta Estática', 'Aeróbicos', 'Alta', 'hipertensos', 'Bajo Peso'),
('Lunes', 'Sentadillas Sin Peso O Con Una Silla', 'Pierna', 'Moderada', 'hipertensos', 'Bajo Peso'),
('Lunes', 'Sentadillas Con Salto', 'Pierna', 'Baja', 'hipertensos', 'Bajo Peso'),
('Lunes', 'Elevaciones De Talones Con Elevación De Cadera', 'Pierna', 'Moderada', 'hipertensos', 'Bajo Peso'),
('Lunes', 'Elevaciones Laterales Con Bandas Elásticas', 'Hombro', 'Moderada', 'hipertensos', 'Bajo Peso'),
('Lunes', 'Elevaciones Frontales Con Bandas Elásticas Y Giro', 'Hombro', 'Alta', 'hipertensos', 'Bajo Peso'),
('Lunes', 'Elevaciones Frontales Con Bandas Elásticas Con Giro De Pie', 'Hombro', 'Baja', 'hipertensos', 'Bajo Peso'),
('Martes', 'Flexiones Inclinadas', 'Espalda', 'Baja', 'hipertensos', 'Bajo Peso'),
('Martes', 'Escaladores De Montaña', 'Espalda', 'Moderada', 'hipertensos', 'Bajo Peso'),
('Martes', 'Remo Con Bandas Elásticas', 'Espalda', 'Alta', 'hipertensos', 'Bajo Peso'),
('Martes', 'Fondos En Silla', 'Triceps', 'Moderada', 'hipertensos', 'Bajo Peso'),
('Martes', 'Fondos En El Suelo', 'Triceps', 'Baja', 'hipertensos', 'Bajo Peso'),
('Martes', 'Fondos De Tríceps Con Elevación De Pierna', 'Triceps', 'Moderada', 'hipertensos', 'Bajo Peso'),
('Martes', 'Levantamiento de una pierna', 'Equilibrio', 'Alta', 'hipertensos', 'Bajo Peso'),
('Martes', 'Equilibrio En T', 'Equilibrio', 'Alta', 'hipertensos', 'Bajo Peso'),
('Martes', 'Equilibrio En Talones', 'Equilibrio', 'Alta', 'hipertensos', 'Bajo Peso'),
('Miercoles', 'Flexiones De Brazo', 'Pecho', 'Baja', 'hipertensos', 'Bajo Peso'),
('Miercoles', 'Flexiones Con Brazos Abiertos', 'Pecho', 'Baja', 'hipertensos', 'Bajo Peso'),
('Miercoles', 'Flexiones Inclinadas', 'Pecho', 'Alta', 'hipertensos', 'Bajo Peso'),
('Miercoles', 'Curl De Bíceps Con Bandas Elásticas', 'Biceps', 'Moderada', 'hipertensos', 'Bajo Peso'),
('Miercoles', 'Curl De Bíceps Con Bandas Elásticas Alternado', 'Biceps', 'Moderada', 'hipertensos', 'Bajo Peso'),
('Miercoles', 'Curl De Bíceps Con Bandas Elásticas Cruzadas', 'Biceps', 'Moderada', 'hipertensos', 'Bajo Peso'),
('Miercoles', 'Curl De Muñeca Con Bandas Elásticas', 'Antebrazo', 'Moderada', 'hipertensos', 'Bajo Peso'),
('Miercoles', 'Extensión De Muñeca Con Bandas Elásticas', 'Antebrazo', 'Moderada', 'hipertensos', 'Bajo Peso'),
('Miercoles', 'Extensión De Muñeca Con Bandas Elásticas Y Giro De Torso', 'Antebrazo', 'Moderada', 'hipertensos', 'Bajo Peso'),
('Jueves', 'Abdominales Tradicionales', 'Abdominales', 'Moderada', 'hipertensos', 'Bajo Peso'),
('Jueves', 'Abdominales Tipo Bicicleta', 'Abdominales', 'Moderada', 'hipertensos', 'Bajo Peso'),
('Jueves', 'Abdominales Con Piernas Elevadas', 'Abdominales', 'Moderada', 'hipertensos', 'Bajo Peso'),
('Jueves', 'Elevaciones De Talón', 'Pantorrilla', 'Moderada', 'hipertensos', 'Bajo Peso'),
('Jueves', 'Elevaciones De Talón Con Una Pierna', 'Pantorrilla', 'Baja', 'hipertensos', 'Bajo Peso'),
('Jueves', 'Elevaciones De Talón En Escalón', 'Pantorrilla', 'Moderada', 'hipertensos', 'Bajo Peso'),
('Jueves', 'Estiramiento De Cuádriceps', 'Flexibilidad', 'Alta', 'hipertensos', 'Bajo Peso'),
('Jueves', 'Estiramiento De Pantorrillas', 'Flexibilidad', 'Alta', 'hipertensos', 'Bajo Peso'),
('Jueves', 'Estiramiento De Cadera', 'Flexibilidad', 'Alta', 'hipertensos', 'Bajo Peso'),
('Viernes', 'Flexiones De Brazo (Push-Ups)', 'Fuerza', 'Baja', 'hipertensos', 'Bajo Peso'),
('Viernes', 'Flexiones Inclinadas', 'Fuerza', 'Baja', 'hipertensos', 'Bajo Peso'),
('Viernes', 'Fondos De Tríceps En Silla', 'Fuerza', 'Baja', 'hipertensos', 'Bajo Peso'),
('Viernes', 'Saltos De Tijera', 'Resistencia', 'Moderada', 'hipertensos', 'Bajo Peso'),
('Viernes', 'Sentadillas Con Salto', 'Resistencia', 'Baja', 'hipertensos', 'Bajo Peso'),
('Viernes', 'Flexiones Declinadas', 'Resistencia', 'Baja', 'hipertensos', 'Bajo Peso'),
('Viernes', 'Rodillas Al Pecho', 'Aerobico', 'Alta', 'hipertensos', 'Bajo Peso'),
('Viernes', 'Skipping', 'Aerobico', 'Alta', 'hipertensos', 'Bajo Peso'),
('Viernes', 'Salto De Estrella', 'Aerobico', 'Alta', 'hipertensos', 'Bajo Peso'),
('Sabado', 'Estocadas Con Salto', 'Fortalecimiento', 'Moderada', 'hipertensos', 'Bajo Peso'),
('Sabado', 'Desplantes Laterales', 'Fortalecimiento', 'Moderada', 'hipertensos', 'Bajo Peso'),
('Sabado', 'Abdominales Laterales', 'Fortalecimiento', 'Alta', 'hipertensos', 'Bajo Peso'),
('Sabado', 'Elevaciones De Cadera', 'Anaerobicos', 'Baja', 'hipertensos', 'Bajo Peso'),
('Sabado', 'Abdominales En V', 'Anaerobicos', 'Baja', 'hipertensos', 'Bajo Peso'),
('Sabado', 'Escaladores Cruzados', 'Anaerobicos', 'Baja', 'hipertensos', 'Bajo Peso'),
('Sabado', 'Correr Con Elevación De Rodillas', 'Aerobico', 'Alta', 'hipertensos', 'Bajo Peso'),
('Sabado', 'Saltos En Zig-Zag', 'Aerobico', 'Moderada', 'hipertensos', 'Bajo Peso'),
('Sabado', 'Saltos De Rana', 'Aerobico', 'Alta', 'hipertensos', 'Bajo Peso'),
('Domingo', 'Estiramiento De Flexores De Cadera', 'Flexibilidad', 'Alta', 'hipertensos', 'Bajo Peso'),
('Domingo', 'Estiramiento De Antebrazos', 'Flexibilidad', 'Alta', 'hipertensos', 'Bajo Peso'),
('Domingo', 'Estiramiento De Abductores', 'Flexibilidad', 'Alta', 'hipertensos', 'Bajo Peso'),
('Domingo', 'Estiramiento De Hombros', 'Flexibilidad', 'Alta', 'hipertensos', 'Bajo Peso'),
('Domingo', 'Estiramiento De Isquiotibiales', 'Flexibilidad', 'Alta', 'hipertensos', 'Bajo Peso');

-- Insertar plan de ejercicios para hipertensos con IMC sobrepeso
INSERT INTO plans_exercises (Day, ExerciseName, ExerciseType, ExerciseIntensity, Disease, HealthClassification) VALUES
('Lunes', 'Trote Moderado', 'Aerobicos', 'Moderada', 'hipertensos', 'SobrePeso'),
('Lunes', 'Saltos Laterales', 'Aerobicos', 'Alta', 'hipertensos', 'SobrePeso'),
('Lunes', 'Abdominales Tipo Bicicleta', 'Aerobicos', 'Moderada', 'hipertensos', 'SobrePeso'),
('Lunes', 'sentadillas', 'Pierna', 'Moderada', 'hipertensos', 'SobrePeso'),
('Lunes', 'Sentadillas De Sumo', 'Pierna', 'Moderada', 'hipertensos', 'SobrePeso'),
('Lunes', 'Sentadillas Con Elevación De Brazos', 'Pierna', 'Moderada', 'hipertensos', 'SobrePeso'),
('Lunes', 'Elevaciones Laterales Con Bandas Elásticas Cruzadas', 'Hombro', 'Moderada', 'hipertensos', 'SobrePeso'),
('Lunes', 'Elevaciones Laterales Con Bandas Elásticas Y Elevación De Brazo', 'Hombro', 'Moderada', 'hipertensos', 'SobrePeso'),
('Martes', 'remo con bandas elásticas', 'Espalda', 'Alta', 'hipertensos', 'SobrePeso'),
('Martes', 'Pull-ups De Barra Casera', 'Espalda', 'Moderada', 'hipertensos', 'SobrePeso'),
('Martes', 'Remo Con Bandas Elásticas Alternando Brazos', 'Espalda', 'Alta', 'hipertensos', 'SobrePeso'),
('Martes', 'Fondos Con Elevación De Talones', 'Triceps', 'Baja', 'hipertensos', 'SobrePeso'),
('Martes', 'Fondos Con Rotación De Torso', 'Triceps', 'Baja', 'hipertensos', 'SobrePeso'),
('Martes', 'Extensión De Tríceps Con Bandas Elásticas Desde Banco', 'Triceps', 'Baja', 'hipertensos', 'SobrePeso'),
('Miercoles', 'Flexiones Con Bandas Elásticas Y Elevación De Pies', 'Pecho', 'Moderada', 'hipertensos', 'SobrePeso'),
('Miercoles', 'Aperturas De Pecho Con Bandas Elásticas Y Elevación De Piernas', 'Pecho', 'Moderada', 'hipertensos', 'SobrePeso'),
('Miercoles', 'Flexiones De Brazo', 'Pecho', 'Moderada', 'hipertensos', 'SobrePeso'),
('Miercoles', 'Flexiones Con Agarre Estrecho', 'Biceps', 'Moderada', 'hipertensos', 'SobrePeso'),
('Miercoles', 'Flexión De Bíceps Con Bandas Elásticas Cruzada Desde Banco Inclinado', 'Biceps', 'Moderada', 'hipertensos', 'SobrePeso'),
('Miercoles', 'Flexión De Bíceps Con Bandas Elásticas Con Elevación De Talones', 'Biceps', 'Moderada', 'hipertensos', 'SobrePeso'),
('Jueves', 'Abdominales Tradicionales', 'Abdominales', 'Moderada', 'hipertensos', 'SobrePeso'),
('Jueves', 'Abdominales Tipo Bicicleta', 'Abdominales', 'Moderada', 'hipertensos', 'SobrePeso'),
('Jueves', 'Elevaciones De Talón', 'Pantorrilla', 'Moderada', 'hipertensos', 'SobrePeso'),
('Jueves', 'Elevaciones De Talón Con Una Pierna', 'Pantorrilla', 'Baja', 'hipertensos', 'SobrePeso'),
('Jueves', 'Elevaciones De Talón En Escalón', 'Pantorrilla', 'Moderada', 'hipertensos', 'SobrePeso'),
('Jueves', 'Estiramiento De Pantorrillas', 'Flexibilidad', 'Alta', 'hypertensos', 'SobrePeso'),
('Jueves', 'Estiramiento De Cadera', 'Flexibilidad', 'Alta', 'hipertensos', 'SobrePeso'),
('Viernes', 'Burpees Con Flexiones', 'Fuerza', 'Baja', 'hipertensos', 'SobrePeso'),
('Viernes', 'Sentadillas Con Bandas Elásticas', 'Fuerza', 'Baja', 'hipertensos', 'SobrePeso'),
('Viernes', 'Tabata De Escaladores', 'Aerobico', 'Moderada', 'hipertensos', 'SobrePeso'),
('Viernes', 'Tabata De Saltos De Tijera', 'Aerobico', 'Alta', 'hipertensos', 'SobrePeso'),
('Viernes', 'Escaladores De Montaña', 'Resistencia', 'Moderada', 'hipertensos', 'SobrePeso'),
('Viernes', 'Flexiones Con Pica', 'Resistencia', 'Moderada', 'hipertensos', 'SobrePeso'),
('Sabado', 'Abdominales En V', 'Fortalecimiento', 'Moderada', 'hipertensos', 'SobrePeso'),
('Sabado', 'Burpees Con Salto', 'Fortalecimiento', 'Baja', 'hipertensos', 'SobrePeso'),
('Sabado', 'Estiramiento De Cuádriceps', 'Flexibilidad', 'Alta', 'hipertensos', 'SobrePeso'),
('Sabado', 'Estiramiento De Trapecio', 'Flexibilidad', 'Alta', 'hipertensos', 'SobrePeso'),
('Domingo', 'Estiramiento De Gemelos', 'Flexibilidad', 'Alta', 'hipertensos', 'SobrePeso'),
('Domingo', 'Estiramiento De Pectorales', 'Flexibilidad', 'Alta', 'hipertensos', 'SobrePeso'),
('Domingo', 'Postura Del Guerrero I', 'Flexibilidad', 'Alta', 'hipertensos', 'SobrePeso'),
('Domingo', 'Equilibrio Con Movimiento De Brazos', 'Equilibrio', 'Alta', 'hipertensos', 'SobrePeso');

-- Insertar plan de ejercicios para hipertensos con IMC Obesidad Tipo I y II
INSERT INTO plans_exercises (Day, ExerciseName, ExerciseType, ExerciseIntensity, Disease, HealthClassification) VALUES
('Lunes', 'Saltos En Caja', 'Aeróbico', 'Moderada', 'hipertensos', 'Obesidad Tipo I y II'),
('Lunes', 'Abdominales Tipo Bicicleta', 'Aerobico', 'Moderada', 'hipertensos', 'Obesidad Tipo I y II'),
('Lunes', 'Sentadillas', 'Pierna', 'Baja', 'hipertensos', 'Obesidad Tipo I y II'),
('Lunes', 'Elevaciones Laterales Con Bandas Elásticas', 'Hombro', 'Baja', 'hipertensos', 'Obesidad Tipo I y II'),
('Martes', 'Elevación De Cadera Con Una Pierna', 'Espalda', 'Baja', 'hipertensos', 'Obesidad Tipo I y II'),
('Martes', 'Remo Con Bandas Elásticas En Banco Con Elevación De Cadera', 'Espalda', 'Baja', 'hipertensos', 'Obesidad Tipo I y II'),
('Martes', 'Extensión De Tríceps En Banco Con Bandas Elásticas Con Giro De Torso', 'Triceps', 'Baja', 'hipertensos', 'Obesidad Tipo I y II'),
('Martes', 'Extensión De Tríceps En Banco Con Bandas Elásticas Con Elevación De Cadera', 'Triceps', 'Baja', 'hipertensos', 'Obesidad Tipo I y II'),
('Miercoles', 'Flexiones Hindúes', 'Pecho', 'Baja', 'hipertensos', 'Obesidad Tipo I y II'),
('Miercoles', 'Flexiones Con Brazos Abiertos', 'Pecho', 'Baja', 'hipertensos', 'Obesidad Tipo I y II'),
('Miercoles', 'Extensión De Muñeca Con Bandas Elásticas Y Giro De Torso', 'Antebrazo', 'Moderada', 'hipertensos', 'Obesidad Tipo I y II'),
('Miercoles', 'Flexión De Muñeca Con Bandas Elásticas Con Rotación', 'Antebrazo', 'Moderada', 'hipertensos', 'Obesidad Tipo I y II'),
('Jueves', 'Abdominales De Doble Pierna', 'Abdominales', 'Baja', 'hipertensos', 'Obesidad Tipo I y II'),
('Jueves', 'Elevaciones De Talón Con Rebote Y Salto', 'Pantorrilla', 'Moderada', 'hipertensos', 'Obesidad Tipo I y II'),
('Jueves', 'Estiramiento De Cuádriceps', 'Flexibilidad', 'Baja', 'hipertensos', 'Obesidad Tipo I y II'),
('Jueves', 'Escaladores De Montaña', 'Resistencia', 'Moderada', 'hipertensos', 'Obesidad Tipo I y II'),
('Viernes', 'Sentadillas Búlgaras', 'Fuerza', 'Baja', 'hipertensos', 'Obesidad Tipo I y II'),
('Viernes', 'Elevación De Talones Con Una Pierna', 'Fortalecimiento', 'Moderada', 'hipertensos', 'Obesidad Tipo I y II'),
('Viernes', 'Equilibrio Con Banda Elástica Y Elevación De Pierna', 'Equilibrio', 'Baja', 'hipertensos', 'Obesidad Tipo I y II'),
('Viernes', 'Abdominales Tipo Bicicleta Con Bandas Elásticas', 'Anaerbico', 'Baja', 'hipertensos', 'Obesidad Tipo I y II'),
('Sabado', 'Estiramiento De La Parte Baja De La Espalda', 'Flexibilidad', 'Alta', 'hipertensos', 'Obesidad Tipo I y II'),
('Sabado', 'Equilibrio Con Elevación Frontal De Pierna', 'Equilibrio', 'Alta', 'hip ertensos', 'Obesidad Tipo I y II'),
('Sabado', 'Peso Muerto Con Mochila Cargada', 'Fuerza', 'Moderada', 'hipertensos', 'Obesidad Tipo I y II'),
('Sabado', 'Estiramiento De Hombros', 'Flexibilidad', 'Alta', 'hipertensos', 'Obesidad Tipo I y II'),
('Domingo', 'Estiramiento De Aductores', 'Flexibilidad', 'Alta', 'hipertensos', 'Obesidad Tipo I y II'),
('Domingo', 'Estiramiento De Cuádriceps', 'Flexibilidad', 'Alta', 'hipertensos', 'Obesidad Tipo I y II'),
('Domingo', 'Estiramiento De Cadera', 'Flexibilidad', 'Alta', 'hipertensos', 'Obesidad Tipo I y II'),
('Domingo', 'Equilibrio Sobre Una Superficie Inestable', 'Equilibrio', 'Alta', 'hipertensos', 'Obesidad Tipo I y II');

-- Insertar plan de ejercicios para hipertensos con IMC Obesidad Tipo III y IV
INSERT INTO plans_exercises (Day, ExerciseName, ExerciseType, ExerciseIntensity, Disease, HealthClassification) VALUES
('Lunes', 'Saltos En Caja', 'Aeróbico', 'Moderada', 'hipertensos', 'Obesidad Tipo III y IV'),
('Lunes', 'Abdominales Tipo Bicicleta', 'Aerobico', 'Moderada', 'hipertensos', 'Obesidad Tipo III y IV'),
('Lunes', 'Sentadillas', 'Pierna', 'Baja', 'hipertensos', 'Obesidad Tipo III y IV'),
('Lunes', 'Sentadillas Con Una Pierna En Banco', 'Pierna', 'Moderada', 'hipertensos', 'Obesidad Tipo III y IV'),
('Lunes', 'Elevaciones Laterales Con Bandas Elásticas', 'Hombro', 'Baja', 'hipertensos', 'Obesidad Tipo III y IV'),
('Martes', 'Elevación De Cadera Con Una Pierna', 'Espalda', 'Baja', 'hipertensos', 'Obesidad Tipo III y IV'),
('Martes', 'Remo Con Bandas Elásticas En Banco Con Elevación De Cadera', 'Espalda', 'Baja', 'hipertensos', 'Obesidad Tipo III y IV'),
('Martes', 'Extensión De Tríceps En Banco Con Bandas Elásticas Con Giro De Torso', 'Triceps', 'Baja', 'hipertensos', 'Obesidad Tipo III y IV'),
('Martes', 'Extensión De Tríceps En Banco Con Bandas Elásticas Con Elevación De Cadera', 'Triceps', 'Baja', 'hipertensos', 'Obesidad Tipo III y IV'),
('Miercoles', 'Flexiones Hindúes', 'Pecho', 'Baja', 'hipertensos', 'Obesidad Tipo III y IV'),
('Miercoles', 'Flexiones Con Brazos Abiertos', 'Pecho', 'Baja', 'hipertensos', 'Obesidad Tipo III y IV'),
('Miercoles', 'Sentadillas Tipo Box', 'Pecho', 'Moderada', 'hipertensos', 'Obesidad Tipo III y IV'),
('Miercoles', 'Extensión De Muñeca Con Bandas Elásticas Y Giro De Torso', 'Antebrazo', 'Moderada', 'hipertensos', 'Obesidad Tipo III y IV'),
('Miercoles', 'Flexión De Muñeca Con Bandas Elásticas Con Rotación', 'Antebrazo', 'Moderada', 'hipertensos', 'Obesidad Tipo III y IV'),
('Jueves', 'Abdominales De Doble Pierna', 'Abdominales', 'Baja', 'hipertensos', 'Obesidad Tipo III y IV'),
('Jueves', 'Elevaciones De Talón Con Rebote Y Salto', 'Pantorrilla', 'Moderada', 'hipertensos', 'Obesidad Tipo III y IV'),
('Jueves', 'Estiramiento De Cuádriceps', 'Flexibilidad', 'Baja', 'hipertensos', 'Obesidad Tipo III y IV'),
('Jueves', 'Escaladores De Montaña', 'Resistencia', 'Moderada', 'hipertensos', 'Obesidad Tipo III y IV'),
('Viernes', 'Sentadillas Búlgaras', 'Fuerza', 'Baja', 'hipertensos', 'Obesidad Tipo III y IV'),
('Viernes', 'Elevación De Talones Con Una Pierna', 'Fortalecimiento', 'Moderada', 'hipertensos', 'Obesidad Tipo III y IV'),
('Viernes', 'Equilibrio Con Banda Elástica Y Elevación De Pierna', 'Baja', 'hipertensos', 'Obesidad Tipo III y IV'),
('Viernes', 'Abdominales Tipo Bicicleta Con Bandas Elásticas', 'Anaerbico', 'Baja', 'hipertensos', 'Obesidad Tipo III y IV'),
('Viernes', 'Peso Muerto Con Bandas Elásticas', 'Anaerbico', 'Baja', 'hipertensos', 'Obesidad Tipo III y IV'),
('Sabado', 'Estiramiento De La Parte Baja De La Espalda', 'Flexibilidad', 'Alta', 'hipertensos', 'Obesidad Tipo III y IV'),
('Sabado', 'Equilibrio Con Elevación Frontal De Pierna', 'Alta', 'hipertensos', 'Obesidad Tipo III y IV'),
('Sabado', 'Peso Muerto Con Mochila Cargada', 'Moderada', 'hipertensos', 'Obesidad Tipo III y IV'),
('Sabado', 'Estiramiento De Hombros', 'Alta', 'hipertensos', 'Obesidad Tipo III y IV'),
('Domingo', 'Estiramiento De Aductores', 'Alta', 'hipertensos', 'Obesidad Tipo III y IV'),
('Domingo', 'Estiramiento De Cuádriceps', 'Alta', 'hipertensos', 'Obesidad Tipo III y IV'),
('Domingo', 'Estiramiento De Cadera', 'Alta', 'hipertensos', 'Obesidad Tipo III y IV'),
('Domingo', 'Equilibrio Sobre Una Superficie Inestable', 'Alta', 'hipertensos', 'Obesidad Tipo III y IV');

-- Insertar plan de ejercicios para hipertensos con IMC Obesidad Tipo I y II
INSERT INTO plans_exercises (Day, ExerciseName, ExerciseType, ExerciseIntensity, Disease, HealthClassification) VALUES
('Lunes', 'Saltos En Caja', 'Aeróbico', 'Moderada', 'hipertensos', 'Obesidad Tipo I y II'),
('Lunes', 'Abdominales Tipo Bicicleta', 'Aerobico', 'Moderada', 'hipertensos', 'Obesidad Tipo I y II'),
('Lunes', 'Sentadillas', 'Pierna', 'Baja', 'hipertensos', 'Obesidad Tipo I y II'),
('Lunes', 'Elevaciones Laterales Con Bandas Elásticas', 'Hombro', 'Baja', 'hipertensos', 'Obesidad Tipo I y II'),
('Martes', 'Elevación De Cadera Con Una Pierna', 'Espalda', 'Baja', 'hipertensos', 'Obesidad Tipo I y II'),
('Martes', 'Remo Con Bandas Elásticas En Banco Con Elevación De Cadera', 'Espalda', 'Baja', 'hipertensos', 'Obesidad Tipo I y II'),
('Martes', 'Extensión De Tríceps En Banco Con Bandas Elásticas Con Giro De Torso', 'Triceps', 'Baja', 'hipertensos', 'Obesidad Tipo I y II'),
('Martes', 'Extensión De Tríceps En Banco Con Bandas Elásticas Con Elevación De Cadera', 'Triceps', 'Baja', 'hipertensos', 'Obesidad Tipo I y II'),
('Miercoles', 'Flexiones Hindúes', 'Pecho', 'Baja', 'hipertensos', 'Obesidad Tipo I y II'),
('Miercoles', 'Flexiones Con Brazos Abiertos', 'Pecho', 'Baja', 'hipertensos', 'Obesidad Tipo I y II'),
('Miercoles', 'Extensión De Muñeca Con Bandas Elásticas Y Giro De Torso', 'Antebrazo', 'Moderada', 'hipertensos', 'Obesidad Tipo I y II'),
('Miercoles', 'Flexión De Muñeca Con Bandas Elásticas Con Rotación', 'Antebrazo', 'Moderada', 'hipertensos', 'Obesidad Tipo I y II'),
('Jueves', 'Abdominales De Doble Pierna', 'Abdominales', 'Baja', 'hipertensos', 'Obesidad Tipo I y II'),
('Jueves', 'Elevaciones De Talón Con Rebote Y Salto', 'Pantorrilla', 'Moderada', 'hipertensos', 'Obesidad Tipo I y II'),
('Jueves', 'Estiramiento De Cuádriceps', 'Flexibilidad', 'Baja', 'hipertensos', 'Obesidad Tipo I y II'),
('Jueves', 'Escaladores De Montaña', 'Resistencia', 'Moderada', 'hipertensos', 'Obesidad Tipo I y II'),
('Viernes', 'Sentadillas Búlgaras', 'Fuerza', 'Baja', 'hipertensos', 'Obesidad Tipo I y II'),
('Viernes', 'Elevación De Talones Con Una Pierna', 'Fortalecimiento', 'Moderada', 'hipertensos', 'Obesidad Tipo I y II'),
('Viernes', 'Equilibrio Con Banda Elástica Y Elevación De Pierna', 'Equilibrio', 'Baja', 'hipertensos', 'Obesidad Tipo I y II'),
('Viernes', 'Abdominales Tipo Bicicleta Con Bandas Elásticas', 'Anaerbico', 'Baja', 'hipertensos', 'Obesidad Tipo I y II'),
('Sabado', 'Estiramiento De La Parte Baja De La Espalda', 'Flexibilidad', 'Alta', 'hipertensos', 'Obesidad Tipo I y II'),
('Sabado', 'Equilibrio Con Elevación Frontal De Pierna', 'Equilibrio', 'Alta', 'hipertensos', 'Obesidad Tipo I y II'),
('Sabado', 'Peso Muerto Con Mochila Cargada', 'Fuerza', 'Moderada', 'hipertensos', 'Obesidad Tipo I y II'),
('Sabado', 'Estiramiento De Hombros', 'Flexibilidad', 'Alta', 'hipertensos', 'Obesidad Tipo I y II'),
('Domingo', 'Estiramiento De Aductores', 'Flexibilidad', 'Alta', 'hipertensos', 'Obesidad Tipo I y II'),
('Domingo', 'Estiramiento De Cuádriceps', 'Flexibilidad', 'Alta', 'hipertensos', 'Obesidad Tipo I y II'),
('Domingo', 'Estiramiento De Cadera', 'Flexibilidad', 'Alta', 'hipertensos', 'Obesidad Tipo I y II'),
('Domingo', 'Equilibrio Sobre Una Superficie Inestable', 'Equilibrio', 'Alta', 'hipertensos', 'Obesidad Tipo I y II');

-- Insertar plan de ejercicios para hipertensos con IMC Obesidad Tipo III y IV
INSERT INTO plans_exercises (Day, ExerciseName, ExerciseType, ExerciseIntensity, Disease, HealthClassification) VALUES
('Lunes', 'Saltos En Caja', 'Aeróbico', 'Moderada', 'hipertensos', 'Obesidad Tipo III y IV'),
('Lunes', 'Abdominales Tipo Bicicleta', 'Aerobico', 'Moderada', 'hipertensos', 'Obesidad Tipo III y IV'),
('Lunes', 'Sentadillas', 'Pierna', 'Baja', 'hipertensos', 'Obesidad Tipo III y IV'),
('Lunes', 'Sentadillas Con Una Pierna En Banco', 'Pierna', 'Moderada', 'hipertensos', 'Obesidad Tipo III y IV'),
('Lunes', 'Elevaciones Laterales Con Bandas Elásticas', 'Hombro', 'Baja', 'hipertensos', 'Obesidad Tipo III y IV'),
('Martes', 'Elevación De Cadera Con Una Pierna', 'Espalda', 'Baja', 'hipertensos', 'Obesidad Tipo III y IV'),
('Martes', 'Remo Con Bandas Elásticas En Banco Con Elevación De Cadera', 'Espalda', 'Baja', 'hipertensos', 'Obesidad Tipo III y IV'),
('Martes', 'Extensión De Tríceps En Banco Con Bandas Elásticas Con Giro De Torso', 'Triceps', 'Baja', 'hipertensos', 'Obesidad Tipo III y IV'),
('Martes', 'Extensión De Tríceps En Banco Con Bandas Elásticas Con Elevación De Cadera', 'Triceps', 'Baja', 'hipertensos', 'Obesidad Tipo III y IV'),
('Miercoles', 'Flexiones Hindúes', 'Pecho', 'Baja', 'hipertensos', 'Obesidad Tipo III y IV'),
('Miercoles', 'Flexiones Con Brazos Abiertos', 'Pecho', 'Baja', 'hipertensos', 'Obesidad Tipo III y IV'),
('Miercoles', 'Sentadillas Tipo Box', 'Pecho', 'Moderada', 'hipertensos', 'Obesidad Tipo III y IV'),
('Miercoles', 'Extensión De Muñeca Con Bandas Elásticas Y Giro De Torso', 'Antebrazo', 'Moderada', 'hipertensos', 'Obesidad Tipo III y IV'),
('Miercoles', 'Flexión De Muñeca Con Bandas Elásticas Con Rotación', 'Antebrazo', 'Moderada', 'hipertensos', 'Obesidad Tipo III y IV'),
('Jueves', 'Abdominales De Doble Pierna', 'Abdominales', 'Baja', 'hipertensos', 'Obesidad Tipo III y IV'),
('Jueves', 'Elevaciones De Talón Con Rebote Y Salto', 'Pantorrilla', 'Moderada', 'hipertensos', 'Obesidad Tipo III y IV'),
('Jueves', 'Estiramiento De Cuádriceps', 'Flexibilidad', 'Baja', 'hipertensos', 'Obesidad Tipo III y IV'),
('Jueves', 'Escaladores De Montaña', 'Resistencia', 'Moderada', 'hipertensos', 'Obesidad Tipo III y IV'),
('Viernes', 'Sentadillas Búlgaras', 'Fuerza', 'Baja', 'hipertensos', 'Obesidad Tipo III y IV'),
('Viernes', 'Elevación De Talones Con Una Pierna', 'Fortalecimiento', 'Moderada', 'hipertensos', 'Obesidad Tipo III y IV'),
('Viernes', 'Equilibrio Con Banda Elástica Y Elevación De Pierna', 'Baja', 'hipertensos', 'Obesidad Tipo III y IV'),
('Viernes', 'Abdominales Tipo Bicicleta Con Bandas Elásticas', 'Anaerbico', 'Baja', 'hipertensos', 'Obesidad Tipo III y IV'),
('Viernes', 'Peso Muerto Con Bandas Elásticas', 'Anaerbico', 'Baja', 'hipertensos', 'Obesidad Tipo III y IV'),
('Sabado', 'Estiramiento De La Parte Baja De La Espalda', 'Flexibilidad', 'Alta', 'hipertensos', 'Obesidad Tipo III y IV'),
('Sabado', 'Equilibrio Con Elevación Frontal De Pierna', 'Alta', 'hipertensos', 'Obesidad Tipo III y IV'),
('Sabado', 'Peso Muerto Con Mochila Cargada', 'Moderada', 'hipertensos', 'Obesidad Tipo III y IV'),
('Sabado', 'Estiramiento De Hombros', 'Alta', 'hipertensos', 'Obesidad Tipo III y IV'),
('Domingo', 'Estiramiento De Aductores', 'Alta', 'hipertensos', 'Obesidad Tipo III y IV'),
('Domingo', 'Estiramiento De Cuádriceps', 'Alta', 'hipertensos', 'Obesidad Tipo III y IV'),
('Domingo', 'Estiramiento De Cadera', 'Alta', 'hipertensos', 'Obesidad Tipo III y IV'),
('Domingo', 'Equilibrio Sobre Una Superficie Inestable', 'Alta', 'hipertensos', 'Obesidad Tipo III y IV');

-- Insertar plan de ejercicios para un Diabético Tipo 1 con IMC bajo de peso
INSERT INTO plans_exercises (Day, ExerciseName, ExerciseType, ExerciseIntensity, Disease, HealthClassification) VALUES
('Lunes', 'Saltos En Cuclillas', 'Aerobicos', 'Alta', 'diabetico tipo 1', 'BajoDePeso'),
('Lunes', 'Saltos Con Patada Trasera', 'Aerobicos', 'Alta', 'diabetico tipo 1', 'BajoDePeso'),
('Lunes', 'Sentadilla Con Salto Y Elevacion', 'Aerobicos', 'Moderada', 'diabetico tipo 1', 'BajoDePeso'),
('Lunes', 'Sentadillas Con Mancuernas Y Salto', 'Pierna', 'Baja', 'diabetico tipo 1', 'BajoDePeso'),
('Lunes', 'Puentes De Glúteos Con Mancuernas', 'Pierna', 'Baja', 'diabetico tipo 1', 'BajoDePeso'),
('Lunes', 'Elevaciones De Cadera Con Mancuernas', 'Pierna', 'Baja', 'diabetico tipo 1', 'BajoDePeso'),
('Lunes', 'Elevaciones Laterales', 'Hombro', 'Moderada', 'diabetico tipo 1', 'BajoDePeso'),
('Lunes', 'Press De Hombros Con Mancuernas', 'Hombro', 'Moderada', 'diabetico tipo 1', 'BajoDePeso'),
('Lunes', 'Prensa De Hombro Con Bandas Elásticas Y Salto', 'Hombro', 'Moderada', 'diabetico tipo 1', 'BajoDePeso'),
('Martes', 'Planchas Laterales Con Elevación De Pierna', 'Espalda', 'Baja', 'diabetico tipo 1', 'BajoDePeso'),
('Martes', 'Remo Con Bandas Elásticas Y Elevación De Cadera', 'Espalda', 'Moderada', 'diabetico tipo 1', 'BajoDePeso'),
('Martes', 'Pull-aparts Con Bandas Elásticas En Banco', 'Espalda', 'Moderada', 'diabetico tipo 1', 'BajoDePeso'),
('Martes', 'Flexiones Con Peso En Espalda', 'Triceps', 'Baja', 'diabetico tipo 1', 'BajoDePeso'),
('Martes', 'Fondos Con Rotación', 'Triceps', 'Baja', 'diabetico tipo 1', 'BajoDePeso'),
('Martes', 'Extensión De Tríceps En Posición De Flexión', 'Triceps', 'Baja', 'diabetico tipo 1', 'BajoDePeso'),
('Martes', 'Remo Unilateral Con Mancuernas', 'Anaerobicos', 'Baja', 'diabetico tipo 1', 'BajoDePeso'),
('Martes', 'Flexiones De Bíceps Alternadas Con Mancuernas', 'Anaerobicos', 'Moderada', 'diabetico tipo 1', 'BajoDePeso'),
('Martes', 'Abdominales Tipo Bicicleta Con Bandas Elásticas', 'Anaerobicos', 'Baja', 'diabetico tipo 1', 'BajoDePeso'),
('Miercoles', 'Aperturas De Pecho Con Mancuernas', 'Pecho', 'Baja', 'diabetico tipo 1', 'BajoDePeso'),
('Miercoles', 'Flexiones De Pecho Con Bandas Elásticas', 'Pecho', 'Baja', 'diabetico tipo 1', 'BajoDePeso'),
('Miercoles', 'Prensa De Pecho En Banco Inclinado Con Mancuernas', 'Pecho', 'Baja', 'diabetico tipo 1', 'BajoDePeso'),
('Miercoles', 'Extensión De Tríceps Sobre La Cabeza Con Bandas Elásticas', 'Biceps', 'Moderada', 'diabetico tipo 1', 'BajoDePeso'),
('Miercoles', 'Extensión De Tríceps Con Bandas Elásticas Y Giro De Torso', 'Biceps', 'Baja', 'diabetico tipo 1', 'BajoDePeso'),
('Miercoles', 'Extensión De Tríceps Con Mancuernas', 'Biceps', 'Baja', 'diabetico tipo 1', 'BajoDePeso'),
('Miercoles', 'Curl De Muñeca Con Mancuernas', 'Antebrazos', 'Baja', 'diabetico tipo 1', 'BajoDePeso'),
('Miercoles', 'Flexión De Muñeca Con Bandas Elásticas Con Elevación De Cadera', 'Antebrazos', 'Moderada', 'diabetico tipo 1', 'BajoDePeso'),
('Miercoles', 'Flexiones Con Toque De Codo', 'Antebrazos', 'Moderada', 'diabetico tipo 1', 'BajoDePeso'),
('Jueves', 'Abdominales Tipo Puente', 'Abdominales', 'Baja', 'diabetico tipo 1', 'BajoDePeso'),
('Jueves', 'Escaladores De Montaña', 'Abdominales', 'Moderada', 'diabetico tipo 1', 'BajoDePeso'),
('Jueves', 'Abdominales Laterales', 'Abdominales', 'Moderada', 'diabetico tipo 1', 'BajoDePeso'),
('Jueves', 'Elevaciones De Talón En Banco Con Toque De Cadera Y Salto', 'Pantorrilla', 'Alta', 'diabetico tipo 1', 'BajoDePeso'),
('Jueves', 'Elevaciones De Talón En Banco Con Una Pierna Y Rebote', 'Pantorrilla', 'Alta', 'diabetico tipo 1', 'BajoDePeso'),
('Jueves', 'Postura Del Árbol', 'Flexibilidad', 'Alta', 'diabetico tipo 1', 'BajoDePeso'),
('Jueves', 'Estiramiento De Cuádriceps', 'Flexibilidad', 'Alta', 'diabetico tipo 1', 'BajoDePeso'),
('Jueves', 'Equilibrio En T', 'Equilibrio', 'Alta', 'diabetico tipo 1', 'BajoDePeso'),
('Jueves', 'Equilibrio Con Extensión De Brazos Y Piernas', 'Equilibrio', 'Alta', 'diabetico tipo 1', 'BajoDePeso'),
('Viernes', 'Estocadas Con Salto', 'Fuerza', 'Baja', 'diabetico tipo 1', 'BajoDePeso'),
('Viernes', 'Estocadas Con Mochila Cargada', 'Fuerza', 'Baja', 'diabetico tipo 1', 'BajoDePeso'),
('Viernes', 'Flexiones Declinadas', 'Resistencia', 'Baja', 'diabetico tipo 1', 'BajoDePeso'),
('Viernes', 'Escaladores De Montaña Con Giro', 'Resistencia', 'Baja', 'diabetico tipo 1', 'BajoDePeso'),
('Viernes', 'Saltos Laterales', 'Fortalecimiento', 'Moderada', 'diabetico tipo 1', 'BajoDePeso'),
('Viernes', 'Plancha Con Elevación De Pierna', 'Fortalecimiento', 'Moderada', 'diabetico tipo 1', 'BajoDePeso'),
('Viernes', 'Plancha Con Elevación De Cadera', 'Fortalecimiento', 'Moderada', 'diabetico tipo 1', 'BajoDePeso'),
('Viernes', 'Abdominales Laterales Con Bandas Elásticas', 'Anaerobico', 'Alta', 'diabetico tipo 1', 'BajoDePeso'),
('Viernes', 'Abdominales Tipo Bicicleta Con Bandas Elásticas', 'Anaerobico', 'Alta', 'diabetico tipo 1', 'BajoDePeso'),
('Sabado', 'Equilibrio A Una Pierna', 'Equilibrio', 'Alta', 'diabetico tipo 1', 'BajoDePeso'),
('Sabado', 'Equilibrio Con Pierna Cruzada', 'Equilibrio', 'Alta', 'diabetico tipo 1', 'BajoDePeso'),
('Sabado', 'Estiramiento De Hombros', 'Flexibilidad', 'Alta', 'diabetico tipo 1', 'BajoDePeso'),
('Sabado', 'Estiramiento De Antebrazos', 'Flexibilidad', 'Alta', 'diabetico tipo 1', 'BajoDePeso'),
('Domingo', 'Postura Del Perro Mirando Hacia Abajo', 'Flexibilidad', 'Alta', 'diabetico tipo 1', 'BajoDePeso'),
('Domingo', 'Postura Del Niño', 'Flexibilidad', 'Alta', 'diabetico tipo 1', 'BajoDePeso'),
('Domingo', 'Equilibrio Con Bandas Y Elevación De Piernas', 'Equilibrio', 'Alta', 'diabetico tipo 1', 'BajoDePeso'),
('Domingo', 'Salto Y Equilibrio A Una Pierna', 'Equilibrio', 'Alta', 'diabetico tipo 1', 'BajoDePeso'),
('Domingo', 'Equilibrio Con Banda Elástica', 'Equilibrio', 'Alta', 'diabetico tipo 1', 'BajoDePeso');

-- Insertar plan de ejercicios para un Diabético Tipo 1 con IMC sobrepeso
INSERT INTO plans_exercises (Day, ExerciseName, ExerciseType, ExerciseIntensity, Disease, HealthClassification) VALUES
('Lunes', 'Sentadillas Con Peso Corporal', 'Pierna', 'Moderada', 'diabetico tipo 1', 'SobrePeso'),
('Lunes', 'Estocadas', 'Pierna', 'Alta', 'diabetico tipo 1', 'SobrePeso'),
('Lunes', 'Peso Muerto Con Piernas Rectas', 'Pierna', 'Baja', 'diabetico tipo 1', 'SobrePeso'),
('Lunes', 'Prensa De Hombro Con Bandas Elásticas Con Elevación De Pie', 'Hombro', 'Baja', 'diabetico tipo 1', 'SobrePeso'),
('Lunes', 'Prensa De Hombro Con Bandas Elásticas Y Elevación De Pie', 'Hombro', 'Baja', 'diabetico tipo 1', 'SobrePeso'),
('Lunes', 'Jumping Jacks En Rotación', 'Aerobico', 'Moderada', 'diabetico tipo 1', 'SobrePeso'),
('Lunes', 'Lunge Con Salto Y Toque De Suelo', 'Aerobico', 'Moderada', 'diabetico tipo 1', 'SobrePeso'),
('Lunes', 'Planchas Con Salto Y Patadas Laterales', 'Aerobico', 'Moderada', 'diabetico tipo 1', 'SobrePeso'),
('Martes', 'Remo Con Mancuernas', 'Espalda', 'Moderada', 'diabetico tipo 1', 'SobrePeso'),
('Martes', 'Pull-downs con banda de resistencia', 'Espalda', 'Moderada', 'diabetico tipo 1', 'SobrePeso'),
('Martes', 'Chin-ups En Barra Casera', 'Espalda', 'Moderada', 'diabetico tipo 1', 'SobrePeso'),
('Martes', 'Fondos en banco', 'Triceps', 'Alta', 'diabetico tipo 1', 'SobrePeso'),
('Martes', 'Extensiones de tríceps', 'Triceps', 'Moderada', 'diabetico tipo 1', 'SobrePeso'),
('Martes', 'Extensión De Tríceps En Banco Inclinado', 'Triceps', 'Baja', 'diabetico tipo 1', 'SobrePeso'),
('Martes', 'Planchas Con Bandas Elásticas', 'Anerobicos', 'Moderada', 'diabetico tipo 1', 'SobrePeso'),
('Martes', 'Elevaciones De Talón Con Mancuernas En Banco', 'Anerobicos', 'Moderada', 'diabetico tipo 1', 'SobrePeso'),
('Miercoles', 'Flexiones De Pecho', 'Pecho', 'Moderada', 'diabetico tipo 1', 'SobrePeso'),
('Miercoles', 'Press De Pecho Con Mancuernas', 'Pecho', 'Moderada', 'diabetico tipo 1', 'SobrePeso'),
('Miercoles', 'Flexiones Con Brazos Abiertos', 'Pecho', 'Moderada', 'diabetico tipo 1', 'SobrePeso'),
('Miercoles', 'Curl De bíceps Con Mancuernas', 'Biceps', 'Baja', 'diabetico tipo 1', 'SobrePeso'),
('Miercoles', 'Curl De Martillo', 'Biceps', 'Baja', 'diabetico tipo 1', 'SobrePeso'),
('Miercoles', 'Curl De Bíceps Con Bandas Elásticas Cruzadas', 'Biceps', ' Baja', 'diabetico tipo 1', 'SobrePeso'),
('Miercoles', 'Flexiones De Muñeca', 'Antebrazo', 'Alta', 'diabetico tipo 1', 'SobrePeso'),
('Miercoles', 'Extensiones De Muñeca', 'Antebrazo', 'Alta', 'diabetico tipo 1', 'SobrePeso'),
('Jueves', 'Crunches', 'Abdominales', 'Moderada', 'diabetico tipo 1', 'SobrePeso'),
('Jueves', 'Abdominales Tipo Bicicleta', 'Abdominales', 'Moderada', 'diabetico tipo 1', 'SobrePeso'),
('Jueves', 'Plancha', 'Abdominales', 'Moderada', 'diabetico tipo 1', 'SobrePeso'),
('Jueves', 'Elevaciones De Talón', 'Pantorrilla', 'Alta', 'diabetico tipo 1', 'SobrePeso'),
('Jueves', 'Elevaciones De Talón En Banco Con Salto', 'Pantorrilla', 'Alta', 'diabetico tipo 1', 'SobrePeso'),
('Jueves', 'Flexiones De Puente', 'Resistencia', 'Baja', 'diabetico tipo 1', 'SobrePeso'),
('Jueves', 'Flexiones Con Codos Cerrados', 'Resistencia', 'Baja', 'diabetico tipo 1', 'SobrePeso'),
('Jueves', 'Estiramientos De Cuerpo Completo', 'Flexibilidad', 'Alta', 'diabetico tipo 1', 'SobrePeso'),
('Viernes', 'Sentadillas De Sumo', 'Fuerza', 'Baja', 'diabetico tipo 1', 'SobrePeso'),
('Viernes', 'Flexiones De Pecho Con Bandas Elásticas', 'Fuerza', 'Baja', 'diabetico tipo 1', 'SobrePeso'),
('Viernes', 'Prensa De Hombros Con Bandas Elásticas', 'Fuerza', 'Baja', 'diabetico tipo 1', 'SobrePeso'),
('Viernes', 'Plancha', 'Fortalecimiento', 'Moderada', 'diabetico tipo 1', 'SobrePeso'),
('Viernes', 'Bird-Dog', 'Fortalecimiento', 'Moderada', 'diabetico tipo 1', 'SobrePeso'),
('Viernes', 'Estocadas Con Salto', 'Anaerobicos', 'Baja', 'diabetico tipo 1', 'SobrePeso'),
('Viernes', 'Patadas Frontales', 'Anaerobicos', 'Baja', 'diabetico tipo 1', 'SobrePeso'),
('Viernes', 'Elevaciones Laterales Con Bandas Elásticas', 'Anaerobicos', 'Baja', 'diabetico tipo 1', 'SobrePeso'),
('Sabado', 'Postura Del Arbol', 'Equilibrio', 'Alta', 'diabetico tipo 1', 'SobrePeso'),
('Sabado', 'Elevación De Una Pierna', 'Equilibrio', 'Alta', 'diabetico tipo 1', 'SobrePeso'),
('Sabado', 'Estiramientos De Espalda', 'Flexibilidad', 'Alta', 'diabetico tipo 1', 'SobrePeso'),
('Sabado', 'Estiramientos De Hombros Y Cuello', 'Flexibilidad', 'Alta', 'diabetico tipo 1', 'SobrePeso'),
('Domingo', 'Estiramientos De Cuádriceps', 'Flexibilidad', 'Alta', 'diabetico tipo 1', 'SobrePeso'),
('Domingo', 'Estiramientos De Isquiotibiales', 'Flexibilidad', 'Alta', 'diabetico tipo 1', 'SobrePeso'),
('Domingo', 'Estiramientos De Pantorrillas', 'Flexibilidad', 'Alta', 'diabetico tipo 1', 'SobrePeso'),
('Domingo', 'Sesión de yoga suave', 'Flexibilidad', 'Alta', 'diabetico tipo 1', 'SobrePeso');

-- Insertar plan de ejercicios para un Diabético Tipo 1 con IMC Obesidad Tipo I y II
INSERT INTO plans_exercises (Day, ExerciseName, ExerciseType, ExerciseIntensity, Disease, HealthClassification) VALUES
('Lunes', 'Sentadillas', 'Pierna', 'Moderada', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Lunes', 'Puente De Glúteos', 'Pierna', 'Moderada', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Lunes', 'Zancadas', 'Pierna', 'Moderada', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Lunes', 'Elevaciones Laterales', 'Hombro', 'Alta', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Lunes', 'Press De Hombros Con Mancuernas', 'Hombro', 'Moderada', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Lunes', 'Trote Suave', 'Aerobico', 'Moderada', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Martes', 'Remo Con Mancuernas', 'Espalda', 'Moderada', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Martes', 'Superman', 'Espalda', 'Alta', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Martes', 'Fondos De Tríceps En Banco', 'Triceps', 'Moderada', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Martes', 'Extensión De Tríceps Con Mancuernas', 'Triceps', 'Baja', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Martes', 'Elevaciones Laterales Con Bandas Elásticas', 'Anaerobicos', 'Moderada', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Martes', 'Escaladores En El Suelo', 'Anaerobicos', 'Baja', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Miercoles', 'Flexiones De Brazo', 'Pecho', 'Moderada', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Miercoles', 'Press De Banca Con Mancuernas', 'Pecho', 'Baja', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Miercoles', 'Flexión De Bíceps Con Bandas Elásticas Y Rotación De Torso', 'Biceps', 'Baja', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Miercoles', 'Flexión De Bíceps Con Bandas Elásticas Desde Banco Inclinado Con Giro De Torso', 'Biceps', 'Moderada', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Miercoles', 'Flexión De Muñeca Con Mancuernas', 'Antebrazo', 'Baja', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Miercoles', 'Flexiones Con Cuerpo Recto Con Elevación De Cadera', 'Antebrazo', 'Baja', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Jueves', 'Bicicletas', 'Abdominales', 'Alta', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Jueves', 'Russian Twists', 'Abdominales', 'Moderada', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Jueves', 'Mountain Climbers', 'Pantorrilla', 'Moderada', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Jueves', 'Elevaciones De Pantorrillas ', 'Pantorrilla', 'Alta', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Jueves', 'Burpees Con Salto Y Elevación De Rodillas', 'Resistencia', 'Moderada', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Jueves', 'Escaladores De Montaña Cruzados', 'Resistencia', 'Baja', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Viernes', 'Curl De Bíceps Con Mancuernas', 'Fuerza', 'Baja', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Viernes', 'Peso Muerto Con Mochila', 'Fuerza', 'Baja', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Viernes', 'Plancha Con Toque De Hombro', 'Fortalecimiento', 'Moderada', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Viernes', 'Abdominales Tipo Rana', 'Fortalecimiento', 'Moderada', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Viernes', 'Elevaciones Frontales Con Mancuernas', 'Anaerobico', 'Baja', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Viernes', 'Abdominales Laterales Con Bandas Elásticas', 'Anaerobico', 'Baja', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Sabado', 'Saltos De Tijera', 'Aerobico', 'Alta', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Sabado', 'Mountain Climbers', 'Aerobico', 'Alta', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Sabado', 'Elevación De Piernas En Plancha Con Pesas', 'Equilibrio', 'Alta', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Sabado', 'Equilibrio En T Con Mancuernas', 'Equilibrio', 'Alta', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Sabado', 'Yoga o Pilates', 'Flexibilidad', 'Alta', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Sabado', 'Postura Del Puente', 'Flexibilidad', 'Alta', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Domingo', 'Postura De La Silla', 'Flexibilidad', 'Alta', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Domingo', 'Postura Del Guerrero', 'Flexibilidad', 'Alta', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Domingo', 'Estiramiento De Aductores', 'Flexibilidad', 'Alta', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Domingo', 'Estiramiento De Cuádriceps', 'Flexibilidad', 'Alta', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Domingo', 'Estiramiento De Antebrazos', 'Flexibilidad', 'Alta', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Domingo', 'Estiramiento De Los Músculos Laterales Del Tronco', 'Flexibilidad', 'Alta', 'diabetico tipo 1', 'Obesidad Tipo I y II');

-- Insertar plan de ejercicios para un Diabético Tipo 1 con IMC Obesidad Tipo III y IV
INSERT INTO plans_exercises (Day, ExerciseName, ExerciseType, ExerciseIntensity, Disease, HealthClassification) VALUES
('Lunes', 'Sentadillas', 'Pierna', 'Moderada', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Lunes', 'Puente De Glúteos', 'Pierna', 'Moderada', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Lunes', 'Zancadas', 'Pierna', 'Moderada', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Lunes', 'Elevaciones Laterales', 'Hombro', 'Alta', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Lunes', 'Press De Hombros Con Mancuernas', 'Hombro', 'Moderada', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Lunes', 'Trote Suave', 'Aerobico', 'Moderada', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Martes', 'Remo Con Mancuernas', 'Espalda', 'Moderada', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Martes', 'Superman', 'Espalda', 'Alta', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Martes', 'Fondos De Tríceps En Banco', 'Triceps', 'Moderada', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Martes', 'Extensión De Tríceps Con Mancuernas', 'Triceps', 'Baja', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Martes', 'Elevaciones Laterales Con Bandas Elásticas', 'Anaerobicos', 'Moderada', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Martes', 'Escaladores En El Suelo', 'Anaerobicos', 'Baja', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Miercoles', 'Flexiones De Brazo', 'Pecho', 'Moderada', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Miercoles', 'Press De Banca Con Mancuernas', 'Pecho', 'Baja', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Miercoles', 'Flexión De Bíceps Con Bandas Elásticas Y Rotación De Torso', 'Biceps', 'Baja', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Miercoles', 'Flexión De Bíceps Con Bandas Elásticas Desde Banco Inclinado Con Giro De Torso', 'Biceps', 'Moderada', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Miercoles', 'Flexión De Muñeca Con Mancuernas', 'Antebrazo', 'Baja', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Miercoles', 'Flexiones Con Cuerpo Recto Con Elevación De Cadera', 'Antebrazo', 'Baja', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Jueves', 'Bicicletas', 'Abdominales', 'Alta', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Jueves', 'Russian Twists', 'Abdominales', 'Moderada', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Jueves', 'Mountain Climbers', 'Pantorrilla', 'Moderada', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Jueves', 'Elevaciones De Pantorrillas', 'Pantorrilla', 'Alta', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Jueves', 'Burpees Con Salto Y Elevación De Rodillas', 'Resistencia', 'Moderada', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Jueves', 'Escaladores De Montaña Cruzados', 'Resistencia', 'Baja', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Viernes', 'Curl De Bíceps Con Mancuernas', 'Fuerza', 'Baja', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Viernes', 'Peso Muerto Con Mochila', 'Fuerza', 'Baja', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Viernes', 'Plancha Con Toque De Hombro', 'Fortalecimiento', 'Moderada', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Viernes', 'Abdominales Tipo Rana', 'Fortalecimiento', 'Moderada', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Viernes', 'Elevaciones Frontales Con Mancuernas', 'Anaerobico', 'Baja', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Viernes', 'Abdominales Laterales Con Bandas Elásticas', 'Baja', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Sabado', 'Saltos De Tijera', 'Aerobico', 'Alta', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Sabado', 'Mountain Climbers', 'Aerobico', 'Alta', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Sabado', 'Elevación De Piernas En Plancha Con Pesas', 'Equilibrio', 'Alta', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Sabado', 'Equilibrio En T Con Mancuernas', 'Equilibrio', 'Alta', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Sabado', 'Yoga o Pilates', 'Flexibilidad', 'Alta', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Sabado', 'Postura Del Puente', 'Flexibilidad', 'Alta', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Domingo', 'Postura De La Silla', 'Flexibilidad', 'Alta', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Domingo', 'Postura Del Guerrero', 'Flexibilidad', 'Alta', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Domingo', 'Estiramiento De Aductores', 'Flexibilidad', 'Alta', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Domingo', 'Estiramiento De Cuádriceps', 'Flexibilidad', 'Alta', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Domingo', 'Estiramiento De Antebrazos', 'Flexibilidad', 'Alta', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Domingo', 'Estiramiento De Los Músculos Laterales Del Tronco', 'Flexibilidad', 'Alta', 'diabetico tipo 1', 'Obesidad Tipo III y IV');

-- Insertar plan de ejercicios para un Diabético Tipo 1 con IMC Obesidad Tipo I y II
INSERT INTO plans_exercises (Day, ExerciseName, ExerciseType, ExerciseIntensity, Disease, HealthClassification) VALUES
('Lunes', 'Sentadillas', 'Pierna', 'Moderada', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Lunes', 'Puente De Glúteos', 'Pierna', 'Moderada', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Lunes', 'Zancadas', 'Pierna', 'Moderada', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Lunes', 'Elevaciones Laterales', 'Hombro', 'Alta', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Lunes', 'Press De Hombros Con Mancuernas', 'Hombro', 'Moderada', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Lunes', 'Trote Suave', 'Aerobico', 'Moderada', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Martes', 'Remo Con Mancuernas', 'Espalda', 'Moderada', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Martes', 'Superman', 'Espalda', 'Alta', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Martes', 'Fondos De Tríceps En Banco', 'Triceps', 'Moderada', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Martes', 'Extensión De Tríceps Con Mancuernas', 'Triceps', 'Baja', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Martes', 'Elevaciones Laterales Con Bandas Elásticas', 'Anaerobicos', 'Moderada', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Martes', 'Escaladores En El Suelo', 'Anaerobicos', 'Baja', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Miercoles', 'Flexiones De Brazo', 'Pecho', 'Moderada', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Miercoles', 'Press De Banca Con Mancuernas', 'Pecho', 'Baja', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Miercoles', 'Flexión De Bíceps Con Bandas Elásticas Y Rotación De Torso', 'Biceps', 'Baja', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Miercoles', 'Flexión De Bíceps Con Bandas Elásticas Desde Banco Inclinado Con Giro De Torso', 'Biceps', 'Moderada', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Miercoles', 'Flexión De Muñeca Con Mancuernas', 'Antebrazo', 'Baja', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Miercoles', 'Flexiones Con Cuerpo Recto Con Elevación De Cadera', 'Antebrazo', 'Baja', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Jueves', 'Bicicletas', 'Abdominales', 'Alta', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Jueves', 'Russian Twists', 'Abdominales', 'Moderada', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Jueves', 'Mountain Climbers', 'Pantorrilla', 'Moderada', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Jueves', 'Elevaciones De Pantorrillas ', 'Pantorrilla', 'Alta', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Jueves', 'Burpees Con Salto Y Elevación De Rodillas', 'Resistencia', 'Moderada', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Jueves', 'Escaladores De Montaña Cruzados', 'Resistencia', 'Baja', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Viernes', 'Curl De Bíceps Con Mancuernas', 'Fuerza', 'Baja', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Viernes', 'Peso Muerto Con Mochila', 'Fuerza', 'Baja', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Viernes', 'Plancha Con Toque De Hombro', 'Fortalecimiento', 'Moderada', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Viernes', 'Abdominales Tipo Rana', 'Fortalecimiento', 'Moderada', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Viernes', 'Elevaciones Frontales Con Mancuernas', 'Anaerobico', 'Baja', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Viernes', 'Abdominales Laterales Con Bandas Elásticas', 'Anaerobico', 'Baja', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Sabado', 'Saltos De Tijera', 'Aerobico', 'Alta', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Sabado', 'Mountain Climbers', 'Aerobico', 'Alta', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Sabado', 'Elevación De Piernas En Plancha Con Pesas', 'Equilibrio', 'Alta', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Sabado', 'Equilibrio En T Con Mancuernas', 'Equilibrio', 'Alta', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Sabado', 'Yoga o Pilates', 'Flexibilidad', 'Alta', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Sabado', 'Postura Del Puente', 'Flexibilidad', 'Alta', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Domingo', 'Postura De La Silla', 'Flexibilidad', 'Alta', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Domingo', 'Postura Del Guerrero', 'Flexibilidad', 'Alta', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Domingo', 'Estiramiento De Aductores', 'Flexibilidad', 'Alta', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Domingo', 'Estiramiento De Cuádriceps', 'Flexibilidad', 'Alta', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Domingo', 'Estiramiento De Antebrazos', 'Flexibilidad', 'Alta', 'diabetico tipo 1', 'Obesidad Tipo I y II'),
('Domingo', 'Estiramiento De Los Músculos Laterales Del Tronco', 'Flexibilidad', 'Alta', 'diabetico tipo 1', 'Obesidad Tipo I y II');

-- Insertar plan de ejercicios para un Diabético Tipo 1 con IMC Obesidad Tipo III y IV
INSERT INTO plans_exercises (Day, ExerciseName, ExerciseType, ExerciseIntensity, Disease, HealthClassification) VALUES
('Lunes', 'Sentadillas', 'Pierna', 'Moderada', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Lunes', 'Puente De Glúteos', 'Pierna', 'Moderada', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Lunes', 'Zancadas', 'Pierna', 'Moderada', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Lunes', 'Elevaciones Laterales', 'Hombro', 'Alta', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Lunes', 'Press De Hombros Con Mancuernas', 'Hombro', 'Moderada', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Lunes', 'Trote Suave', 'Aerobico', 'Moderada', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Martes', 'Remo Con Mancuernas', 'Espalda', 'Moderada', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Martes', 'Superman', 'Espalda', 'Alta', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Martes', 'Fondos De Tríceps En Banco', 'Triceps', 'Moderada', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Martes', 'Extensión De Tríceps Con Mancuernas', 'Triceps', 'Baja', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Martes', 'Elevaciones Laterales Con Bandas Elásticas', 'Anaerobicos', 'Moderada', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Martes', 'Escaladores En El Suelo', 'Anaerobicos', 'Baja', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Miercoles', 'Flexiones De Brazo', 'Pecho', 'Moderada', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Miercoles', 'Press De Banca Con Mancuernas', 'Pecho', 'Baja', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Miercoles', 'Flexión De Bíceps Con Bandas Elásticas Y Rotación De Torso', 'Biceps', 'Baja', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Miercoles', 'Flexión De Bíceps Con Bandas Elásticas Desde Banco Inclinado Con Giro De Torso', 'Biceps', 'Moderada', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Miercoles', 'Flexión De Muñeca Con Mancuernas', 'Antebrazo', 'Baja', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Miercoles', 'Flexiones Con Cuerpo Recto Con Elevación De Cadera', 'Antebrazo', 'Baja', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Jueves', 'Bicicletas', 'Abdominales', 'Alta', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Jueves', 'Russian Twists', 'Abdominales', 'Moderada', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Jueves', 'Mountain Climbers', 'Pantorrilla', 'Moderada', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Jueves', 'Elevaciones De Pantorrillas', 'Pantorrilla', 'Alta', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Jueves', 'Burpees Con Salto Y Elevación De Rodillas', 'Resistencia', 'Moderada', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Jueves', 'Escaladores De Montaña Cruzados', 'Resistencia', 'Baja', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Viernes', 'Curl De Bíceps Con Mancuernas', 'Fuerza', 'Baja', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Viernes', 'Peso Muerto Con Mochila', 'Fuerza', 'Baja', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Viernes', 'Plancha Con Toque De Hombro', 'Fortalecimiento', 'Moderada', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Viernes', 'Abdominales Tipo Rana', 'Fortalecimiento', 'Moderada', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Viernes', 'Elevaciones Frontales Con Mancuernas', 'Anaerobico', 'Baja', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Viernes', 'Abdominales Laterales Con Bandas Elásticas', 'Baja', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Sabado', 'Saltos De Tijera', 'Aerobico', 'Alta', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Sabado', 'Mountain Climbers', 'Aerobico', 'Alta', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Sabado', 'Elevación De Piernas En Plancha Con Pesas', 'Equilibrio', 'Alta', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Sabado', 'Equilibrio En T Con Mancuernas', 'Equilibrio', 'Alta', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Sabado', 'Yoga o Pilates', 'Flexibilidad', 'Alta', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Sabado', 'Postura Del Puente', 'Flexibilidad', 'Alta', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Domingo', 'Postura De La Silla', 'Flexibilidad', 'Alta', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Domingo', 'Postura Del Guerrero', 'Flexibilidad', 'Alta', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Domingo', 'Estiramiento De Aductores', 'Flexibilidad', 'Alta', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Domingo', 'Estiramiento De Cuádriceps', 'Flexibilidad', 'Alta', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Domingo', 'Estiramiento De Antebrazos', 'Flexibilidad', 'Alta', 'diabetico tipo 1', 'Obesidad Tipo III y IV'),
('Domingo', 'Estiramiento De Los Músculos Laterales Del Tronco', 'Flexibilidad', 'Alta', 'diabetico tipo 1', 'Obesidad Tipo III y IV');

-- Insertar plan de ejercicios para un Diabético Tipo 2 con IMC bajo de peso
INSERT INTO plans_exercises (Day, ExerciseName, ExerciseType, ExerciseIntensity, Disease, HealthClassification) VALUES
('Lunes', 'Sentadillas', 'Piernas', 'Moderada', 'diabetico tipo 2', 'BajoDePeso'),
('Lunes', 'Puente De Glúteos', 'Pierna', 'Moderada', 'diabetico tipo 2', 'BajoDePeso'),
('Lunes', 'Zancadas', 'Pierna', 'Moderada', 'diabetico tipo 2', 'BajoDePeso'),
('Lunes', 'Elevaciones Laterales', 'Hombro', 'Alta', 'diabetico tipo 2', 'BajoDePeso'),
('Lunes', 'Press De Hombros Con Mancuernas', 'Hombro', 'Moderada', 'diabetico tipo 2', 'BajoDePeso'),
('Lunes', 'Trote Suave', 'Aerobico', 'Moderada', 'diabetico tipo 2', 'BajoDePeso'),
('Lunes', 'Estiramiento De Cuádriceps', 'Flexibilidad', 'Alta', 'diabetico tipo 2', 'BajoDePeso'),
('Lunes', 'Estiramiento De Antebrazos', 'Flexibilidad', 'Alta', 'diabetico tipo 2', 'BajoDePeso'),
('Martes', 'Saltos De Tijera', 'Aerobico', 'Alta', 'diabetico tipo 2', 'BajoDePeso'),
('Martes', 'Mountain Climbers', 'Aerobico', 'Alta', 'diabetico tipo 2', 'BajoDePeso'),
('Martes', 'Elevación De Piernas En Plancha Con Pesas', 'Equilibrio', 'Moderada', 'diabetico tipo 2', 'BajoDePeso'),
('Martes', 'Equilibrio En T Con Mancuernas', 'Equilibrio', 'Moderada', 'diabetico tipo 2', 'BajoDePeso'),
('Martes', 'Estiramiento De Antebrazos', 'Flexibilidad', 'Moderada', 'diabetico tipo 2', 'BajoDePeso'),
('Martes', 'Estiramiento De Los Músculos Laterales Del Tronco', 'Flexibilidad', 'Moderada', 'diabetico tipo 2', 'BajoDePeso'),
('Martes', 'Estiramiento De Aductores', 'Flexibilidad', 'Moderada', 'diabetico tipo 2', 'BajoDePeso'),
('Miercoles', 'Flexiones De Brazo', 'Pecho', 'Moderada', 'diabetico tipo 2', 'BajoDePeso'),
('Miercoles', 'Press De Banca Con Mancuernas', 'Pecho', 'Moderada', 'diabetico tipo 2', 'BajoDePeso'),
('Miercoles', 'Flexión De Bíceps Con Bandas Elásticas Y Rotación De Torso', 'Biceps', 'Moderada', 'diabetico tipo 2', 'BajoDePeso'),
('Miercoles', 'Flexión De Bíceps Con Bandas Elásticas Desde Banco Inclinado Con Giro De Torso', 'Biceps', 'Moderada', 'diabetico tipo 2', 'BajoDePeso'),
('Miercoles', 'Remo Con Mancuernas', 'Espalda', 'Alta', 'diabetico tipo 2', 'BajoDePeso'),
('Miercoles', 'Superman', 'Espalda', 'Alta', 'diabetico tipo 2', 'BajoDePeso'),
('Miercoles', 'Fondos De Tríceps En Banco', 'Triceps', 'Moderada', 'diabetico tipo 2', 'BajoDePeso'),
('Miercoles', 'Extensión De Tríceps Con Mancuernas', 'Triceps', 'Moderada', 'diabetico tipo 2', 'BajoDePeso'),
('Jueves', 'Abdominales Tradicionales', 'Abdominales', 'Moder ada', 'diabetico tipo 2', 'BajoDePeso'),
('Jueves', 'Abdominales Oblicuos', 'Abdominales', 'Baja', 'diabetico tipo 2', 'BajoDePeso'),
('Jueves', 'Plancha Tradicional', 'Abdominales', 'Moderada', 'diabetico tipo 2', 'BajoDePeso'),
('Jueves', 'Elevaciones De Talón Con Salto', 'Pantorrilla', 'Moderada', 'diabetico tipo 2', 'BajoDePeso'),
('Jueves', 'Elevaciones De Talón Alternadas', 'Pantorrilla', 'Moderada', 'diabetico tipo 2', 'BajoDePeso'),
('Jueves', 'Sentadillas Con Una Pierna', 'Anaerobico', 'Baja', 'diabetico tipo 2', 'BajoDePeso'),
('Jueves', 'Estocadas Laterales', 'Anaerobico', 'Moderada', 'diabetico tipo 2', 'BajoDePeso'),
('Jueves', 'Elevaciones De Pierna En Decúbito Supino', 'Anaerobico', 'Baja', 'diabetico tipo 2', 'BajoDePeso'),
('Viernes', 'Postura Del Árbol', 'Flexibilidad', 'Moderada', 'diabetico tipo 2', 'BajoDePeso'),
('Viernes', 'Estiramiento De Cuádriceps', 'Flexibilidad', 'Moderada', 'diabetico tipo 2', 'BajoDePeso'),
('Viernes', 'Equilibrio En T', 'Equilibrio', 'Moderada', 'diabetico tipo 2', 'BajoDePeso'),
('Viernes', 'Equilibrio Con Extensión De Brazos Y Piernas', 'Equilibrio', 'Moderada', 'diabetico tipo 2', 'BajoDePeso'),
('Viernes', 'Elevaciones Laterales Con Bandas Elásticas', 'Anaerobicos', 'Moderada', 'diabetico tipo 2', 'BajoDePeso'),
('Viernes', 'Escaladores En El Suelo', 'Anaerobicos', 'Moderada', 'diabetico tipo 2', 'BajoDePeso'),
('Viernes', 'Estiramiento de los isquiotibiales', 'Flexibilidad', 'Moderada', 'diabetico tipo 2', 'BajoDePeso'),
('Viernes', 'Estiramiento de los cuádriceps', 'Flexibilidad', 'Moderada', 'diabetico tipo 2', 'BajoDePeso'),
('Sabado', 'Salto En Tijeras', 'Aerobico', 'Alta', 'diabetico tipo 2', 'BajoDePeso'),
('Sabado', 'Trote Suave', 'Aerobico', 'Alta', 'diabetico tipo 2', 'BajoDePeso'),
('Sabado', 'Equilibrio Con Elevación De Rodilla', 'Equilibrio', 'Alta', 'diabetico tipo 2', 'BajoDePeso'),
('Sabado', 'Equilibrio Con Elevación De Brazos', 'Equilibrio', 'Alta', 'diabetico tipo 2', 'BajoDePeso'),
('Sabado', 'Equilibrio En Posición De Yoga', 'Equilibrio', 'Alta', 'diabetico tipo 2', 'BajoDePeso'),
('Domingo', 'Yoga', 'Flexibilidad', 'Moderada', 'diabetico tipo 2', 'BajoDePeso'),
('Domingo', 'Postura Del Camello', 'Flexibilidad', 'Moderada', 'diabetico tipo 2', 'BajoDePeso'),
('Domingo', 'Postura Del Triángulo', 'Flexibilidad', 'Moderada', 'diabetico tipo 2', 'BajoDePeso');

-- Insertar plan de ejercicios para un Diabético Tipo 2 con IMC sobrepeso
INSERT INTO plans_exercises (Day, ExerciseName, ExerciseType, ExerciseIntensity, Disease, HealthClassification) VALUES
('Lunes', 'Sentadillas', 'Piernas', 'Moderada', 'diabetico tipo 2', 'Sobrepeso'),
('Lunes', 'Puente De Glúteos', 'Piernas', 'Moderada', 'diabetico tipo 2', 'Sobrepeso'),
('Lunes', 'Estiramiento De Cuádriceps', 'Flexibilidad', 'Moderada', 'diabetico tipo 2', 'Sobrepeso'),
('Lunes', 'Postura Del Árbol', 'Flexibilidad', 'Moderada', 'diabetico tipo  2', 'Sobrepeso'),
('Lunes', 'Equilibrio Con Extensión De Brazos Y Piernas', 'Equilibrio', 'Moderada', 'diabetico tipo 2', 'Sobrepeso'),
('Lunes', 'Equilibrio En T', 'Equilibrio', 'Moderada', 'diabetico tipo 2', 'Sobrepeso'),
('Martes', 'Flexiones De Brazo', 'Pecho', 'Alta', 'diabetico tipo 2', 'Sobrepeso'),
('Martes', 'Press De Banca Con Mancuernas', 'Pecho', 'Alta', 'diabetico tipo 2', 'Sobrepeso'),
('Martes', 'Elevaciones Laterales', 'Hombro', 'Moderada', 'diabetico tipo 2', 'Sobrepeso'),
('Martes', 'Press De Hombros Con Mancuernas', 'Hombro', 'Moderada', 'diabetico tipo 2', 'Sobrepeso'),
('Martes', 'Flexiones De Muñeca', 'Antebrazo', 'Moderada', 'diabetico tipo 2', 'Sobrepeso'),
('Martes', 'Extensiones De Muñeca', 'Antebrazo', 'Moderada', 'diabetico tipo 2', 'Sobrepeso'),
('Miercoles', 'Superman', 'Espalda', 'Moderada', 'diabetico tipo 2', 'Sobrepeso'),
('Miercoles', 'Remo Con Mancuernas', 'Espalda', 'Moderada', 'diabetico tipo 2', 'Sobrepeso'),
('Miercoles', 'Flexión De Muñeca Con Mancuernas', 'Antebrazo', 'Moderada', 'diabetico tipo 2', 'Sobrepeso'),
('Miercoles', 'Flexiones Con Cuerpo Recto Con Elevación De Cadera', 'Antebrazo', 'Moderada', 'diabetico tipo 2', 'Sobrepeso'),
('Miercoles', 'Remo con barra', 'Fuerza', 'Moderada', 'diabetico tipo 2', 'Sobrepeso'),
('Miercoles', 'Elevaciones de pantorrillas', 'Fuerza', 'Moderada', 'diabetico tipo 2', 'Sobrepeso'),
('Jueves', 'Postura Del Árbol', 'Equilibrio', 'Moderada', 'diabetico tipo 2', 'Sobrepeso'),
('Jueves', 'Estiramiento De Cuádriceps', 'Flexibilidad', 'Moderada', 'diabetico tipo 2', 'Sobrepeso'),
('Jueves', 'Estiramiento de los isquiotibiales', 'Flexibilidad', 'Moderada', 'diabetico tipo 2', 'Sobrepeso'),
('Jueves', 'Estiramiento De Cuádriceps', 'Flexibilidad', 'Moderada', 'diabetico tipo 2', 'Sobrepeso'),
('Jueves', 'Caminar a paso ligero', 'Aeróbico', 'Moderada', 'diabetico tipo 2', 'Sobrepeso'),
('Jueves', 'Trotar En El Mismo Lugar', 'Aeróbico', 'Moderada', 'diabetico tipo 2', 'Sobrepeso'),
('Viernes', 'Estocadas Con Salto', 'Fortalecimiento', 'Moderada', 'diabetico tipo 2', 'Sobrepeso'),
('Viernes', 'Sentadillas Búlgaras', 'Fortalecimiento', 'Moderada', 'diabetico tipo 2', 'Sobrepeso'),
('Viernes', 'Fondos De Tríceps En Silla', 'Fuerza', 'Baja', 'diabetico tipo 2', 'Sobrepeso'),
('Viernes', 'Plancha Lateral', 'Fuerza', 'Moderada', 'diabetico tipo 2', 'Sobrepeso'),
('Viernes', 'Estiramiento Cuerpo Completo', 'Flexibilidad', 'Alta', 'diabetico tipo 2', 'Sobrepeso'),
('Sabado', 'Caminar a paso ligero', 'Aeróbico', 'Moderada', 'diabetico tipo 2', 'Sobrepeso'),
('Sabado', 'Trote Suave', 'Aeróbico', 'Moderada', 'diabetico tipo 2', 'Sobrepeso'),
('Domingo', 'Estiramiento De Antebrazos', 'Flexibilidad', 'Alta', 'diabetico tipo 2', 'Sobrepeso'),
('Domingo', 'Estiramiento De Muñeca', 'Flexibilidad', 'Alta', 'diabetico tipo 2', 'Sobrepeso'),
('Domingo', 'Estiramiento De Gemelos', 'Flexibilidad', 'Alta', ' diabetico tipo 2', 'Sobrepeso'),
('Domingo', 'Equilibrio En Talones', 'Equilibrio', 'Alta', 'diabetico tipo 2', 'Sobrepeso'),
('Domingo', 'Equilibrio Con Banda Elástica', 'Equilibrio', 'Alta', 'diabetico tipo 2', 'Sobrepeso');

-- Insertar plan de ejercicios para un Diabético Tipo 2 con IMC Obesidad Tipo I y II
INSERT INTO plans_exercises (Day, ExerciseName, ExerciseType, ExerciseIntensity, Disease, HealthClassification) VALUES
('Lunes', 'Saltos En Tijeras', 'Aeróbico', 'Moderada', 'diabetico tipo 2', 'Obesidad Tipo I y II'),
('Lunes', 'Caminar a paso ligero', 'Aeróbico', 'Moderada', 'diabetico tipo 2', 'Obesidad Tipo I y II'),
('Lunes', 'Sentadilla', 'Piernas', 'Moderada', 'diabetico tipo 2', 'Obesidad Tipo I y II'),
('Lunes', 'Sentadilla En Sumo', 'Pierna', 'Moderada', 'diabetico tipo 2', 'Obesidad Tipo I y II'),
('Lunes', 'Elevaciones Frontales De Hombro', 'Hombro', 'Moderada', 'diabetico tipo 2', 'Obesidad Tipo I y II'),
('Martes', 'Remo con barra', 'Fuerza', 'Alta', 'diabetico tipo 2', 'Obesidad Tipo I y II'),
('Martes', 'Press de banca', 'Fuerza', 'Alta', 'diabetico tipo 2', 'Obesidad Tipo I y II'),
('Martes', 'Flexiones De Pica Con Palma Hacia Abajo', 'Espalda', 'Moderada', 'diabetico tipo 2', 'Obesidad Tipo I y II'),
('Martes', 'Elevaciones De Tronco', 'Espalda', 'Moderada', 'diabetico tipo 2', 'Obesidad Tipo I y II'),
('Miercoles', 'Flexiones Tradicionales', 'Pecho', 'Moderada', 'diabetico tipo 2', 'Obesidad Tipo I y II'),
('Miercoles', 'Flexiones Con Banda Elastica', 'Pecho', 'Moderada', 'diabetico tipo 2', 'Obesidad Tipo I y II'),
('Miercoles', 'Equilibrio En T', 'Equilibrio', 'Moderada', 'diabetico tipo 2', 'Obesidad Tipo I y II'),
('Miercoles', 'Equilibrio Con Extensión De Brazos Y Piernas', 'Equilibrio', 'Moderada', 'diabetico tipo 2', 'Obesidad Tipo I y II'),
('Jueves', 'Fondos De Tríceps En Banco', 'Triceps', 'Alta', 'diabetico tipo 2', 'Obesidad Tipo I y II'),
('Jueves', 'Press De Hombros Con Mancuernas', 'Triceps', 'Alta', 'diabetico tipo 2', 'Obesidad Tipo I y II'),
('Jueves', 'Flexiones De Muñeca', 'Antebrazo', 'Moderada', 'diabetico tipo 2', 'Obesidad Tipo I y II'),
('Jueves', 'Extensiones De Muñeca', 'Antebrazo', 'Moderada', 'diabetico tipo 2', 'Obesidad Tipo I y II'),
('Viernes', 'Saltos En Cajas', 'Aeróbico', 'Moderada', 'diabetico tipo 2', 'Obesidad Tipo I y II'),
('Viernes', 'Skipping', 'Aeróbico', 'Moderada', 'diabetico tipo 2', 'Obesidad Tipo I y II'),
('Viernes', 'Elevacion De Rodilla', 'Anaerobico', 'Moderada', 'diabetico tipo 2', 'Obesidad Tipo I y II'),
('Viernes', 'Planchas', 'Anaerobico', 'Moderada', 'diabetico tipo 2', 'Obesidad Tipo I y II'),
('Sabado', 'Equilibrio Con Una Sola Pierna', 'Equilibrio', 'Alta', 'diabetico tipo 2', 'Obesidad Tipo I y II'),
('Sabado', 'Elevacion De Talón', 'Equilibrio', 'Alta', 'diabetico tipo 2', 'Obesidad Tipo I y II'),
('Sabado', 'Abdominales Tradicionales', 'Abdominales', 'Moderada', 'diabetico tipo 2', 'Obesidad Tipo I y II'),
('Sabado', 'Elevacion De Pierna', 'Abdominales', 'Moderada', 'diabetico tipo 2', 'Obesidad Tipo I y II'),
('Domingo', 'Postura Del Árbol', 'Flexibilidad', 'Moderada', 'diabetico tipo 2', 'Obesidad Tipo I y II'),
('Domingo', 'Estiramiento De Cuádriceps', 'Flexibilidad', 'Moderada', 'diabetico tipo 2', 'Obesidad Tipo I y II'),
('Domingo', 'Estiramiento de los isquiotibiales', 'Flexibilidad', 'Moderada', 'diabetico tipo 2', 'Obesidad Tipo I y II'),
('Domingo', 'Estiramiento del pecho', 'Flexibilidad', 'Moderada', 'diabetico tipo 2', 'Obesidad Tipo I y II');

-- Insertar plan de ejercicios para un Diabético Tipo 2 con IMC Obesidad Tipo III y IV
INSERT INTO plans_exercises (Day, ExerciseName, ExerciseType, ExerciseIntensity, Disease, HealthClassification) VALUES
('Lunes', 'Saltos En Tijeras', 'Aeróbico', 'Moderada', 'diabetico tipo 2', 'Obesidad Tipo III y IV'),
('Lunes', 'Caminar a paso ligero', 'Aeróbico', 'Moderada', 'diabetico tipo 2', 'Obesidad Tipo III y IV'),
('Lunes', 'Sentadilla', 'Piernas', 'Moderada', 'diabetico tipo 2', 'Obesidad Tipo III y IV'),
('Lunes', 'Sentadilla En Sumo', 'Pierna', 'Moderada', 'diabetico tipo 2', 'Obesidad Tipo III y IV'),
('Lunes', 'Elevaciones Frontales De Hombro', 'Hombro', 'Moderada', 'diabetico tipo 2', 'Obesidad Tipo III y IV'),
('Martes', 'Fondo En Silla', 'Triceps', 'Moderada', 'diabetico tipo 2', 'Obesidad Tipo III y IV'),
('Martes', 'Extensión De Tríceps Con Mancuernas Y Elevación De Talones', 'Triceps', 'Moderada', 'diabetico tipo 2', 'Obesidad Tipo III y IV'),
('Martes', 'Flexiones De Pica Con Palma Hacia Abajo', 'Espalda', 'Moderada', 'diabetico tipo 2', 'Obesidad Tipo III y IV'),
('Martes', 'Elevaciones De Tronco', 'Espalda', 'Moderada', 'diabetico tipo 2', 'Obesidad Tipo III y IV'),
('Miercoles', 'Flexiones Tradicionales', 'Pecho', 'Moderada', 'diabetico tipo 2', 'Obesidad Tipo III y IV'),
('Miercoles', 'Flexiones Con Banda Elastica', 'Pecho', 'Moderada', 'diabetico tipo 2', 'Obesidad Tipo III y IV'),
('Miercoles', 'Elevacion De Talones Con Banda Elastica', 'Pantorrilla', 'Moderada', 'diabetico tipo 2', 'Obesidad Tipo III y IV'),
('Miercoles', 'Extension De Muñeca Hacia Atras', 'Antebrazo', 'Moderada', 'diabetico tipo 2', 'Obesidad Tipo III y IV'),
('Jueves', 'Flexiones Con Agarre Estrecho', 'Biceps', 'Baja', 'diabetico tipo 2', 'Obesidad Tipo III y IV'),
('Jueves', 'Curl De Bíceps Cruzado Con Mancuernas Desde Banco Inclinado', 'Biceps', 'Baja', 'diabetico tipo 2', 'Obesidad Tipo III y IV'),
('Jueves', 'Flexiones De Muñeca', 'Antebrazo', 'Moderada', 'diabetico tipo 2', 'Obesidad Tipo III y IV'),
('Jueves', 'Extensiones De Muñeca', 'Antebrazo', 'Moderada', 'diabetico tipo 2', 'Obesidad Tipo III y IV'),
('Viernes', 'Saltos En Cajas', 'Aeróbico', 'Moderada', 'diabetico tipo 2', 'Obesidad Tipo III y IV'),
('Viernes', 'Skipping', 'Aeróbico', 'Moderada', 'diabetico tipo 2', 'Obesidad Tipo III y IV'),
('Viernes', 'Elevacion De Rodilla', 'Anaerobico', 'Moderada', 'diabetico tipo 2', 'Obesidad Tipo III y IV'),
('Viernes', 'Planchas', 'Anaerobico', 'Moderada', 'diabetico tipo 2', 'Obesidad Tipo III y IV'),
('Sabado', 'Equilibrio Con Una Sola Pierna', 'Equilibrio', 'Alta', 'diabetico tipo 2', 'Obesidad Tipo III y IV'),
('Sabado', 'Elevacion De Talón', 'Equilibrio', 'Alta', 'diabetico tipo 2', 'Obesidad Tipo III y IV'),
('Sabado', 'Abdominales Tradicionales', 'Abdominales', 'Moderada', 'diabetico tipo 2', 'Obesidad Tipo III y IV'),
('Sabado', 'Elevacion De Pierna', 'Abdominales', 'Moderada', 'diabetico tipo 2', 'Obesidad Tipo III y IV'),
('Domingo', 'Postura Del Árbol', 'Flexibilidad', 'Moderada', 'diabetico tipo 2', 'Obesidad Tipo III y IV'),
('Domingo', 'Estiramiento De Cuádriceps', 'Flexibilidad', 'Moderada', 'diabetico tipo 2', 'Obesidad Tipo III y IV'),
('Domingo', 'Estiramiento de los isquiotibiales', 'Flexibilidad', 'Moderada', 'diabetico tipo 2', 'Obesidad Tipo III y IV'),
('Domingo', 'Estiramiento del pecho', 'Flexibilidad', 'Moderada', 'diabetico tipo 2', 'Obesidad Tipo III y IV');